package repository;

import model.Difficulty;
import model.Question;

import java.util.List;

public class QuestionBank {

    private static final List<Question> QUESTIONS = List.of(
            new Question("OOP", "Java-da hansı açar söz bir sinifin başqa sinifdən miras almasını təmin edir?",
                    List.of("implements", "extends", "inherits", "super"), 1, Difficulty.EASY),
            new Question("OOP", "Aşağıdakılardan hansı Java-da çoxvarislik (multiple inheritance) əldə etmək üçün istifadə olunur?",
                    List.of("Abstract class", "Interface", "Final class", "Static class"), 1, Difficulty.MEDIUM),
            new Question("OOP", "Encapsulation (inkapsulyasiya) nəyi ifadə edir?",
                    List.of("Kod təkrarının aradan qaldırılması", "Data və metodların bir sinif daxilində gizlədilməsi",
                            "Sinifin genişləndirilməsi", "Metodun overload edilməsi"), 1, Difficulty.EASY),
            new Question("OOP", "Java-da 'this' açar sözü nə üçün istifadə olunur?",
                    List.of("Statik dəyişənə müraciət üçün", "Cari obyektə istinad üçün",
                            "Valideyn sinifə müraciət üçün", "Yeni obyekt yaratmaq üçün"), 1, Difficulty.EASY),
            new Question("OOP", "Polymorphism (çoxformalılıq) Java-da necə əldə edilir?",
                    List.of("Yalnız inheritance ilə", "Method overloading və overriding ilə",
                            "Yalnız interface ilə", "Statik metodlarla"), 1, Difficulty.MEDIUM),
            new Question("OOP", "Abstract class ilə interface arasındakı əsas fərq nədir (Java 8-ə qədər)?",
                    List.of("Abstract class-da constructor ola bilməz",
                            "Interface-də yalnız abstract metodlar ola bilərdi, abstract class-da isə implementasiya edilmiş metodlar da ola bilər",
                            "Fərq yoxdur", "Interface-dən birbaşa obyekt yaratmaq olar"), 1, Difficulty.MEDIUM),
            new Question("OOP", "Constructor overloading nə deməkdir?",
                    List.of("Eyni sinifdə fərqli parametrlərlə bir neçə constructor olması", "Constructor-un override edilməsi",
                            "Yalnız bir constructor olması", "Constructor-un private olması"), 0, Difficulty.EASY),
            new Question("OOP", "Java-da 'super' açar sözü nə üçün istifadə olunur?",
                    List.of("Cari obyektə istinad üçün", "Valideyn sinifin constructor və ya metodlarına müraciət üçün",
                            "Statik metod çağırmaq üçün", "Yeni obyekt yaratmaq üçün"), 1, Difficulty.EASY),
            new Question("OOP", "Java-da 'instanceof' operatoru nə üçün istifadə olunur?",
                    List.of("Obyektin müəyyən tipdən olub-olmadığını yoxlamaq üçün", "Yeni obyekt yaratmaq üçün",
                            "Metodu overload etmək üçün", "Sinifi final etmək üçün"), 0, Difficulty.EASY),
            new Question("OOP", "Composition (kompozisiya) inheritance-dan nə ilə fərqlənir?",
                    List.of("Composition 'has-a', inheritance 'is-a' münasibətini ifadə edir", "Fərq yoxdur",
                            "Composition yalnız interfeyslərlə işləyir", "Inheritance daha çevikdir"), 0, Difficulty.MEDIUM),

            new Question("Kolleksiyalar", "ArrayList və LinkedList arasındakı əsas fərq nədir?",
                    List.of("ArrayList sıralanmır", "ArrayList array əsaslıdır, LinkedList node əsaslıdır",
                            "LinkedList thread-safe-dir", "Fərq yoxdur"), 1, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "HashMap-də açarların unikallığı necə təmin olunur?",
                    List.of("equals() və hashCode() metodları ilə", "compareTo() metodu ilə",
                            "toString() metodu ilə", "clone() metodu ilə"), 0, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "Hansı kolleksiya interfeysi dublikat elementlərə icazə vermir?",
                    List.of("List", "Set", "Queue", "Map (values)"), 1, Difficulty.EASY),
            new Question("Kolleksiyalar", "TreeMap elementləri necə saxlayır?",
                    List.of("Təsadüfi ardıcıllıqla", "Açarların təbii sıralaması ilə",
                            "Əlavə olunma ardıcıllığı ilə", "Heç bir sıralama olmadan"), 1, Difficulty.HARD),
            new Question("Kolleksiyalar", "Iterator və ListIterator arasındakı fərq nədir?",
                    List.of("ListIterator yalnız irəli hərəkət edir", "ListIterator həm irəli, həm geri hərəkət edə bilər",
                            "Iterator List üçün işləmir", "Fərq yoxdur"), 1, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "ConcurrentModificationException nə vaxt yaranır?",
                    List.of("Kolleksiya iterasiya zamanı birbaşa dəyişdirildikdə", "Kolleksiya boş olduqda",
                            "Kolleksiya sıralandıqda", "Heç vaxt"), 0, Difficulty.HARD),
            new Question("Kolleksiyalar", "PriorityQueue elementləri necə sıralayır?",
                    List.of("Əlavə olunma ardıcıllığı ilə", "Təbii sıralama və ya verilmiş Comparator əsasında",
                            "Təsadüfi", "Sıralamır"), 1, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "Collections.unmodifiableList() nə edir?",
                    List.of("List-i sıralayır", "List-in dəyişdirilə bilməyən görünüşünü qaytarır",
                            "List-i kopyalayır", "List-i silir"), 1, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "LinkedHashMap HashMap-dən nə ilə fərqlənir?",
                    List.of("Elementlərin əlavə olunma ardıcıllığını saxlayır", "Sürəti daha yüksəkdir",
                            "Null açara icazə vermir", "Fərq yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "Comparable və Comparator interfeysləri arasındakı fərq nədir?",
                    List.of("Comparable sinifin öz daxilində təbii sıralamanı, Comparator isə xarici, xüsusi sıralamanı təyin edir",
                            "Fərq yoxdur", "Comparator yalnız String üçündür", "Comparable xarici sıralama üçündür"),
                    0, Difficulty.MEDIUM),

            new Question("İstisnalar", "Checked və unchecked exception arasındakı fərq nədir?",
                    List.of("Checked exception-lar compile zamanı yoxlanılır", "Unchecked exception-lar compile zamanı yoxlanılır",
                            "Fərq yoxdur", "Checked exception-lar yalnız runtime-da olur"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "finally bloku nə vaxt icra olunur?",
                    List.of("Yalnız exception atılarsa", "Yalnız exception atılmazsa",
                            "Həmişə, exception olub-olmamasından asılı olmayaraq", "Heç vaxt"), 2, Difficulty.EASY),
            new Question("İstisnalar", "Öz custom exception sinifinizi yaratmaq üçün hansı sinifi extend etməlisiniz?",
                    List.of("Throwable və ya Exception", "Object", "RuntimeError", "Error only"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "try-with-resources nə üçün istifadə olunur?",
                    List.of("Exception-ları tutmaq üçün", "Resursların avtomatik bağlanması üçün",
                            "Yeni thread yaratmaq üçün", "Statik dəyişən elan etmək üçün"), 1, Difficulty.MEDIUM),
            new Question("İstisnalar", "throw və throws açar sözləri arasındakı fərq nədir?",
                    List.of("throw exception atmaq üçün, throws metodun imzasında istisna elan etmək üçün istifadə olunur",
                            "Fərq yoxdur", "throws yalnız runtime exception üçündür", "throw metodun imzasında istifadə olunur"),
                    0, Difficulty.MEDIUM),
            new Question("İstisnalar", "NullPointerException hansı halda yaranır?",
                    List.of("Massiv indeksi hüdüddan kənara çıxdıqda", "null referensiya üzərində metod çağırıldıqda",
                            "Fayl tapılmadıqda", "Rəqəm formatı səhv olduqda"), 1, Difficulty.EASY),
            new Question("İstisnalar", "Multi-catch bloku (catch (IOException | SQLException e)) nə üçün istifadə olunur?",
                    List.of("Bir neçə exception tipini eyni blokda tutmaq üçün", "Yalnız bir exception tipini tutmaq üçün",
                            "Exception-ı yenidən atmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "StackOverflowError nə vaxt yaranır?",
                    List.of("Yaddaş kifayət etmədikdə", "Sonsuz və ya çox dərin rekursiya zamanı",
                            "Fayl tapılmadıqda", "Massiv hüdüddan kənar çıxdıqda"), 1, Difficulty.MEDIUM),
            new Question("İstisnalar", "Exception chaining (səbəb zənciri) nə üçün istifadə olunur?",
                    List.of("Orijinal xətanın səbəbini itirmədən yeni exception atmaq üçün", "Exception-ları silmək üçün",
                            "Performansı artırmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "Error və Exception arasındakı fərq nədir?",
                    List.of("Error adətən proqramın idarə edə bilmədiyi ciddi problemlər (məs. OutOfMemoryError), Exception isə tutula bilən vəziyyətlərdir",
                            "Fərq yoxdur", "Error həmişə checked-dir", "Exception yalnız runtime-dadır"), 0, Difficulty.MEDIUM),

            new Question("Multithreading", "Java-da yeni thread yaratmağın neçə əsas yolu var?",
                    List.of("1", "2 (Thread sinifi və Runnable interfeysi)", "3", "4"), 1, Difficulty.EASY),
            new Question("Multithreading", "'synchronized' açar sözü nə üçün istifadə olunur?",
                    List.of("Kodu sürətləndirmək üçün", "Bir vaxtda yalnız bir thread-in bloka girməsini təmin etmək üçün",
                            "Yeni thread yaratmaq üçün", "Thread-i dayandırmaq üçün"), 1, Difficulty.MEDIUM),
            new Question("Multithreading", "Thread.sleep() metodu nə edir?",
                    List.of("Thread-i həmişəlik dayandırır", "Thread-i müəyyən müddətə pauza edir",
                            "Thread-i öldürür", "Yeni thread yaradır"), 1, Difficulty.EASY),
            new Question("Multithreading", "Deadlock nə deməkdir?",
                    List.of("Thread-lərin bir-birini gözləyərək sonsuz bloklanması", "Thread-in normal bitməsi",
                            "Thread-in sürətlə işləməsi", "Bir thread-in digərini yaratması"), 0, Difficulty.HARD),
            new Question("Multithreading", "wait() və sleep() metodları arasındakı fərq nədir?",
                    List.of("wait() monitoru buraxır, sleep() buraxmır", "Fərq yoxdur",
                            "sleep() monitoru buraxır", "wait() yalnız static metoddur"), 0, Difficulty.HARD),
            new Question("Multithreading", "ExecutorService nə üçün istifadə olunur?",
                    List.of("Thread-lərin pool şəklində idarə edilməsi üçün", "Yaddaşı təmizləmək üçün",
                            "Fayl oxumaq üçün", "Exception tutmaq üçün"), 0, Difficulty.MEDIUM),
            new Question("Multithreading", "Runnable və Callable arasındakı fərq nədir?",
                    List.of("Callable nəticə qaytara bilər və exception ata bilər, Runnable qaytara bilməz", "Fərq yoxdur",
                            "Runnable nəticə qaytarır", "Callable yalnız static-dir"), 0, Difficulty.MEDIUM),
            new Question("Multithreading", "Thread-safe kolleksiyaya nümunə göstərin.",
                    List.of("ArrayList", "HashMap", "ConcurrentHashMap", "LinkedList"), 2, Difficulty.MEDIUM),
            new Question("Multithreading", "volatile açar sözünün təyinatı nədir?",
                    List.of("Dəyişənin dəyərinin bütün thread-lər üçün həmişə yaddaşdan (cache-dən deyil) oxunmasını təmin edir",
                            "Dəyişəni final edir", "Thread yaradır", "Sinxronizasiya əvəz edir"), 0, Difficulty.HARD),
            new Question("Multithreading", "Thread pool-un istifadəsinin əsas üstünlüyü nədir?",
                    List.of("Hər tapşırıq üçün yeni thread yaratmaqdan qaçaraq resursları səmərəli idarə etmək",
                            "Kodu qısaltmaq", "Yaddaşı artırmaq", "Heç bir üstünlüyü yoxdur"), 0, Difficulty.MEDIUM),

            new Question("JVM və Yaddaş", "Garbage Collector-un vəzifəsi nədir?",
                    List.of("Kodu compile etmək", "İstifadə olunmayan obyektləri yaddaşdan silmək",
                            "Thread-ləri idarə etmək", "Faylları oxumaq"), 1, Difficulty.EASY),
            new Question("JVM və Yaddaş", "Java-da 'Heap' yaddaşı nə üçün istifadə olunur?",
                    List.of("Statik dəyişənlər üçün", "Obyektlərin saxlanması üçün",
                            "Metod çağırışları üçün", "Yalnız primitivlər üçün"), 1, Difficulty.MEDIUM),
            new Question("JVM və Yaddaş", "JVM, JRE və JDK arasındakı fərq nədir?",
                    List.of("Eynidir", "JDK development üçün, JRE işə salma üçün, JVM bytecode icrası üçündür",
                            "JVM yalnız compile edir", "JRE yalnız development üçündür"), 1, Difficulty.MEDIUM),
            new Question("JVM və Yaddaş", "'static' açar sözü ilə elan olunan dəyişən nəyə aiddir?",
                    List.of("Yalnız bir obyektə", "Sinifin özünə, bütün obyektlər üçün ortaqdır",
                            "Yalnız local metoda", "Heç nəyə"), 1, Difficulty.EASY),
            new Question("JVM və Yaddaş", "Stack yaddaşında nə saxlanılır?",
                    List.of("Obyektlər", "Metod çağırışları və lokal dəyişənlər",
                            "Statik dəyişənlər", "Class faylları"), 1, Difficulty.EASY),
            new Question("JVM və Yaddaş", "'final' açar sözü dəyişənə tətbiq edildikdə nə deməkdir?",
                    List.of("Dəyişənin dəyəri bir dəfə təyin edildikdən sonra dəyişdirilə bilməz",
                            "Dəyişən yalnız static olur", "Dəyişən yalnız private olur", "Heç nə demək deyil"),
                    0, Difficulty.EASY),
            new Question("JVM və Yaddaş", "Memory leak Java-da necə baş verə bilər?",
                    List.of("Java-da memory leak mümkün deyil", "İstifadə olunmayan obyektlərə hələ də referans saxlanıldıqda GC onları təmizləyə bilmir",
                            "Yalnız native kodda olur", "Yalnız Stack-də olur"), 1, Difficulty.HARD),
            new Question("JVM və Yaddaş", "Classloader-in vəzifəsi nədir?",
                    List.of(".class fayllarını yaddaşa yükləmək", "Kodu compile etmək",
                            "Thread yaratmaq", "Faylları oxumaq"), 0, Difficulty.MEDIUM),
            new Question("JVM və Yaddaş", "JIT (Just-In-Time) compiler nə edir?",
                    List.of("Bytecode-u runtime-da native maşın koduna çevirərək performansı artırır", "Kodu yalnız compile zamanı yoxlayır",
                            "Yaddaşı təmizləyir", "Thread yaradır"), 0, Difficulty.HARD),
            new Question("JVM və Yaddaş", "Metaspace (Java 8+) nə üçün istifadə olunur?",
                    List.of("Sinif metadata-sının saxlanması üçün (əvvəlki PermGen-in əvəzi)", "Obyektlərin saxlanması üçün",
                            "Lokal dəyişənlər üçün", "Thread stack-i üçün"), 0, Difficulty.HARD),

            new Question("String", "Java-da String niyə immutable-dır?",
                    List.of("Performans üçün lazım deyil", "Təhlükəsizlik, thread-safety və String Pool-un səmərəli işləməsi üçün",
                            "Compiler tələb edir", "Heç bir səbəb yoxdur"), 1, Difficulty.MEDIUM),
            new Question("String", "String, StringBuilder və StringBuffer arasındakı fərq nədir?",
                    List.of("String mutable, StringBuilder immutable-dır",
                            "StringBuilder thread-safe deyil, StringBuffer thread-safe-dir, String isə immutable-dır",
                            "Fərq yoxdur", "StringBuffer immutable-dır"), 1, Difficulty.MEDIUM),
            new Question("String", "'==' operatoru ilə .equals() metodu String-lər üçün nəyə görə fərqlənir?",
                    List.of("'==' referensiyanı, equals() məzmunu müqayisə edir", "Fərq yoxdur",
                            "equals() referensiyanı müqayisə edir", "'==' həmişə true qaytarır"), 0, Difficulty.EASY),
            new Question("String", "String Pool nədir?",
                    List.of("Bütün obyektlərin saxlandığı yaddaş",
                            "JVM-in string literal-ları təkrar istifadə üçün saxladığı xüsusi yaddaş sahəsi",
                            "Fayl sistemi", "Thread pool-un digər adı"), 1, Difficulty.MEDIUM),
            new Question("String", "intern() metodu nə edir?",
                    List.of("String-i massivə çevirir", "String-i String Pool-a əlavə edir və ya oradan qaytarır",
                            "String-i böyük hərflərə çevirir", "String-i silir"), 1, Difficulty.HARD),
            new Question("String", "String.format() metodunun məqsədi nədir?",
                    List.of("String-i parçalamaq", "Şablon əsasında formatlanmış string yaratmaq",
                            "String-i şifrələmək", "String-i müqayisə etmək"), 1, Difficulty.EASY),
            new Question("String", "StringBuilder-in append() metodu nə edir?",
                    List.of("Yeni String yaradır", "Mövcud StringBuilder-ə məzmun əlavə edir (mutable)",
                            "String-i silir", "String-i tərsinə çevirir"), 1, Difficulty.EASY),
            new Question("String", "String.split() metodu nə qaytarır?",
                    List.of("Tək String", "String massivi", "List<Character>", "Boolean"), 1, Difficulty.EASY),
            new Question("String", "String.valueOf() metodunun məqsədi nədir?",
                    List.of("İstənilən tipi String-ə çevirmək", "String-i silmək",
                            "String-i şifrələmək", "String uzunluğunu ölçmək"), 0, Difficulty.EASY),
            new Question("String", "StringBuilder-in ilkin tutumu (capacity) neçədir (default konstruktorla)?",
                    List.of("0", "16", "100", "Sonsuz"), 1, Difficulty.HARD),

            new Question("Generics", "Generics-in əsas məqsədi nədir?",
                    List.of("Kodun icra sürətini artırmaq", "Compile-time tip təhlükəsizliyi təmin etmək",
                            "Yaddaşı azaltmaq", "Multithreading dəstəkləmək"), 1, Difficulty.MEDIUM),
            new Question("Generics", "'List<?>' ifadəsi nəyi bildirir?",
                    List.of("İstənilən tipdə element saxlaya bilən wildcard List", "Yalnız Integer List",
                            "Boş List", "Sabit tipli List"), 0, Difficulty.MEDIUM),
            new Question("Generics", "'<T extends Number>' bildirişi nəyi ifadə edir?",
                    List.of("T tipi Number sinifini extend edən tip olmalıdır", "T yalnız String ola bilər",
                            "Heç bir məhdudiyyət yoxdur", "T mütləq abstrakt olmalıdır"), 0, Difficulty.HARD),
            new Question("Generics", "Type erasure nədir?",
                    List.of("Compile zamanı generic tip məlumatının silinməsi (runtime-da olmaması)",
                            "Runtime-da tip yaradılması", "Generic siniflərin silinməsi", "Heç bir əlaqəsi yoxdur"),
                    0, Difficulty.HARD),
            new Question("Generics", "Generic metod necə elan olunur?",
                    List.of("Metod adından əvvəl tip parametri ilə, məs. <T> T method()", "Yalnız sinif səviyyəsində",
                            "Generic metod mümkün deyil", "Return tipindən sonra"), 0, Difficulty.MEDIUM),
            new Question("Generics", "Raw type (məs. List list = new ArrayList()) istifadəsi nə üçün tövsiyə olunmur?",
                    List.of("Compile-time tip yoxlamasını itirir", "Daha sürətli işləyir",
                            "Daha az yaddaş tutur", "Heç bir problem yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Generics", "'? super T' wildcard nəyi ifadə edir?",
                    List.of("T və ya onun hər hansı superclass-ı", "T və ya onun subclass-ları",
                            "Yalnız T", "Heç bir tip"), 0, Difficulty.HARD),
            new Question("Generics", "Generic sinifdə statik sahə niyə generic tip parametrindən istifadə edə bilməz?",
                    List.of("Statik sahələr bütün instansiyalar arasında paylaşılır, amma generic tip hər instansiya üçün fərqli ola bilər",
                            "Statik sahələr generic ola bilər", "Heç bir səbəb yoxdur", "Statik sahələr yalnız private olur"),
                    0, Difficulty.HARD),
            new Question("Generics", "Bounded type parameter nədir?",
                    List.of("Tip parametrinin müəyyən sinif və ya interfeys ilə məhdudlaşdırılması (məs. <T extends Comparable>)",
                            "Sərhədsiz tip", "Yalnız primitiv tiplər", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Generics", "Generic array yaratmaq (məs. new T[10]) Java-da niyə mümkün deyil?",
                    List.of("Type erasure səbəbindən runtime-da tip məlumatı olmur", "Java array dəstəkləmir",
                            "Yaddaş çatışmır", "Heç bir səbəb yoxdur"), 0, Difficulty.HARD),

            new Question("Stream və Lambda", "Lambda ifadəsi nədir?",
                    List.of("Anonim funksiyanın qısa yazılış forması", "Yeni sinif tipi",
                            "Statik metod", "Exception növü"), 0, Difficulty.EASY),
            new Question("Stream və Lambda", "Stream API-də 'map()' metodu nə edir?",
                    List.of("Elementləri filtr edir", "Hər elementi başqa formaya çevirir",
                            "Elementləri sıralayır", "Stream-i bağlayır"), 1, Difficulty.EASY),
            new Question("Stream və Lambda", "'filter()' və 'map()' arasındakı fərq nədir?",
                    List.of("filter() şərtə uyğun elementləri seçir, map() elementləri çevirir", "Fərq yoxdur",
                            "map() elementləri seçir", "filter() elementləri çevirir"), 0, Difficulty.EASY),
            new Question("Stream və Lambda", "Stream-lər neçə dəfə istifadə oluna bilər?",
                    List.of("Sonsuz sayda", "Yalnız bir dəfə (terminal əməliyyatdan sonra bağlanır)",
                            "İki dəfə", "Yalnız paralel rejimdə"), 1, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "'reduce()' metodunun məqsədi nədir?",
                    List.of("Stream elementlərini bir nəticəyə birləşdirmək", "Stream-i sıralamaq",
                            "Stream-i filtr etmək", "Yeni stream yaratmaq"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Functional interface nədir?",
                    List.of("Yalnız bir abstract metodu olan interfeys", "Bir neçə metodu olan sinif",
                            "Statik siniflər üçün istifadə olunan interfeys", "Generic interfeys"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Optional sinifinin məqsədi nədir?",
                    List.of("null yoxlamasını daha təhlükəsiz və aydın etmək", "Yeni thread yaratmaq",
                            "Exception atmaq", "Kolleksiyanı sıralamaq"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Stream.collect(Collectors.toList()) nə edir?",
                    List.of("Stream elementlərini List-ə toplayır", "Stream-i bağlayır",
                            "Elementləri silir", "Yeni Stream yaradır"), 0, Difficulty.EASY),
            new Question("Stream və Lambda", "Method reference (məs. String::toUpperCase) nədir?",
                    List.of("Mövcud metodu lambda əvəzinə istinad etmək üçün qısa yazılış", "Yeni metod yaratmaq",
                            "Metodu silmək", "Statik dəyişən"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Parallel stream nə vaxt istifadə edilməlidir?",
                    List.of("Böyük data həcmində, çoxnüvəli emalın faydalı olduğu hallarda", "Həmişə",
                            "Heç vaxt", "Yalnız kiçik data üçün"), 0, Difficulty.MEDIUM),

            new Question("SOLID Prinsipləri", "Single Responsibility Principle (SRP) nəyi ifadə edir?",
                    List.of("Bir sinifin yalnız bir dəyişmə səbəbi olmalıdır", "Sinif çoxlu interfeys implementasiya etməlidir",
                            "Bir sinif yalnız bir metoda malik olmalıdır", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Open/Closed Principle nə deməkdir?",
                    List.of("Siniflər genişlənməyə açıq, dəyişikliyə qapalı olmalıdır", "Bütün siniflər final olmalıdır",
                            "Siniflər həmişə açıq (public) olmalıdır", "Heç bir əlaqəsi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Liskov Substitution Principle nəyi tələb edir?",
                    List.of("Alt sinif öz valideyn sinifinin yerinə istifadə oluna bilməlidir, davranışı pozmadan",
                            "Alt sinif valideyndən fərqli davranmalıdır", "İnterfeyslər əvəz oluna bilməz", "Heç bir mənası yoxdur"),
                    0, Difficulty.HARD),
            new Question("SOLID Prinsipləri", "Interface Segregation Principle nəyi tövsiyə edir?",
                    List.of("Böyük, hər şeyi əhatə edən interfeyslər yaratmaq",
                            "Klientlərin istifadə etmədiyi metodlara asılı olmamaq üçün kiçik, spesifik interfeyslər yaratmaq",
                            "Yalnız bir interfeys istifadə etmək", "İnterfeysləri ümumiyyətlə istifadə etməmək"), 1, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Dependency Inversion Principle nəyi ifadə edir?",
                    List.of("Yüksək səviyyəli modullar aşağı səviyyəli modullardan deyil, abstraksiyalardan asılı olmalıdır",
                            "Bütün siniflər bir-birindən asılı olmalıdır", "Asılılıqlar həmişə konkret siniflər olmalıdır",
                            "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("SOLID Prinsipləri", "SOLID prinsiplərinin əsas məqsədi nədir?",
                    List.of("Kodu daha çətin oxunan etmək", "Daha çevik, davamlı (maintainable) və genişlənə bilən kod yazmaq",
                            "Kodun sətir sayını artırmaq", "Yalnız performansı artırmaq"), 1, Difficulty.EASY),
            new Question("SOLID Prinsipləri", "SOLID-in 'S' hərfi nəyi bildirir?",
                    List.of("Simple", "Single Responsibility", "Static", "Secure"), 1, Difficulty.EASY),
            new Question("SOLID Prinsipləri", "Dependency Injection SOLID-in hansı prinsipi ilə birbaşa bağlıdır?",
                    List.of("Single Responsibility", "Open/Closed", "Dependency Inversion", "Liskov Substitution"),
                    2, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "SOLID-in 'O' hərfi hansı prinsipi bildirir?",
                    List.of("Open/Closed Principle", "Object Principle", "Optional Principle", "Override Principle"),
                    0, Difficulty.EASY),
            new Question("SOLID Prinsipləri", "Liskov Substitution Principle pozulduqda adətən nə baş verir?",
                    List.of("Alt sinif valideynin yerinə istifadə edildikdə gözlənilməz davranış yaranır", "Heç nə dəyişmir",
                            "Proqram sürətlənir", "Yaddaş azalır"), 0, Difficulty.MEDIUM),

            new Question("Dizayn Şablonları", "Singleton dizayn şablonu nəyi təmin edir?",
                    List.of("Bir sinifdən yalnız bir obyekt yaradılmasını", "Çoxlu obyekt yaradılmasını",
                            "Sinifin final olmasını", "İnterfeys yaradılmasını"), 0, Difficulty.EASY),
            new Question("Dizayn Şablonları", "Factory Method şablonunun məqsədi nədir?",
                    List.of("Obyekt yaratma məntiqini alt siniflərə həvalə etmək", "Obyektləri silmək",
                            "Thread yaratmaq", "Exception idarə etmək"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Observer dizayn şablonu nə üçün istifadə olunur?",
                    List.of("Bir obyektin vəziyyəti dəyişdikdə asılı obyektləri xəbərdar etmək üçün", "Obyektləri kopyalamaq üçün",
                            "Yaddaşı idarə etmək üçün", "Thread sinxronizasiyası üçün"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Builder dizayn şablonu hansı problemi həll edir?",
                    List.of("Çoxlu parametrli mürəkkəb obyektlərin addım-addım qurulması", "Obyektlərin silinməsi",
                            "Interfeyslərin birləşdirilməsi", "Thread-lərin idarə edilməsi"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Strategy dizayn şablonu nəyi təmin edir?",
                    List.of("Alqoritmləri runtime-da dəyişdirmək imkanı", "Sinifin tək instansiya olmasını",
                            "Obyektlərin klonlanmasını", "Yaddaşın azaldılmasını"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Decorator dizayn şablonu nə edir?",
                    List.of("Obyektə runtime-da əlavə funksionallıq qoşur, inheritance olmadan", "Obyekti silir",
                            "Yeni sinif yaradır", "Thread yaradır"), 0, Difficulty.HARD),
            new Question("Dizayn Şablonları", "Adapter dizayn şablonu nə üçün istifadə olunur?",
                    List.of("Uyğun olmayan interfeysləri bir-biri ilə işləməyə uyğunlaşdırmaq üçün", "Obyektləri sıralamaq üçün",
                            "Yaddaşı təmizləmək üçün", "Exception tutmaq üçün"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Dependency Injection dizayn şablonunun əsas faydası nədir?",
                    List.of("Siniflər arasında sıx bağlılığı (tight coupling) azaltmaq", "Kodu daha uzun etmək",
                            "Performansı azaltmaq", "Heç bir faydası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Facade dizayn şablonu nə edir?",
                    List.of("Mürəkkəb alt sistemə sadə interfeys təqdim edir", "Obyektləri klonlayır",
                            "Thread yaradır", "Exception tutur"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Command dizayn şablonu nəyi encapsulate edir?",
                    List.of("Bir sorğunu (request) obyekt kimi", "Yalnız data-nı", "Thread-i", "Exception-ı"),
                    0, Difficulty.HARD),

            new Question("Java 8+ Xüsusiyyətləri", "'var' açar sözü Java-da nəyi ifadə edir?",
                    List.of("Dinamik tip (JavaScript kimi)", "Compile zamanı tipin avtomatik nəticə çıxarılması (local variable type inference)",
                            "Yeni primitiv tip", "Generic wildcard"), 1, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Record (Java 14+) nədir?",
                    List.of("Dəyişən (mutable) sinif", "Immutable data daşıyan qısa yazılış formalı sinif",
                            "Interfeys növü", "Exception növü"), 1, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Sealed class (Java 17+) nəyi məhdudlaşdırır?",
                    List.of("Hansı siniflərin onu extend edə biləcəyini", "Metodların sayını",
                            "Sahələrin görünürlüyünü", "Constructor sayını"), 0, Difficulty.HARD),
            new Question("Java 8+ Xüsusiyyətləri", "Text block (\"\"\"...\"\"\") Java 15+-da nə üçün istifadə olunur?",
                    List.of("Çoxsətirli string-ləri rahat yazmaq üçün", "Şifrələmə üçün",
                            "Fayl oxumaq üçün", "Regex yazmaq üçün"), 0, Difficulty.EASY),
            new Question("Java 8+ Xüsusiyyətləri", "Switch expression (Java 14+) klassik switch-dən nə ilə fərqlənir?",
                    List.of("Dəyər qaytara bilər və fallthrough-u aradan qaldırır", "Yalnız String üçün işləyir",
                            "Fərq yoxdur", "Yalnız bir case qəbul edir"), 0, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Pattern matching for instanceof (Java 16+) nəyi asanlaşdırır?",
                    List.of("instanceof yoxlamasından sonra əlavə casting-i aradan qaldırır", "Yaddaş idarəetməsini",
                            "Thread yaratmağı", "Exception idarəetməsini"), 0, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Optional.orElseGet() və Optional.orElse() arasındakı fərq nədir?",
                    List.of("orElseGet() dəyər boş olduqda supplier-i lazy şəkildə çağırır, orElse() isə həmişə hesablanır",
                            "Fərq yoxdur", "orElse() lazy-dir", "orElseGet() həmişə null qaytarır"), 0, Difficulty.HARD),
            new Question("Java 8+ Xüsusiyyətləri", "CompletableFuture nə üçün istifadə olunur?",
                    List.of("Asinxron, qeyri-blok edən əməliyyatları idarə etmək üçün", "Statik dəyişən yaratmaq üçün",
                            "Kolleksiyanı sıralamaq üçün", "Fayl oxumaq üçün"), 0, Difficulty.HARD),
            new Question("Java 8+ Xüsusiyyətləri", "Enhanced for-each loop-da 'var' istifadəsi nəyə imkan verir?",
                    List.of("Tipin kompilyator tərəfindən avtomatik müəyyən edilməsinə", "Sonsuz dövrəyə",
                            "Massivin silinməsinə", "Heç nəyə"), 0, Difficulty.EASY),
            new Question("Java 8+ Xüsusiyyətləri", "java.time paketi (Java 8+) nəyi əvəz etmək üçün təqdim olunub?",
                    List.of("Köhnə və problemli java.util.Date/Calendar siniflərini", "String sinifini",
                            "Collections API-ni", "IO paketini"), 0, Difficulty.MEDIUM),

            new Question("Testing", "JUnit-də @Test annotasiyası nə üçün istifadə olunur?",
                    List.of("Metodun test metodu olduğunu bildirmək üçün", "Sinifi abstrakt etmək üçün",
                            "Metodu private etmək üçün", "Exception atmaq üçün"), 0, Difficulty.EASY),
            new Question("Testing", "@BeforeEach annotasiyası nə vaxt icra olunur?",
                    List.of("Bütün testlərdən əvvəl bir dəfə", "Hər testdən əvvəl",
                            "Bütün testlərdən sonra", "Heç vaxt"), 1, Difficulty.EASY),
            new Question("Testing", "Mock obyekt nə üçün istifadə olunur?",
                    List.of("Real asılılıqları simulyasiya edərək təcrid olunmuş test yazmaq üçün", "Verilənlər bazasına qoşulmaq üçün",
                            "Performansı artırmaq üçün", "Kodu compile etmək üçün"), 0, Difficulty.MEDIUM),
            new Question("Testing", "assertEquals() metodu nə edir?",
                    List.of("İki dəyərin bərabər olub-olmadığını yoxlayır", "İki dəyəri toplayır",
                            "Exception atır", "Testi dayandırır"), 0, Difficulty.EASY),
            new Question("Testing", "Unit test və Integration test arasındakı fərq nədir?",
                    List.of("Unit test bir komponenti təcrid şəkildə, integration test isə komponentlərin birgə işini test edir",
                            "Fərq yoxdur", "Integration test daha sürətlidir", "Unit test verilənlər bazasını yoxlayır"),
                    0, Difficulty.MEDIUM),
            new Question("Testing", "assertThrows() nə üçün istifadə olunur?",
                    List.of("Metodun müəyyən exception atdığını yoxlamaq üçün", "Metodun sürətini ölçmək üçün",
                            "Metodu dayandırmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Testing", "Test coverage (kod əhatəsi) nəyi göstərir?",
                    List.of("Kodun neçə faizinin testlərlə əhatə olunduğunu", "Testlərin sürətini",
                            "Bug sayını", "Sinif sayını"), 0, Difficulty.EASY),
            new Question("Testing", "TDD (Test-Driven Development) yanaşmasının əsas prinsipi nədir?",
                    List.of("Əvvəlcə testi yazmaq, sonra onu keçən kodu yazmaq", "Əvvəlcə kodu yazmaq, sonra test yazmaq",
                            "Test yazmamaq", "Yalnız manual test etmək"), 0, Difficulty.MEDIUM),
            new Question("Testing", "@Mock və @InjectMocks annotasiyaları (Mockito) nə üçün istifadə olunur?",
                    List.of("Mock obyektlər yaratmaq və onları test olunan sinifə inject etmək üçün", "Verilənlər bazası qoşulması üçün",
                            "Performans testi üçün", "UI testi üçün"), 0, Difficulty.MEDIUM),
            new Question("Testing", "Parametrized test nə üçün istifadə olunur?",
                    List.of("Eyni test metodunu fərqli giriş dəyərləri ilə dəfələrlə işlətmək üçün", "Testi yavaşlatmaq üçün",
                            "Yalnız bir dəyərlə test etmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),

            new Question("Spring Framework Əsasları", "Spring Framework-də IoC (Inversion of Control) nəyi ifadə edir?",
                    List.of("Obyektlərin yaradılması və idarəsinin proqramçıdan konteynerə keçməsi", "Kodun sürətləndirilməsi",
                            "Verilənlər bazası idarəetməsi", "Thread idarəetməsi"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "@Autowired annotasiyası nə üçün istifadə olunur?",
                    List.of("Asılılıqların (dependency) avtomatik inject edilməsi üçün", "Sinifi final etmək üçün",
                            "Metodu test etmək üçün", "Exception tutmaq üçün"), 0, Difficulty.EASY),
            new Question("Spring Framework Əsasları", "Spring-də Bean nədir?",
                    List.of("Spring konteyneri tərəfindən idarə olunan obyekt", "Verilənlər bazası cədvəli",
                            "Exception növü", "Test sinifi"), 0, Difficulty.EASY),
            new Question("Spring Framework Əsasları", "@Component, @Service və @Repository annotasiyaları arasındakı fərq nədir?",
                    List.of("Hamısı eyni məqsədi daşıyır, amma qatları (layer) semantik olaraq fərqləndirir", "Tamamilə fərqli işlər görürlər",
                            "Yalnız @Component işləyir", "Heç bir fərq yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring Boot-un əsas üstünlüyü nədir?",
                    List.of("Auto-configuration və embedded server ilə tez başlanğıc təmin etmək", "Yalnız UI yaratmaq",
                            "Yalnız verilənlər bazası ilə işləmək", "Heç bir üstünlüyü yoxdur"), 0, Difficulty.EASY),
            new Question("Spring Framework Əsasları", "Dependency Injection-un növləri hansılardır?",
                    List.of("Constructor, Setter və Field injection", "Yalnız Constructor injection",
                            "Yalnız Field injection", "Heç biri"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "@RestController annotasiyası nə edir?",
                    List.of("Sinifi REST controller kimi işarələyir və metodların qaytardığı obyektləri JSON-a çevirir",
                            "Verilənlər bazası bağlantısı yaradır", "Testi işə salır", "Thread yaradır"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring-də Bean-in default scope-u nədir?",
                    List.of("Prototype", "Singleton", "Request", "Session"), 1, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "@Transactional annotasiyası nəyi təmin edir?",
                    List.of("Metodun tranzaksiya daxilində icra olunmasını", "Metodun sürətlənməsini",
                            "Metodun test olunmasını", "Heç nəyi"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring-də Application Context nədir?",
                    List.of("Bean-lərin yaradılması, konfiqurasiyası və idarəsi üçün IoC konteyneri", "Verilənlər bazası",
                            "Test framework-ü", "Fayl sistemi"), 0, Difficulty.MEDIUM),

            new Question("JDBC və Verilənlər Bazası", "JDBC nədir?",
                    List.of("Java-dan verilənlər bazasına qoşulmaq üçün standart API", "Java-nın test framework-ü",
                            "Yeni proqramlaşdırma dili", "Web server"), 0, Difficulty.EASY),
            new Question("JDBC və Verilənlər Bazası", "PreparedStatement, Statement-dən nə ilə fərqlənir?",
                    List.of("Parametrləşdirilmiş sorğulara imkan verir və SQL injection-a qarşı daha təhlükəsizdir", "Fərq yoxdur",
                            "Statement daha sürətlidir", "PreparedStatement yalnız SELECT üçündür"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "Connection Pool nə üçün istifadə olunur?",
                    List.of("Verilənlər bazası bağlantılarını təkrar istifadə edərək performansı artırmaq üçün", "Bağlantıları silmək üçün",
                            "Yalnız bir bağlantı yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "ORM (Object-Relational Mapping) nədir?",
                    List.of("Obyektləri verilənlər bazası cədvəlləri ilə uyğunlaşdıran texnika (məs. Hibernate)", "Yalnız SQL yazmaq üsulu",
                            "Test metodu", "Thread idarəetməsi"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "SQL injection həmləsindən qorunmaq üçün ən yaxşı üsul hansıdır?",
                    List.of("PreparedStatement/parametrləşdirilmiş sorğulardan istifadə etmək", "String birləşdirmə (concatenation) ilə sorğu qurmaq",
                            "Heç nə etməmək", "Yalnız Statement istifadə etmək"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "Transaction-un ACID xüsusiyyətləri nələrdir?",
                    List.of("Atomicity, Consistency, Isolation, Durability", "Access, Control, Isolation, Data",
                            "Atomic, Concurrent, Isolated, Distributed", "Heç biri"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "ResultSet nədir?",
                    List.of("SQL sorğusunun nəticəsini təmsil edən obyekt", "Verilənlər bazası bağlantısı",
                            "SQL sorğusunun özü", "Exception növü"), 0, Difficulty.EASY),
            new Question("JDBC və Verilənlər Bazası", "Hibernate-də lazy loading nə deməkdir?",
                    List.of("Əlaqəli data yalnız faktiki istifadə olunduqda yüklənir", "Bütün data əvvəlcədən yüklənir",
                            "Data heç vaxt yüklənmir", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "commit() və rollback() metodları nə üçündür?",
                    List.of("Tranzaksiyanı təsdiqləmək və ya geri qaytarmaq üçün", "Bağlantını bağlamaq üçün",
                            "Cədvəl yaratmaq üçün", "Sorğunu icra etmək üçün"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "N+1 select problemi nədir?",
                    List.of("Hər əlaqəli obyekt üçün ayrıca sorğu göndərilməsi nəticəsində yaranan performans problemi",
                            "Verilənlər bazasının silinməsi", "Tranzaksiya xətası", "Heç bir problem deyil"), 0, Difficulty.HARD),

            new Question("REST API və Veb Servislər", "REST nə deməkdir?",
                    List.of("Representational State Transfer — resurs əsaslı memarlıq stili", "Bir proqramlaşdırma dili",
                            "Verilənlər bazası növü", "Test framework-ü"), 0, Difficulty.EASY),
            new Question("REST API və Veb Servislər", "HTTP metodlarından GET və POST arasındakı əsas fərq nədir?",
                    List.of("GET məlumat almaq, POST yeni resurs yaratmaq/göndərmək üçündür", "Fərq yoxdur",
                            "GET həmişə data dəyişir", "POST yalnız oxumaq üçündür"), 0, Difficulty.EASY),
            new Question("REST API və Veb Servislər", "HTTP status kodu 404 nəyi bildirir?",
                    List.of("Resurs tapılmadı", "Server xətası", "Uğurlu əməliyyat", "İcazə yoxdur"), 0, Difficulty.EASY),
            new Question("REST API və Veb Servislər", "PUT və PATCH HTTP metodları arasındakı fərq nədir?",
                    List.of("PUT bütün resursu əvəz edir, PATCH qismən yeniləyir", "Fərq yoxdur",
                            "PATCH resursu silir", "PUT yalnız oxumaq üçündür"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "Idempotent HTTP metodu nə deməkdir?",
                    List.of("Eyni sorğu neçə dəfə göndərilsə də nəticə eyni olur", "Sorğu heç vaxt icra olunmur",
                            "Sorğu yalnız bir dəfə göndərilə bilər", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "JSON verilənlər formatının əsas üstünlüyü nədir?",
                    List.of("Yüngül, oxunaqlı və dillərarası dəstəklənən struktur", "Yalnız Java-da işləyir",
                            "Binary formatdır", "Heç bir üstünlüyü yoxdur"), 0, Difficulty.EASY),
            new Question("REST API və Veb Servislər", "@RequestBody annotasiyası (Spring) nə edir?",
                    List.of("HTTP sorğu gövdəsini Java obyektinə çevirir", "HTTP başlığını oxuyur",
                            "URL parametrini oxuyur", "Cavab kodu təyin edir"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "API versiyalaşdırması nə üçün vacibdir?",
                    List.of("Köhnə klientləri pozmadan API-ni inkişaf etdirmək üçün", "API-ni yavaşlatmaq üçün",
                            "Heç bir səbəbi yoxdur", "Yalnız sənədləşmə üçün"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "Statelessness REST memarlığında nəyi ifadə edir?",
                    List.of("Hər sorğunun serverdə əvvəlki sorğulardan asılı olmadan, özündə bütün lazımi məlumatla icra olunması",
                            "Server-in vəziyyəti heç vaxt dəyişməməsi", "Client-in vəziyyəti saxlamaması", "Heç bir mənası yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "CORS (Cross-Origin Resource Sharing) nə üçündür?",
                    List.of("Fərqli domenlərdən gələn sorğulara icazə vermək/idarə etmək üçün brauzer təhlükəsizlik mexanizmi",
                            "Verilənlər bazası əlaqəsi üçün", "Thread idarəetməsi üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),

            new Question("Concurrency Alətləri", "AtomicInteger sinifinin məqsədi nədir?",
                    List.of("Sinxronizasiya olmadan thread-safe atomik əməliyyatlar aparmaq", "İnteger-i sabit etmək",
                            "Yalnız oxumaq üçün istifadə olunur", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "CountDownLatch nə üçün istifadə olunur?",
                    List.of("Bir və ya bir neçə thread-in digər thread-lərin tamamlanmasını gözləməsi üçün", "Thread-i öldürmək üçün",
                            "Yaddaşı təmizləmək üçün", "Exception tutmaq üçün"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "Semaphore nə edir?",
                    List.of("Bir resursa eyni anda çıxış edə bilən thread sayını məhdudlaşdırır", "Thread yaradır",
                            "Yaddaşı artırır", "Exception atır"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "Future interfeysi nə üçün istifadə olunur?",
                    List.of("Asinxron hesablamanın nəticəsini gələcəkdə əldə etmək üçün", "Keçmiş nəticələri saxlamaq üçün",
                            "Thread-i dayandırmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "ReentrantLock, synchronized açar sözündən nə ilə fərqlənir?",
                    List.of("Daha çevikdir — tryLock, fairness və interrupt dəstəyi verir", "Fərq yoxdur",
                            "Daha yavaşdır həmişə", "synchronized-dan daha az təhlükəsizdir"), 0, Difficulty.HARD),
            new Question("Concurrency Alətləri", "CyclicBarrier və CountDownLatch arasındakı fərq nədir?",
                    List.of("CyclicBarrier təkrar istifadə oluna bilər, CountDownLatch bir dəfəlikdir", "Fərq yoxdur",
                            "CountDownLatch təkrar istifadə olunur", "CyclicBarrier yalnız bir thread üçündür"), 0, Difficulty.HARD),
            new Question("Concurrency Alətləri", "ThreadLocal nə üçün istifadə olunur?",
                    List.of("Hər thread üçün ayrıca dəyişən nüsxəsi saxlamaq üçün", "Bütün thread-lər arasında ortaq dəyişən üçün",
                            "Thread yaratmaq üçün", "Exception tutmaq üçün"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "Fork/Join Framework nə üçün nəzərdə tutulub?",
                    List.of("Böyük tapşırıqları kiçik hissələrə bölüb paralel icra etmək üçün", "Fayl oxumaq üçün",
                            "Verilənlər bazası üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Concurrency Alətləri", "BlockingQueue nə edir?",
                    List.of("Növbə boş və ya dolu olduqda thread-i bloklayır (producer-consumer modeli üçün)", "Elementləri sıralayır",
                            "Yalnız oxumaq üçündür", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "Race condition nə deməkdir?",
                    List.of("Bir neçə thread paylaşılan data-nı sinxronizasiya olmadan dəyişdirdikdə yaranan gözlənilməz nəticə",
                            "Thread-lərin sürət yarışı", "Proqramın sürətlə işləməsi", "Heç bir problem deyil"), 0, Difficulty.MEDIUM),

            new Question("Annotations və Reflection", "Java-da annotation nədir?",
                    List.of("Koda əlavə metadata təqdim edən element", "Yeni sinif növü", "Exception növü", "Thread növü"),
                    0, Difficulty.EASY),
            new Question("Annotations və Reflection", "@Override annotasiyası nə üçün istifadə olunur?",
                    List.of("Metodun valideyn sinifdəki metodu override etdiyini compiler-ə bildirmək üçün", "Metodu gizlətmək üçün",
                            "Metodu final etmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("Annotations və Reflection", "Reflection API nə üçün istifadə olunur?",
                    List.of("Runtime-da siniflərin, metodların və sahələrin strukturunu araşdırmaq və manipulyasiya etmək üçün",
                            "Kodu sürətləndirmək üçün", "Yaddaşı azaltmaq üçün", "Thread yaratmaq üçün"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "@FunctionalInterface annotasiyası nə edir?",
                    List.of("İnterfeysin yalnız bir abstract metoda malik olmasını compile zamanı təsdiqləyir", "İnterfeysi sinifə çevirir",
                            "Metodu final edir", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "Class.forName() metodu nə edir?",
                    List.of("Verilmiş adla sinifi runtime-da yükləyir", "Yeni sinif yaradır", "Sinifi silir", "Obyekti klonlayır"),
                    0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "Custom annotation necə yaradılır?",
                    List.of("@interface açar sözü ilə", "class açar sözü ilə", "interface açar sözü ilə", "enum açar sözü ilə"),
                    0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "Retention Policy (@Retention) annotasiyanın nəyini müəyyən edir?",
                    List.of("Annotasiyanın nə qədər müddət saxlanılacağını (SOURCE, CLASS, RUNTIME)", "Annotasiyanın rəngini",
                            "Annotasiyanın adını", "Heç nəyi"), 0, Difficulty.HARD),
            new Question("Annotations və Reflection", "Reflection-un mənfi tərəfi nədir?",
                    List.of("Performans itkisi və compile-time tip təhlükəsizliyinin olmaması", "Heç bir mənfi tərəfi yoxdur",
                            "Yalnız test üçün yararsızdır", "Yaddaşı artırır"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "getDeclaredFields() metodu nə qaytarır?",
                    List.of("Sinifin bütün elan olunmuş sahələrini (private daxil olmaqla)", "Yalnız public sahələri",
                            "Yalnız metodları", "Heç nə"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "Annotation processor nə üçün istifadə olunur?",
                    List.of("Compile zamanı annotasiyalara əsasən kod generasiya etmək və ya yoxlama aparmaq üçün",
                            "Runtime-da annotasiyanı silmək üçün", "Annotasiyanı şifrələmək üçün", "Heç bir məqsədi yoxdur"),
                    0, Difficulty.HARD),

            new Question("I/O və Serialization", "Serialization nədir?",
                    List.of("Obyekti bayt ardıcıllığına çevirmək (saxlamaq və ya ötürmək üçün)", "Obyekti silmək",
                            "Obyekti klonlamaq", "Obyekti sıralamaq"), 0, Difficulty.EASY),
            new Question("I/O və Serialization", "Serializable interfeysi nə üçün implement edilir?",
                    List.of("Sinifin obyektlərinin serializasiya oluna bilməsini təmin etmək üçün", "Sinifi final etmək üçün",
                            "Metodları gizlətmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("I/O və Serialization", "transient açar sözü nə edir?",
                    List.of("Sahənin serializasiya zamanı nəzərə alınmamasını təmin edir", "Sahəni final edir",
                            "Sahəni statik edir", "Heç nə etmir"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "BufferedReader niyə adi FileReader-dən daha sürətlidir?",
                    List.of("Daxili buferləşdirmə ilə oxuma əməliyyatlarının sayını azaldır", "Fərq yoxdur",
                            "Daha az yaddaş istifadə edir", "Yalnız binary fayllar üçündür"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "try-with-resources I/O əməliyyatlarında niyə vacibdir?",
                    List.of("Stream/resource-ların avtomatik və düzgün bağlanmasını təmin edir", "Faylı sürətli oxuyur",
                            "Yaddaşı artırır", "Heç bir əhəmiyyəti yoxdur"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "InputStream və Reader arasındakı fərq nədir?",
                    List.of("InputStream bayt, Reader isə simvol (character) əsaslı oxuma aparır", "Fərq yoxdur",
                            "Reader yalnız fayl üçündür", "InputStream yalnız şəbəkə üçündür"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "serialVersionUID nə üçün istifadə olunur?",
                    List.of("Serializasiya olunmuş sinifin versiyasını idarə etmək üçün, deserialization zamanı uyğunluğu yoxlamaq üçün",
                            "Obyektin ID-si üçün", "Thread ID-si üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("I/O və Serialization", "java.nio.file.Files sinifi nə üçün istifadə olunur?",
                    List.of("Fayl əməliyyatlarını (oxuma, yazma, kopyalama) müasir və rahat şəkildə aparmaq üçün", "Şəbəkə əməliyyatları üçün",
                            "Thread yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "Deserialization zamanı təhlükəsizlik riski nə ola bilər?",
                    List.of("Zərərli serialized data icra olunan koda çevrilə bilər (insecure deserialization)", "Heç bir risk yoxdur",
                            "Yalnız performans azalır", "Fayl böyüyür"), 0, Difficulty.HARD),
            new Question("I/O və Serialization", "System.out.println() daxili olaraq hansı axını istifadə edir?",
                    List.of("Standart çıxış axınını (stdout, PrintStream)", "Standart giriş axınını",
                            "Şəbəkə axınını", "Fayl axınını"), 0, Difficulty.EASY),

            new Question("Maven və Gradle", "Maven-in əsas məqsədi nədir?",
                    List.of("Layihənin build, asılılıq idarəetməsi və layihə strukturunu standartlaşdırmaq", "Yalnız kodu compile etmək",
                            "Test yazmaq", "UI yaratmaq"), 0, Difficulty.EASY),
            new Question("Maven və Gradle", "pom.xml faylı nəyi təsvir edir?",
                    List.of("Maven layihəsinin konfiqurasiyasını və asılılıqlarını", "Java kodunu",
                            "Test nəticələrini", "Heç nəyi"), 0, Difficulty.EASY),
            new Question("Maven və Gradle", "Maven-də 'dependency' nə deməkdir?",
                    List.of("Layihənin ehtiyac duyduğu xarici kitabxana", "Test sinifi", "Compile xətası", "Heç bir mənası yoxdur"),
                    0, Difficulty.EASY),
            new Question("Maven və Gradle", "Gradle, Maven-dən nə ilə fərqlənir?",
                    List.of("XML əvəzinə Groovy/Kotlin DSL istifadə edir və adətən daha sürətlidir", "Fərq yoxdur",
                            "Gradle yalnız Android üçündür", "Maven daha sürətlidir"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Maven-in 'build lifecycle' mərhələlərindən biri deyil hansıdır?",
                    List.of("compile", "test", "package", "refactor"), 3, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Semantic Versioning-də (MAJOR.MINOR.PATCH) MAJOR versiyasının artması nəyi bildirir?",
                    List.of("Geriyə uyğun olmayan (breaking) dəyişikliklər", "Kiçik bug fix", "Sənədləşmə dəyişikliyi", "Heç nəyi"),
                    0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Maven repository (local, central, remote) nə üçündür?",
                    List.of("Asılılıqların saxlandığı və axtarıldığı yer", "Kodun versiyalaşdırıldığı yer",
                            "Test nəticələrinin saxlandığı yer", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "'mvn clean install' əmri nə edir?",
                    List.of("Əvvəlki build nəticələrini silir, yenidən compile/test edir və artefaktı local repository-ə quraşdırır",
                            "Yalnız kodu silir", "Yalnız test edir", "Heç nə etmir"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Gradle-də build.gradle faylının rolu nədir?",
                    List.of("Layihənin build konfiqurasiyasını təyin etmək (pom.xml-in Gradle qarşılığı)", "Test nəticələrini saxlamaq",
                            "Kodu compile etmək", "Heç bir rolu yoxdur"), 0, Difficulty.EASY),
            new Question("Maven və Gradle", "Transitive dependency nə deməkdir?",
                    List.of("Birbaşa əlavə etdiyiniz asılılığın öz asılılıqlarının da avtomatik daxil edilməsi", "Yalnız birbaşa asılılıqlar",
                            "Test asılılıqları", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),

            new Question("Kod Keyfiyyəti və Clean Code", "Code smell nə deməkdir?",
                    List.of("Kodda potensial problemi göstərən əlamət (mütləq bug olmasa da)", "Kompilyasiya xətası",
                            "Runtime exception", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "DRY prinsipi nəyi ifadə edir?",
                    List.of("Don't Repeat Yourself — kod təkrarından qaçmaq", "Kodu qısa yazmaq",
                            "Yalnız şərhlərdən istifadə etmək", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Kod Keyfiyyəti və Clean Code", "Code review-un əsas məqsədi nədir?",
                    List.of("Kodun keyfiyyətini, düzgünlüyünü yoxlamaq və bilik paylaşımını təmin etmək", "Yalnız bugları tapmaq",
                            "Yalnız performansı ölçmək", "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("Kod Keyfiyyəti və Clean Code", "Refactoring nə deməkdir?",
                    List.of("Xarici davranışı dəyişmədən kodun daxili strukturunu yaxşılaşdırmaq", "Yeni funksionallıq əlavə etmək",
                            "Bugları düzəltmək", "Testləri silmək"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Cyclomatic complexity nəyi ölçür?",
                    List.of("Kodun məntiqi mürəkkəbliyini (şərti budaqların sayı əsasında)", "Kodun sətir sayını",
                            "Fayl sayını", "Test sayını"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "YAGNI prinsipi nə deməkdir?",
                    List.of("You Aren't Gonna Need It — indi lazım olmayan funksionallığı əlavə etməmək",
                            "Həmişə hər şeyi qabaqcadan planlaşdırmaq", "Kod təkrarı", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Static code analysis alətləri (məs. SonarQube) nə üçün istifadə olunur?",
                    List.of("Kodu icra etmədən potensial problemləri (bug, code smell, təhlükəsizlik) aşkar etmək üçün",
                            "Yalnız kodu compile etmək üçün", "Testləri işə salmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Magic number nə deməkdir?",
                    List.of("Kodda izahsız, sabit dəyər kimi yazılmış rəqəm", "Random ədəd", "Böyük ədəd", "Heç bir mənası yoxdur"),
                    0, Difficulty.EASY),
            new Question("Kod Keyfiyyəti və Clean Code", "Technical debt nəyi ifadə edir?",
                    List.of("Sürətli həll üçün edilən güzəştlərin gələcəkdə əlavə iş tələb etməsi", "Maliyyə borcu",
                            "Layihənin büdcəsi", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Pair programming-in üstünlüyü nədir?",
                    List.of("Bilik paylaşımı və real-time kod review vasitəsilə keyfiyyətin artması", "Yalnız sürəti artırmaq",
                            "Heç bir üstünlüyü yoxdur", "Yalnız yeni işçilər üçündür"), 0, Difficulty.EASY)
    );

    public static List<Question> getQuestions() {
        return QUESTIONS;
    }
}
