package repository;

import model.Difficulty;
import model.Question;

import java.util.List;

public class QuestionBank {

    private static final List<Question> QUESTIONS = List.of(
            new Question("OOP", "Java-da hansı açar söz bir sinifin başqa sinifdən miras almasını təmin edir?",
                    List.of("implements", "extends", "inherits", "super"), 1, Difficulty.EASY),
            new Question("OOP", "Aşağıdakılardan hansı Java-da çoxvarislik (multiple inheritance) əldə etmək üçün istifadə olunur?",
                    List.of("Abstract class", "Interface", "Final class", "Static class"), 1, Difficulty.MEDIUM),
            new Question("OOP", "Encapsulation (inkapsulyasiya) nəyi ifadə edir?",
                    List.of("Kod təkrarının aradan qaldırılması", "Data və metodların bir sinif daxilində gizlədilməsi",
                            "Sinifin genişləndirilməsi", "Metodun overload edilməsi"), 1, Difficulty.EASY),
            new Question("OOP", "Java-da 'this' açar sözü nə üçün istifadə olunur?",
                    List.of("Statik dəyişənə müraciət üçün", "Cari obyektə istinad üçün",
                            "Valideyn sinifə müraciət üçün", "Yeni obyekt yaratmaq üçün"), 1, Difficulty.EASY),
            new Question("OOP", "Polymorphism (çoxformalılıq) Java-da necə əldə edilir?",
                    List.of("Yalnız inheritance ilə", "Method overloading və overriding ilə",
                            "Yalnız interface ilə", "Statik metodlarla"), 1, Difficulty.MEDIUM),
            new Question("OOP", "Abstract class ilə interface arasındakı əsas fərq nədir (Java 8-ə qədər)?",
                    List.of("Abstract class-da constructor ola bilməz",
                            "Interface-də yalnız abstract metodlar ola bilərdi, abstract class-da isə implementasiya edilmiş metodlar da ola bilər",
                            "Fərq yoxdur", "Interface-dən birbaşa obyekt yaratmaq olar"), 1, Difficulty.MEDIUM),

            new Question("Kolleksiyalar", "ArrayList və LinkedList arasındakı əsas fərq nədir?",
                    List.of("ArrayList sıralanmır", "ArrayList array əsaslıdır, LinkedList node əsaslıdır",
                            "LinkedList thread-safe-dir", "Fərq yoxdur"), 1, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "HashMap-də açarların unikallığı necə təmin olunur?",
                    List.of("equals() və hashCode() metodları ilə", "compareTo() metodu ilə",
                            "toString() metodu ilə", "clone() metodu ilə"), 0, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "Hansı kolleksiya interfeysi dublikat elementlərə icazə vermir?",
                    List.of("List", "Set", "Queue", "Map (values)"), 1, Difficulty.EASY),
            new Question("Kolleksiyalar", "TreeMap elementləri necə saxlayır?",
                    List.of("Təsadüfi ardıcıllıqla", "Açarların təbii sıralaması ilə",
                            "Əlavə olunma ardıcıllığı ilə", "Heç bir sıralama olmadan"), 1, Difficulty.HARD),
            new Question("Kolleksiyalar", "Iterator və ListIterator arasındakı fərq nədir?",
                    List.of("ListIterator yalnız irəli hərəkət edir", "ListIterator həm irəli, həm geri hərəkət edə bilər",
                            "Iterator List üçün işləmir", "Fərq yoxdur"), 1, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "ConcurrentModificationException nə vaxt yaranır?",
                    List.of("Kolleksiya iterasiya zamanı birbaşa dəyişdirildikdə", "Kolleksiya boş olduqda",
                            "Kolleksiya sıralandıqda", "Heç vaxt"), 0, Difficulty.HARD),

            new Question("İstisnalar", "Checked və unchecked exception arasındakı fərq nədir?",
                    List.of("Checked exception-lar compile zamanı yoxlanılır", "Unchecked exception-lar compile zamanı yoxlanılır",
                            "Fərq yoxdur", "Checked exception-lar yalnız runtime-da olur"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "finally bloku nə vaxt icra olunur?",
                    List.of("Yalnız exception atılarsa", "Yalnız exception atılmazsa",
                            "Həmişə, exception olub-olmamasından asılı olmayaraq", "Heç vaxt"), 2, Difficulty.EASY),
            new Question("İstisnalar", "Öz custom exception sinifinizi yaratmaq üçün hansı sinifi extend etməlisiniz?",
                    List.of("Throwable və ya Exception", "Object", "RuntimeError", "Error only"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "try-with-resources nə üçün istifadə olunur?",
                    List.of("Exception-ları tutmaq üçün", "Resursların avtomatik bağlanması üçün",
                            "Yeni thread yaratmaq üçün", "Statik dəyişən elan etmək üçün"), 1, Difficulty.MEDIUM),
            new Question("İstisnalar", "throw və throws açar sözləri arasındakı fərq nədir?",
                    List.of("throw exception atmaq üçün, throws metodun imzasında istisna elan etmək üçün istifadə olunur",
                            "Fərq yoxdur", "throws yalnız runtime exception üçündür", "throw metodun imzasında istifadə olunur"),
                    0, Difficulty.MEDIUM),
            new Question("İstisnalar", "NullPointerException hansı halda yaranır?",
                    List.of("Massiv indeksi hüdüddan kənara çıxdıqda", "null referensiya üzərində metod çağırıldıqda",
                            "Fayl tapılmadıqda", "Rəqəm formatı səhv olduqda"), 1, Difficulty.EASY),

            new Question("Multithreading", "Java-da yeni thread yaratmağın neçə əsas yolu var?",
                    List.of("1", "2 (Thread sinifi və Runnable interfeysi)", "3", "4"), 1, Difficulty.EASY),
            new Question("Multithreading", "'synchronized' açar sözü nə üçün istifadə olunur?",
                    List.of("Kodu sürətləndirmək üçün", "Bir vaxtda yalnız bir thread-in bloka girməsini təmin etmək üçün",
                            "Yeni thread yaratmaq üçün", "Thread-i dayandırmaq üçün"), 1, Difficulty.MEDIUM),
            new Question("Multithreading", "Thread.sleep() metodu nə edir?",
                    List.of("Thread-i həmişəlik dayandırır", "Thread-i müəyyən müddətə pauza edir",
                            "Thread-i öldürür", "Yeni thread yaradır"), 1, Difficulty.EASY),
            new Question("Multithreading", "Deadlock nə deməkdir?",
                    List.of("Thread-lərin bir-birini gözləyərək sonsuz bloklanması", "Thread-in normal bitməsi",
                            "Thread-in sürətlə işləməsi", "Bir thread-in digərini yaratması"), 0, Difficulty.HARD),
            new Question("Multithreading", "wait() və sleep() metodları arasındakı fərq nədir?",
                    List.of("wait() monitoru buraxır, sleep() buraxmır", "Fərq yoxdur",
                            "sleep() monitoru buraxır", "wait() yalnız static metoddur"), 0, Difficulty.HARD),
            new Question("Multithreading", "ExecutorService nə üçün istifadə olunur?",
                    List.of("Thread-lərin pool şəklində idarə edilməsi üçün", "Yaddaşı təmizləmək üçün",
                            "Fayl oxumaq üçün", "Exception tutmaq üçün"), 0, Difficulty.MEDIUM),

            new Question("JVM və Yaddaş", "Garbage Collector-un vəzifəsi nədir?",
                    List.of("Kodu compile etmək", "İstifadə olunmayan obyektləri yaddaşdan silmək",
                            "Thread-ləri idarə etmək", "Faylları oxumaq"), 1, Difficulty.EASY),
            new Question("JVM və Yaddaş", "Java-da 'Heap' yaddaşı nə üçün istifadə olunur?",
                    List.of("Statik dəyişənlər üçün", "Obyektlərin saxlanması üçün",
                            "Metod çağırışları üçün", "Yalnız primitivlər üçün"), 1, Difficulty.MEDIUM),
            new Question("JVM və Yaddaş", "JVM, JRE və JDK arasındakı fərq nədir?",
                    List.of("Eynidir", "JDK development üçün, JRE işə salma üçün, JVM bytecode icrası üçündür",
                            "JVM yalnız compile edir", "JRE yalnız development üçündür"), 1, Difficulty.MEDIUM),
            new Question("JVM və Yaddaş", "'static' açar sözü ilə elan olunan dəyişən nəyə aiddir?",
                    List.of("Yalnız bir obyektə", "Sinifin özünə, bütün obyektlər üçün ortaqdır",
                            "Yalnız local metoda", "Heç nəyə"), 1, Difficulty.EASY),
            new Question("JVM və Yaddaş", "Stack yaddaşında nə saxlanılır?",
                    List.of("Obyektlər", "Metod çağırışları və lokal dəyişənlər",
                            "Statik dəyişənlər", "Class faylları"), 1, Difficulty.EASY),
            new Question("JVM və Yaddaş", "'final' açar sözü dəyişənə tətbiq edildikdə nə deməkdir?",
                    List.of("Dəyişənin dəyəri bir dəfə təyin edildikdən sonra dəyişdirilə bilməz",
                            "Dəyişən yalnız static olur", "Dəyişən yalnız private olur", "Heç nə demək deyil"),
                    0, Difficulty.EASY),

            new Question("String", "Java-da String niyə immutable-dır?",
                    List.of("Performans üçün lazım deyil", "Təhlükəsizlik, thread-safety və String Pool-un səmərəli işləməsi üçün",
                            "Compiler tələb edir", "Heç bir səbəb yoxdur"), 1, Difficulty.MEDIUM),
            new Question("String", "String, StringBuilder və StringBuffer arasındakı fərq nədir?",
                    List.of("String mutable, StringBuilder immutable-dır",
                            "StringBuilder thread-safe deyil, StringBuffer thread-safe-dir, String isə immutable-dır",
                            "Fərq yoxdur", "StringBuffer immutable-dır"), 1, Difficulty.MEDIUM),
            new Question("String", "'==' operatoru ilə .equals() metodu String-lər üçün nəyə görə fərqlənir?",
                    List.of("'==' referensiyanı, equals() məzmunu müqayisə edir", "Fərq yoxdur",
                            "equals() referensiyanı müqayisə edir", "'==' həmişə true qaytarır"), 0, Difficulty.EASY),
            new Question("String", "String Pool nədir?",
                    List.of("Bütün obyektlərin saxlandığı yaddaş",
                            "JVM-in string literal-ları təkrar istifadə üçün saxladığı xüsusi yaddaş sahəsi",
                            "Fayl sistemi", "Thread pool-un digər adı"), 1, Difficulty.MEDIUM),
            new Question("String", "intern() metodu nə edir?",
                    List.of("String-i massivə çevirir", "String-i String Pool-a əlavə edir və ya oradan qaytarır",
                            "String-i böyük hərflərə çevirir", "String-i silir"), 1, Difficulty.HARD),
            new Question("String", "String.format() metodunun məqsədi nədir?",
                    List.of("String-i parçalamaq", "Şablon əsasında formatlanmış string yaratmaq",
                            "String-i şifrələmək", "String-i müqayisə etmək"), 1, Difficulty.EASY),

            new Question("Generics", "Generics-in əsas məqsədi nədir?",
                    List.of("Kodun icra sürətini artırmaq", "Compile-time tip təhlükəsizliyi təmin etmək",
                            "Yaddaşı azaltmaq", "Multithreading dəstəkləmək"), 1, Difficulty.MEDIUM),
            new Question("Generics", "'List<?>' ifadəsi nəyi bildirir?",
                    List.of("İstənilən tipdə element saxlaya bilən wildcard List", "Yalnız Integer List",
                            "Boş List", "Sabit tipli List"), 0, Difficulty.MEDIUM),
            new Question("Generics", "'<T extends Number>' bildirişi nəyi ifadə edir?",
                    List.of("T tipi Number sinifini extend edən tip olmalıdır", "T yalnız String ola bilər",
                            "Heç bir məhdudiyyət yoxdur", "T mütləq abstrakt olmalıdır"), 0, Difficulty.HARD),
            new Question("Generics", "Type erasure nədir?",
                    List.of("Compile zamanı generic tip məlumatının silinməsi (runtime-da olmaması)",
                            "Runtime-da tip yaradılması", "Generic siniflərin silinməsi", "Heç bir əlaqəsi yoxdur"),
                    0, Difficulty.HARD),
            new Question("Generics", "Generic metod necə elan olunur?",
                    List.of("Metod adından əvvəl tip parametri ilə, məs. <T> T method()", "Yalnız sinif səviyyəsində",
                            "Generic metod mümkün deyil", "Return tipindən sonra"), 0, Difficulty.MEDIUM),
            new Question("Generics", "Raw type (məs. List list = new ArrayList()) istifadəsi nə üçün tövsiyə olunmur?",
                    List.of("Compile-time tip yoxlamasını itirir", "Daha sürətli işləyir",
                            "Daha az yaddaş tutur", "Heç bir problem yoxdur"), 0, Difficulty.MEDIUM),

            new Question("Stream və Lambda", "Lambda ifadəsi nədir?",
                    List.of("Anonim funksiyanın qısa yazılış forması", "Yeni sinif tipi",
                            "Statik metod", "Exception növü"), 0, Difficulty.EASY),
            new Question("Stream və Lambda", "Stream API-də 'map()' metodu nə edir?",
                    List.of("Elementləri filtr edir", "Hər elementi başqa formaya çevirir",
                            "Elementləri sıralayır", "Stream-i bağlayır"), 1, Difficulty.EASY),
            new Question("Stream və Lambda", "'filter()' və 'map()' arasındakı fərq nədir?",
                    List.of("filter() şərtə uyğun elementləri seçir, map() elementləri çevirir", "Fərq yoxdur",
                            "map() elementləri seçir", "filter() elementləri çevirir"), 0, Difficulty.EASY),
            new Question("Stream və Lambda", "Stream-lər neçə dəfə istifadə oluna bilər?",
                    List.of("Sonsuz sayda", "Yalnız bir dəfə (terminal əməliyyatdan sonra bağlanır)",
                            "İki dəfə", "Yalnız paralel rejimdə"), 1, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "'reduce()' metodunun məqsədi nədir?",
                    List.of("Stream elementlərini bir nəticəyə birləşdirmək", "Stream-i sıralamaq",
                            "Stream-i filtr etmək", "Yeni stream yaratmaq"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Functional interface nədir?",
                    List.of("Yalnız bir abstract metodu olan interfeys", "Bir neçə metodu olan sinif",
                            "Statik siniflər üçün istifadə olunan interfeys", "Generic interfeys"), 0, Difficulty.MEDIUM),

            new Question("SOLID Prinsipləri", "Single Responsibility Principle (SRP) nəyi ifadə edir?",
                    List.of("Bir sinifin yalnız bir dəyişmə səbəbi olmalıdır", "Sinif çoxlu interfeys implementasiya etməlidir",
                            "Bir sinif yalnız bir metoda malik olmalıdır", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Open/Closed Principle nə deməkdir?",
                    List.of("Siniflər genişlənməyə açıq, dəyişikliyə qapalı olmalıdır", "Bütün siniflər final olmalıdır",
                            "Siniflər həmişə açıq (public) olmalıdır", "Heç bir əlaqəsi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Liskov Substitution Principle nəyi tələb edir?",
                    List.of("Alt sinif öz valideyn sinifinin yerinə istifadə oluna bilməlidir, davranışı pozmadan",
                            "Alt sinif valideyndən fərqli davranmalıdır", "İnterfeyslər əvəz oluna bilməz", "Heç bir mənası yoxdur"),
                    0, Difficulty.HARD),
            new Question("SOLID Prinsipləri", "Interface Segregation Principle nəyi tövsiyə edir?",
                    List.of("Böyük, hər şeyi əhatə edən interfeyslər yaratmaq",
                            "Klientlərin istifadə etmədiyi metodlara asılı olmamaq üçün kiçik, spesifik interfeyslər yaratmaq",
                            "Yalnız bir interfeys istifadə etmək", "İnterfeysləri ümumiyyətlə istifadə etməmək"), 1, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Dependency Inversion Principle nəyi ifadə edir?",
                    List.of("Yüksək səviyyəli modullar aşağı səviyyəli modullardan deyil, abstraksiyalardan asılı olmalıdır",
                            "Bütün siniflər bir-birindən asılı olmalıdır", "Asılılıqlar həmişə konkret siniflər olmalıdır",
                            "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("SOLID Prinsipləri", "SOLID prinsiplərinin əsas məqsədi nədir?",
                    List.of("Kodu daha çətin oxunan etmək", "Daha çevik, davamlı (maintainable) və genişlənə bilən kod yazmaq",
                            "Kodun sətir sayını artırmaq", "Yalnız performansı artırmaq"), 1, Difficulty.EASY)
    );

    public static List<Question> getQuestions() {
        return QUESTIONS;
    }
}
