package repository.bank;

import model.Difficulty;
import model.Question;

import java.util.List;

public class ArchitectureSecurityQuestions {

    private static final List<Question> QUESTIONS = List.of(
            new Question("Sistem Dizaynı Əsasları", "Scalability (miqyaslanma) sistemin nəyini ifadə edir?",
                    List.of("Artan yükü idarə etmək üçün sistemin genişlənə bilmə qabiliyyətini", "Sistemin sürətini",
                            "Sistemin ölçüsünü", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Sistem Dizaynı Əsasları", "Vertical scaling (şaquli miqyaslanma) və horizontal scaling (üfüqi miqyaslanma) arasındakı fərq nədir?",
                    List.of("Vertical mövcud serveri gücləndirir, horizontal əlavə server qoşur", "Fərq yoxdur",
                            "Horizontal serveri gücləndirir", "Vertical əlavə server qoşur"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Load balancer (yük balanslayıcı) nə üçün istifadə olunur?",
                    List.of("Gələn trafiki bir neçə server arasında bölüşdürmək üçün", "Data saxlamaq üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün"), 0, Difficulty.EASY),
            new Question("Sistem Dizaynı Əsasları", "Sistem dizaynında single point of failure (tək uğursuzluq nöqtəsi) nə üçün riskli sayılır?",
                    List.of("O komponent iflic olduqda bütün sistem dayana bilər", "Heç bir riski yoxdur", "Sistemi sürətləndirir",
                            "Yalnız test mühitində risklidir"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "CAP teoremi sistem dizaynında hansı seçimi vurğulayır?",
                    List.of("Consistency, Availability və Partition tolerance arasında trade-off", "Yalnız performans seçimi",
                            "Heç bir seçim yoxdur", "Yalnız təhlükəsizlik seçimi"), 0, Difficulty.HARD),
            new Question("Sistem Dizaynı Əsasları", "Fault tolerance (xətaya dözümlülük) nə deməkdir?",
                    List.of("Sistemin komponent xətalarına baxmayaraq işləməyə davam etmə qabiliyyəti", "Sistemin heç vaxt xəta verməməsi",
                            "Heç bir mənası yoxdur", "Yalnız test mühitinə aiddir"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Sistem dizaynında throughput və latency arasındakı əlaqə necədir?",
                    List.of("Onlar həmişə eyni istiqamətdə dəyişmir, sistem hər ikisini balanslaşdırmalıdır", "Həmişə eynidir",
                            "Heç bir əlaqəsi yoxdur", "Throughput həmişə latency-ni azaldır"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Content Delivery Network (CDN) sistem dizaynında nəyə kömək edir?",
                    List.of("Statik məzmunu istifadəçiyə coğrafi baxımdan yaxın yerdən çatdıraraq latency-ni azaltmağa",
                            "Verilənlər bazasını əvəz etməyə", "Heç bir köməyi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Sistem dizaynında 'back-of-envelope estimation' nə üçün aparılır?",
                    List.of("Sistemin təxmini tutumunu (storage, trafik) erkən qiymətləndirmək üçün", "Kodu yazmaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Consistent Hashing paylanmış sistemlərdə nə üçün istifadə olunur?",
                    List.of("Node əlavə/silindikdə minimal yenidən bölüşdürmə ilə data-nı node-lar arasında bölmək üçün", "Data-nı şifrələmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.HARD),
            new Question("Sistem Dizaynı Əsasları", "Sistem dizaynında 'bottleneck' (darboğaz) nəyi ifadə edir?",
                    List.of("Sistemin ümumi performansını məhdudlaşdıran ən zəif komponenti", "Sistemin ən sürətli hissəsini",
                            "Heç bir mənası yoxdur", "Yalnız verilənlər bazasına aiddir"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Sistem dizaynında capacity planning nə üçün vacibdir?",
                    List.of("Gələcək yükü qabaqcadan proqnozlaşdırıb lazımi resursları planlaşdırmaq üçün", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız kiçik sistemlər üçündür", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Reverse proxy nə üçün istifadə olunur?",
                    List.of("Klient sorğularını backend serverlərə yönləndirmək və əlavə funksiyalar (keşləmə, SSL) təmin etmək üçün",
                            "Yalnız verilənlər bazası üçün", "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Data partitioning (sharding) sistem dizaynında nə üçün istifadə olunur?",
                    List.of("Böyük data həcmini idarə oluna bilən hissələrə bölüb paylamaq üçün", "Data-nı silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız backup üçün"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Sistem dizaynında idempotency niyə vacibdir (məs. ödəniş sistemlərində)?",
                    List.of("Şəbəkə problemi səbəbindən təkrarlanan sorğuların yanlışlıqla əməliyyatı iki dəfə icra etməsinin qarşısını alır",
                            "Heç bir əhəmiyyəti yoxdur", "Yalnız test üçündür", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Sistem dizaynında 'graceful degradation' nə deməkdir?",
                    List.of("Sistem hissəvi xəta zamanı tam çökmək əvəzinə funksionallığı azaldaraq işləməyə davam etməsi", "Sistemin tam dayanması",
                            "Heç bir mənası yoxdur", "Yalnız test mühitinə aiddir"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Sistem dizaynı müsahibələrində 'trade-off' anlayışı niyə vacibdir?",
                    List.of("Real dünya sistemlərində hər həll yolunun öz üstünlük/mənfi cəhətləri olur, mükəmməl həll nadirdir",
                            "Heç bir əhəmiyyəti yoxdur", "Yalnız nəzəri sistemlərə aiddir", "Trade-off həmişə eynidir"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Sistem dizaynında 'SLA' (Service Level Agreement) nəyi ifadə edir?",
                    List.of("Xidmətin gözlənilən əlçatanlıq/performans səviyyəsini müəyyən edən razılaşma", "Kod keyfiyyəti standartı",
                            "Heç bir mənası yoxdur", "Yalnız test protokolu"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Rate limiting sistem dizaynında hansı problemin qarşısını almağa kömək edir?",
                    List.of("Sistemin həddindən artıq sorğu ilə yüklənməsinin (overload)", "Data itkisinin", "Heç bir problemin",
                            "Yalnız test problemlərinin"), 0, Difficulty.MEDIUM),
            new Question("Sistem Dizaynı Əsasları", "Sistem dizaynında 'read-heavy' və 'write-heavy' sistemlər üçün fərqli strategiyalar niyə tələb olunur?",
                    List.of("Hər ssenari fərqli optimallaşdırma (keşləmə, replikasiya vs. partitioning) tələb edir", "Heç bir fərqi yoxdur",
                            "Hər zaman eyni strategiya işləyir", "Yalnız kiçik sistemlərə aiddir"), 0, Difficulty.MEDIUM),

            new Question("Mikroservislər Memarlığı", "Mikroservis memarlığı nə deməkdir?",
                    List.of("Tətbiqi kiçik, müstəqil deploy oluna bilən servislərə bölmək", "Bütün kodu tək tətbiqdə saxlamaq",
                            "Heç bir mənası yoxdur", "Yalnız UI dizaynı üsulu"), 0, Difficulty.EASY),
            new Question("Mikroservislər Memarlığı", "Monolit memarlıq ilə mikroservis memarlığı arasındakı əsas fərq nədir?",
                    List.of("Monolit tək deploy vahidi, mikroservis çoxlu müstəqil deploy vahididir", "Fərq yoxdur",
                            "Mikroservis həmişə daha sadədir", "Monolit həmişə daha yavaşdır"), 0, Difficulty.EASY),
            new Question("Mikroservislər Memarlığı", "Mikroservislərin əsas üstünlüyü nədir?",
                    List.of("Müstəqil deployment, texnologiya seçimi çevikliyi və izolyasiya edilmiş miqyaslanma", "Həmişə daha az mürəkkəblik",
                            "Heç bir üstünlüyü yoxdur", "Yalnız kiçik komandalar üçündür"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Mikroservislərin əsas çətinliyi/dezavantajı nədir?",
                    List.of("Paylanmış sistem mürəkkəbliyi (network latency, data consistency, monitorinq)", "Heç bir dezavantajı yoxdur",
                            "Yalnız kiçik layihələrdə çətinlik yaradır", "Performans həmişə pisdir"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Servislər arasında kommunikasiya üçün ümumi üsullardan biri hansıdır?",
                    List.of("Sinxron REST/gRPC çağırışları və ya asinxron mesajlaşma", "Yalnız paylaşılan verilənlər bazası", "Heç bir üsul yoxdur",
                            "Yalnız fayl paylaşımı"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Mikroservis memarlığında 'database per service' prinsipi nə deməkdir?",
                    List.of("Hər servisin öz ayrıca verilənlər bazasının olması, sıx bağlılığın qarşısını almaq üçün",
                            "Bütün servislərin eyni verilənlər bazasını paylaşması", "Heç bir mənası yoxdur", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Service Discovery mikroservis memarlığında nə üçün lazımdır?",
                    List.of("Servislərin bir-birini dinamik olaraq (IP/port dəyişsə belə) tapa bilməsi üçün", "Servisləri silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Circuit Breaker pattern mikroservislərdə nə üçün istifadə olunur?",
                    List.of("Uğursuz servisə davamlı sorğu göndərməkdən çəkinərək kaskad xətaların qarşısını almaq üçün", "Servisi silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.HARD),
            new Question("Mikroservislər Memarlığı", "Distributed tracing mikroservislərdə nə üçün istifadə olunur?",
                    List.of("Bir sorğunun çoxlu servis üzərindən keçdiyi yolu izləyib performans/xəta analiz etmək üçün", "Servisi yaratmaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız UI üçün"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Saga pattern mikroservislərdə nə üçün istifadə olunur?",
                    List.of("Paylanmış tranzaksiyaları bir sıra lokal tranzaksiya və kompensasiya addımları ilə idarə etmək üçün",
                            "Servisi silmək üçün", "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.HARD),
            new Question("Mikroservislər Memarlığı", "Strangler Fig pattern nə üçün istifadə olunur?",
                    List.of("Monolit sistemi tədricən mikroservislərə köçürmək üçün", "Yeni sistem yaratmaq üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün"), 0, Difficulty.HARD),
            new Question("Mikroservislər Memarlığı", "Mikroservislərdə 'bounded context' (Domain-Driven Design-dan) nəyi ifadə edir?",
                    List.of("Hər servisin öz aydın domen sərhədi və modelinə malik olmasını", "Bütün servislərin eyni modeli paylaşmasını",
                            "Heç bir mənası yoxdur", "Yalnız UI-a aiddir"), 0, Difficulty.HARD),
            new Question("Mikroservislər Memarlığı", "Mikroservislərdə API Gateway-in rolu nədir?",
                    List.of("Klient sorğularını mərkəzləşdirilmiş nöqtədən müvafiq servislərə yönləndirmək", "Verilənlər bazası olmaq",
                            "Heç bir rolu yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Mikroservislərdə konfiqurasiyaların mərkəzləşdirilməsi (Config Server) nə üçün faydalıdır?",
                    List.of("Bütün servislərin konfiqurasiyasını mərkəzi yerdən idarə etməyə imkan verir", "Heç bir faydası yoxdur",
                            "Yalnız test üçündür", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Mikroservislər arasında data consistency-ni təmin etmək niyə çətindir?",
                    List.of("Paylanmış tranzaksiyalar mürəkkəbdir, ənənəvi ACID tranzaksiyalar servislərarası tətbiq oluna bilmir",
                            "Heç bir çətinliyi yoxdur", "Mikroservislərdə consistency avtomatikdir", "Yalnız test mühitində çətindir"), 0, Difficulty.HARD),
            new Question("Mikroservislər Memarlığı", "Mikroservis memarlığına keçid nə vaxt tövsiyə olunmur?",
                    List.of("Kiçik, sadə tətbiqlərdə, komandanın təcrübəsi məhdud olduqda", "Həmişə tövsiyə olunur",
                            "Heç bir halda tövsiyə olunmur", "Yalnız böyük şirkətlərdə"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Health check endpoint-ləri mikroservislərdə nə üçün istifadə olunur?",
                    List.of("Servisin sağlam işlədiyini monitorinq/orkestrasiya sistemlərinə bildirmək üçün", "Servisi silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Event-driven mikroservis memarlığı nə deməkdir?",
                    List.of("Servislərin hadisələr (events) vasitəsilə asinxron kommunikasiya qurması", "Yalnız sinxron çağırışlar",
                            "Heç bir mənası yoxdur", "Yalnız UI üçün"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Mikroservislərin versiyalaşdırılması niyə vacibdir?",
                    List.of("Fərqli servislərin müxtəlif templərdə inkişaf etməsinə baxmayaraq uyğunluğu qorumaq üçün", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız UI üçündür", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("Mikroservislər Memarlığı", "Mikroservislərdə 'sidecar' pattern nə üçün istifadə olunur (məs. service mesh-də)?",
                    List.of("Əsas servisə köməkçi funksionallıq (logging, proxy) əlavə etmək üçün ayrıca konteyner", "Əsas servisi əvəz etmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.HARD),

            new Question("Proqram Memarlığı Üslubları", "Layered (qatlı) memarlıq nə deməkdir?",
                    List.of("Tətbiqi məsuliyyətə görə qatlara (presentation, business, data) bölmək", "Bütün kodu bir sinifdə saxlamaq",
                            "Heç bir mənası yoxdur", "Yalnız UI üsulu"), 0, Difficulty.EASY),
            new Question("Proqram Memarlığı Üslubları", "MVC (Model-View-Controller) memarlıq nümunəsi nəyi ayırır?",
                    List.of("Data (Model), təqdimat (View) və idarəetmə məntiqini (Controller)", "Yalnız verilənlər bazasını",
                            "Heç bir şeyi ayırmır", "Yalnız test kodunu"), 0, Difficulty.EASY),
            new Question("Proqram Memarlığı Üslubları", "Hexagonal Architecture (Ports and Adapters) nəyi hədəfləyir?",
                    List.of("Əsas biznes məntiqini xarici asılılıqlardan (verilənlər bazası, UI) izolyasiya etmək", "Bütün kodu qarışdırmaq",
                            "Heç bir hədəfi yoxdur", "Yalnız test üçündür"), 0, Difficulty.HARD),
            new Question("Proqram Memarlığı Üslubları", "Domain-Driven Design (DDD) nəyə fokuslanır?",
                    List.of("Biznes domeninin modelləşdirilməsinə və domen ekspertləri ilə əməkdaşlığa", "Yalnız verilənlər bazası dizaynına",
                            "Heç bir fokusu yoxdur", "Yalnız UI dizaynına"), 0, Difficulty.MEDIUM),
            new Question("Proqram Memarlığı Üslubları", "Event Sourcing memarlıq nümunəsi nə edir?",
                    List.of("Sistem vəziyyətini birbaşa saxlamaq əvəzinə, vəziyyəti dəyişən hadisələrin ardıcıllığını saxlayır",
                            "Yalnız cari vəziyyəti saxlayır", "Heç bir mənası yoxdur", "Yalnız UI üçündür"), 0, Difficulty.HARD),
            new Question("Proqram Memarlığı Üslubları", "CQRS (Command Query Responsibility Segregation) nəyi ayırır?",
                    List.of("Data yazma (command) və oxuma (query) əməliyyatlarının modellərini/yollarını", "Yalnız UI-ı",
                            "Heç bir şeyi ayırmır", "Yalnız test kodunu"), 0, Difficulty.HARD),
            new Question("Proqram Memarlığı Üslubları", "Clean Architecture-ın əsas prinsipi nədir?",
                    List.of("Asılılıqların daxili (domen) qatdan xarici qatlara deyil, əksinə yönəlməsi", "Bütün qatların bir-birindən asılı olması",
                            "Heç bir prinsipi yoxdur", "Yalnız UI-a aiddir"), 0, Difficulty.HARD),
            new Question("Proqram Memarlığı Üslubları", "Service-Oriented Architecture (SOA) mikroservislərdən nə ilə fərqlənir?",
                    List.of("SOA adətən daha iri, paylaşılan servislər və enterprise service bus istifadə edir, mikroservis daha kiçik və müstəqildir",
                            "Fərq yoxdur", "SOA daha kiçikdir", "Mikroservis həmişə ESB istifadə edir"), 0, Difficulty.HARD),
            new Question("Proqram Memarlığı Üslubları", "Peer-to-Peer (P2P) memarlıq nümunəsində node-ların rolu nədir?",
                    List.of("Hər node həm klient, həm də server rolunu oynaya bilər", "Yalnız server rolu", "Yalnız klient rolu",
                            "Heç bir rolu yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Proqram Memarlığı Üslubları", "Serverless memarlıq nə deməkdir?",
                    List.of("İnfrastrukturu bulud provideri idarə edir, developer yalnız funksiya kodu yazır",
                            "Server olmayan tətbiq deməkdir hərfi mənada", "Heç bir mənası yoxdur", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Proqram Memarlığı Üslubları", "Repository Pattern nə üçün istifadə olunur?",
                    List.of("Data giriş məntiqini (data access) biznes məntiqindən abstraksiya etmək üçün", "UI yaratmaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Proqram Memarlığı Üslubları", "Client-Server memarlıq modeli nəyi təsvir edir?",
                    List.of("Klientlərin resurs/xidmət üçün mərkəzi serverə müraciət etməsini", "Bütün node-ların bərabər olmasını",
                            "Heç bir mənası yoxdur", "Yalnız P2P-yə aiddir"), 0, Difficulty.EASY),
            new Question("Proqram Memarlığı Üslubları", "Onion Architecture Hexagonal Architecture ilə hansı ortaq ideyanı paylaşır?",
                    List.of("Domen məntiqini mərkəzdə saxlayıb xarici asılılıqları kənarda tutmaq", "Heç bir ortaq ideyası yoxdur",
                            "Hər ikisi UI-a fokuslanır", "Hər ikisi verilənlər bazasına fokuslanır"), 0, Difficulty.HARD),
            new Question("Proqram Memarlığı Üslubları", "Pipe and Filter memarlıq nümunəsi nə edir?",
                    List.of("Data-nı ardıcıl emal addımlarından (filter) keçirərək emal edir (pipe ilə bağlanır)", "Yalnız bir addımda emal edir",
                            "Heç bir mənası yoxdur", "Yalnız UI-a aiddir"), 0, Difficulty.MEDIUM),
            new Question("Proqram Memarlığı Üslubları", "N-tier (çox qatlı) memarlıq layered memarlıqdan nə ilə fərqlənir?",
                    List.of("N-tier fiziki ayrılmanı (fərqli serverlər) vurğulaya bilər, layered isə məntiqi təşkilata fokuslanır", "Fərq yoxdur",
                            "N-tier yalnız 2 qatdan ibarətdir", "Layered həmişə fiziki ayrılma tələb edir"), 0, Difficulty.MEDIUM),
            new Question("Proqram Memarlığı Üslubları", "Broker pattern paylanmış sistemlərdə nə edir?",
                    List.of("Komponentlər arasında kommunikasiyanı koordinasiya edir", "Data-nı silir", "Heç bir işi yoxdur",
                            "Yalnız UI üçündür"), 0, Difficulty.MEDIUM),
            new Question("Proqram Memarlığı Üslubları", "Actor Model memarlıq üslubunda 'actor' nəyi təmsil edir?",
                    List.of("Öz vəziyyətini idarə edən, mesajlaşma vasitəsilə digərləri ilə əlaqə quran izolyasiya edilmiş hesablama vahidi",
                            "Fiziki server", "Verilənlər bazası", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("Proqram Memarlığı Üslubları", "Space-Based Architecture nə üçün nəzərdə tutulub?",
                    List.of("Paylanmış, in-memory data grid vasitəsilə yüksək miqyaslanma tələb edən sistemlər üçün",
                            "Kiçik, tək server tətbiqlər üçün", "Heç bir məqsədi yoxdur", "Yalnız UI üçün"), 0, Difficulty.HARD),
            new Question("Proqram Memarlığı Üslubları", "Memarlıq üslubu seçimi nədən asılıdır?",
                    List.of("Layihənin ölçüsü, komanda təcrübəsi, scaling və mürəkkəblik tələbləri", "Yalnız moda", "Heç bir amildən asılı deyil",
                            "Yalnız qiymətdən"), 0, Difficulty.MEDIUM),
            new Question("Proqram Memarlığı Üslubları", "Big Ball of Mud anti-pattern-i nəyi ifadə edir?",
                    List.of("Aydın strukturu olmayan, qarışıq, idarə olunması çətin kod bazası", "Yaxşı strukturlaşdırılmış sistem",
                            "Heç bir mənası yoxdur", "Yalnız kiçik layihələrə aiddir"), 0, Difficulty.MEDIUM),

            new Question("Təhlükəsizlik", "OWASP Top 10 nədir?",
                    List.of("Veb tətbiqlərdə ən kritik təhlükəsizlik risklərinin siyahısı", "Proqramlaşdırma dili", "Test framework-ü",
                            "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Təhlükəsizlik", "XSS (Cross-Site Scripting) həmləsi nədir?",
                    List.of("Zərərli skriptin veb səhifəyə inject edilərək başqa istifadəçilərin brauzerində icra edilməsi", "SQL injection növü",
                            "Şəbəkə kəsintisi", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "SQL Injection həmləsindən qorunmanın ən effektiv üsulu hansıdır?",
                    List.of("Parametrləşdirilmiş sorğular (PreparedStatement) istifadə etmək", "Sorğunu String birləşdirmə ilə qurmaq",
                            "Heç bir üsul yoxdur", "Yalnız input-u gizlətmək"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "HTTPS, HTTP-dən nə ilə fərqlənir təhlükəsizlik baxımından?",
                    List.of("Data-nı TLS/SSL ilə şifrələyərək ötürür", "Fərq yoxdur", "HTTP daha təhlükəsizdir",
                            "HTTPS şifrələmə tələb etmir"), 0, Difficulty.EASY),
            new Question("Təhlükəsizlik", "Şifrələmə (encryption) və hashing arasındakı fərq nədir?",
                    List.of("Şifrələmə geri qaytarıla bilər (açarla), hashing isə birtərəflidir", "Fərq yoxdur", "Hashing geri qaytarıla bilər",
                            "Şifrələmə birtərəflidir"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "Salt (duz) parol hashing-də nə üçün istifadə olunur?",
                    List.of("Eyni parolların fərqli hash nəticəsi verməsini təmin edərək rainbow table həmləsindən qorunmaq üçün",
                            "Heç bir məqsədi yoxdur", "Parolu sürətləndirmək üçün", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "Man-in-the-Middle (MITM) həmləsi nədir?",
                    List.of("Həmləçinin iki tərəf arasındakı kommunikasiyanı gizlicə ələ keçirməsi/dinləməsi", "Server çökməsi",
                            "SQL injection növü", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "Input validation (giriş validasiyası) niyə təhlükəsizlik üçün vacibdir?",
                    List.of("Zərərli və ya gözlənilməz məlumatın sistemə daxil olmasının qarşısını alır", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız UI üçündür", "Performansı azaldır"), 0, Difficulty.EASY),
            new Question("Təhlükəsizlik", "DDoS (Distributed Denial of Service) həmləsi nə edir?",
                    List.of("Çoxlu mənbədən gələn həddindən artıq trafiklə sistemi işə yaramaz hala salır", "Data oğurlayır",
                            "Şifrələri sındırır", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Təhlükəsizlik", "Security by design prinsipi nə deməkdir?",
                    List.of("Təhlükəsizliyi sonradan əlavə etmək əvəzinə layihələndirmə mərhələsindən nəzərə almaq", "Təhlükəsizliyi ən sonda düşünmək",
                            "Heç bir mənası yoxdur", "Yalnız test mühitinə aiddir"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "CSRF (Cross-Site Request Forgery) həmləsindən qorunmaq üçün ümumi üsul hansıdır?",
                    List.of("CSRF token istifadə etmək", "Heç bir üsul yoxdur", "Şifrəni dəyişmək", "Yalnız HTTPS kifayətdir"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "Insecure Deserialization riski nədir?",
                    List.of("Zərərli serialized data-nın icra olunan koda çevrilə bilməsi", "Heç bir risk yoxdur", "Yalnız performans problemi",
                            "Fayl böyüməsi"), 0, Difficulty.HARD),
            new Question("Təhlükəsizlik", "Principle of Defense in Depth (dərinlikdə müdafiə) nə deməkdir?",
                    List.of("Bir təhlükəsizlik qatının uğursuz olması halında digərlərinin qorunmanı davam etdirməsi üçün çoxlu qat müdafiə tətbiq etmək",
                            "Yalnız bir müdafiə qatı kifayətdir", "Heç bir mənası yoxdur", "Yalnız firewall-a aiddir"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "Security headers (məs. Content-Security-Policy) nə üçün istifadə olunur?",
                    List.of("Brauzerə müəyyən təhlükəsizlik davranışlarını (məs. skript mənbələrini məhdudlaşdırmaq) diktə etmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız performans üçün", "Yalnız SEO üçün"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "Vulnerability scanning alətləri nə üçün istifadə olunur?",
                    List.of("Sistemdə məlum təhlükəsizlik boşluqlarını avtomatik aşkarlamaq üçün", "Kodu compile etmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "Penetration testing (pentest) nədir?",
                    List.of("Sistemin təhlükəsizlik zəifliklərini aşkarlamaq üçün icazəli, simulyasiya edilmiş həmlə", "İcazəsiz həmlə",
                            "Heç bir mənası yoxdur", "Yalnız avtomatik skan"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "Sensitive data exposure riskini azaltmaq üçün nə tövsiyə olunur?",
                    List.of("Həssas data-nı şifrələmək, minimal saxlamaq və giriş nəzarəti tətbiq etmək", "Heç bir tədbir görməmək",
                            "Data-nı açıq mətn kimi saxlamaq", "Heç bir tövsiyə yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "Broken Access Control OWASP Top 10-da nəyi ifadə edir?",
                    List.of("İstifadəçilərin icazəsiz resurs/əməliyyatlara çıxış əldə edə bilməsi", "Sistem sürətinin aşağı olması",
                            "Heç bir mənası yoxdur", "Yalnız UI xətası"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "Security Misconfiguration nədir?",
                    List.of("Sistemin qeyri-təhlükəsiz default parametrlər və ya natamam konfiqurasiya ilə buraxılması", "Kodun səhv yazılması",
                            "Heç bir mənası yoxdur", "Yalnız şəbəkə problemi"), 0, Difficulty.MEDIUM),
            new Question("Təhlükəsizlik", "Zero Trust təhlükəsizlik modeli nə deməkdir?",
                    List.of("Şəbəkə daxilindəki heç bir isteğin/istifadəçinin default olaraq etibarlı sayılmaması, hər dəfə yoxlanması",
                            "Bütün daxili trafikə etibar etmək", "Heç bir mənası yoxdur", "Yalnız xarici trafikə aid"), 0, Difficulty.MEDIUM),

            new Question("Networking və HTTP Əsasları", "TCP və UDP protokolları arasındakı əsas fərq nədir?",
                    List.of("TCP əlaqə-yönümlü və etibarlıdır, UDP isə əlaqəsiz və daha sürətli, lakin etibarsızdır", "Fərq yoxdur",
                            "UDP daha etibarlıdır", "TCP daha sürətlidir həmişə"), 0, Difficulty.MEDIUM),
            new Question("Networking və HTTP Əsasları", "DNS (Domain Name System) nə üçün istifadə olunur?",
                    List.of("Domen adlarını IP ünvanlarına çevirmək üçün", "Faylları saxlamaq üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız email üçün"), 0, Difficulty.EASY),
            new Question("Networking və HTTP Əsasları", "HTTP-nin default portu neçədir?",
                    List.of("80", "443", "8080", "21"), 0, Difficulty.EASY),
            new Question("Networking və HTTP Əsasları", "HTTPS-in default portu neçədir?",
                    List.of("443", "80", "8443", "22"), 0, Difficulty.EASY),
            new Question("Networking və HTTP Əsasları", "IP ünvanının məqsədi nədir?",
                    List.of("Şəbəkədəki cihazı unikal olaraq identifikasiya etmək", "Faylı adlandırmaq", "Heç bir mənası yoxdur",
                            "Yalnız internal istifadə üçün"), 0, Difficulty.EASY),
            new Question("Networking və HTTP Əsasları", "TCP three-way handshake prosesi nədir?",
                    List.of("SYN, SYN-ACK, ACK mesajları ilə əlaqənin qurulması", "Yalnız bir mesaj mübadiləsi", "Heç bir mənası yoxdur",
                            "Yalnız UDP-yə aiddir"), 0, Difficulty.MEDIUM),
            new Question("Networking və HTTP Əsasları", "OSI modelinin neçə qatı var?",
                    List.of("7", "5", "4", "10"), 0, Difficulty.MEDIUM),
            new Question("Networking və HTTP Əsasları", "HTTP başlıqları (headers) nə üçün istifadə olunur?",
                    List.of("Sorğu/cavab haqqında meta-məlumat ötürmək üçün (məs. Content-Type, Authorization)", "Yalnız data ötürmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız cookie üçün"), 0, Difficulty.EASY),
            new Question("Networking və HTTP Əsasları", "Cookie nə üçün istifadə olunur?",
                    List.of("Klient tərəfində kiçik data (sessiya, preferences) saxlamaq üçün", "Server-i identifikasiya etmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız şifrələmə üçün"), 0, Difficulty.EASY),
            new Question("Networking və HTTP Əsasları", "Firewall nə üçün istifadə olunur?",
                    List.of("Şəbəkə trafikini müəyyən qaydalara əsasən süzgəcdən keçirərək icazəsiz girişi əngəlləmək üçün", "Data saxlamaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.EASY),
            new Question("Networking və HTTP Əsasları", "Load balancer-in Layer 4 və Layer 7 balanslaşdırması arasındakı fərq nədir?",
                    List.of("Layer 4 TCP/UDP səviyyəsində, Layer 7 tətbiq (HTTP) səviyyəsində qərar verir", "Fərq yoxdur",
                            "Layer 7 daha sadədir", "Layer 4 HTTP başlıqlarına baxır"), 0, Difficulty.HARD),
            new Question("Networking və HTTP Əsasları", "NAT (Network Address Translation) nə üçün istifadə olunur?",
                    List.of("Daxili şəbəkə ünvanlarını xarici (public) IP ünvanına çevirmək üçün", "DNS sorğularını həll etmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız şifrələmə üçün"), 0, Difficulty.MEDIUM),
            new Question("Networking və HTTP Əsasları", "HTTP/2, HTTP/1.1-dən nə ilə fərqlənir?",
                    List.of("Multiplexing dəstəkləyir, eyni bağlantı üzərindən paralel sorğulara imkan verir", "Fərq yoxdur", "Daha yavaşdır",
                            "Şifrələməni əvəz edir"), 0, Difficulty.MEDIUM),
            new Question("Networking və HTTP Əsasları", "SSL/TLS handshake zamanı nə baş verir?",
                    List.of("Klient və server şifrələmə parametrlərini razılaşdırır və sertifikatı yoxlayır", "Heç nə baş vermir",
                            "Yalnız data ötürülür", "Yalnız DNS sorğusu göndərilir"), 0, Difficulty.MEDIUM),
            new Question("Networking və HTTP Əsasları", "Proxy server nə üçün istifadə olunur?",
                    List.of("Klient və server arasında vasitəçi rolunu oynayaraq sorğuları yönləndirmək (keşləmə, anonimlik, filtr) üçün",
                            "Data saxlamaq üçün", "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Networking və HTTP Əsasları", "Latency (gecikmə) və bandwidth (buraxılış qabiliyyəti) arasındakı fərq nədir?",
                    List.of("Latency data-nın çatması üçün lazım olan vaxt, bandwidth isə vahid zamanda ötürülə bilən data həcmidir",
                            "Fərq yoxdur", "Bandwidth vaxtı ölçür", "Latency data həcmini ölçür"), 0, Difficulty.MEDIUM),
            new Question("Networking və HTTP Əsasları", "WebSocket-dən fərqli olaraq adi HTTP sorğusu niyə hər dəfə yeni bağlantı tələb edə bilər (HTTP/1.0-da)?",
                    List.of("Default olaraq hər sorğudan sonra bağlantı bağlanırdı (keep-alive HTTP/1.1-də yaxşılaşdırıldı)", "Heç bir səbəb yoxdur",
                            "HTTP həmişə davamlı bağlantı saxlayır", "Yalnız HTTPS-ə aiddir"), 0, Difficulty.HARD),
            new Question("Networking və HTTP Əsasları", "IPv4 və IPv6 arasındakı əsas fərq nədir?",
                    List.of("IPv6 daha böyük ünvan sahəsinə malikdir (128-bit, IPv4 32-bit)", "Fərq yoxdur", "IPv4 daha çox ünvana malikdir",
                            "IPv6 daha köhnədir"), 0, Difficulty.MEDIUM),
            new Question("Networking və HTTP Əsasları", "HTTP-də 'keep-alive' başlığı nə edir?",
                    List.of("TCP bağlantısını bir neçə sorğu/cavab üçün açıq saxlayır, hər dəfə yenidən qurmaqdan qaçır", "Bağlantını dərhal bağlayır",
                            "Heç bir işi yoxdur", "Yalnız HTTPS üçündür"), 0, Difficulty.MEDIUM),
            new Question("Networking və HTTP Əsasları", "Ping əmri nə üçün istifadə olunur?",
                    List.of("Şəbəkədə bir hostun əlçatan olub-olmadığını və gecikməni yoxlamaq üçün", "Faylı köçürmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız DNS üçün"), 0, Difficulty.EASY)
    );

    public static List<Question> get() {
        return QUESTIONS;
    }
}
