package repository.bank;

import model.Difficulty;
import model.Question;

import java.util.List;

public class CollectionsDataStructuresQuestions {

    private static final List<Question> QUESTIONS = List.of(
            new Question("Kolleksiyalar", "ArrayList və LinkedList arasındakı əsas fərq nədir?",
                    List.of("ArrayList sıralanmır", "ArrayList array əsaslıdır, LinkedList node əsaslıdır",
                            "LinkedList thread-safe-dir", "Fərq yoxdur"), 1, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "HashMap-də açarların unikallığı necə təmin olunur?",
                    List.of("equals() və hashCode() metodları ilə", "compareTo() metodu ilə",
                            "toString() metodu ilə", "clone() metodu ilə"), 0, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "Hansı kolleksiya interfeysi dublikat elementlərə icazə vermir?",
                    List.of("List", "Set", "Queue", "Map (values)"), 1, Difficulty.EASY),
            new Question("Kolleksiyalar", "TreeMap elementləri necə saxlayır?",
                    List.of("Təsadüfi ardıcıllıqla", "Açarların təbii sıralaması ilə",
                            "Əlavə olunma ardıcıllığı ilə", "Heç bir sıralama olmadan"), 1, Difficulty.HARD),
            new Question("Kolleksiyalar", "Iterator və ListIterator arasındakı fərq nədir?",
                    List.of("ListIterator yalnız irəli hərəkət edir", "ListIterator həm irəli, həm geri hərəkət edə bilər",
                            "Iterator List üçün işləmir", "Fərq yoxdur"), 1, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "ConcurrentModificationException nə vaxt yaranır?",
                    List.of("Kolleksiya iterasiya zamanı birbaşa dəyişdirildikdə", "Kolleksiya boş olduqda",
                            "Kolleksiya sıralandıqda", "Heç vaxt"), 0, Difficulty.HARD),
            new Question("Kolleksiyalar", "PriorityQueue elementləri necə sıralayır?",
                    List.of("Əlavə olunma ardıcıllığı ilə", "Təbii sıralama və ya verilmiş Comparator əsasında",
                            "Təsadüfi", "Sıralamır"), 1, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "Collections.unmodifiableList() nə edir?",
                    List.of("List-i sıralayır", "List-in dəyişdirilə bilməyən görünüşünü qaytarır",
                            "List-i kopyalayır", "List-i silir"), 1, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "LinkedHashMap HashMap-dən nə ilə fərqlənir?",
                    List.of("Elementlərin əlavə olunma ardıcıllığını saxlayır", "Sürəti daha yüksəkdir",
                            "Null açara icazə vermir", "Fərq yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "Comparable və Comparator interfeysləri arasındakı fərq nədir?",
                    List.of("Comparable sinifin öz daxilində təbii sıralamanı, Comparator isə xarici, xüsusi sıralamanı təyin edir",
                            "Fərq yoxdur", "Comparator yalnız String üçündür", "Comparable xarici sıralama üçündür"),
                    0, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "HashSet-in daxili implementasiyası nəyə əsaslanır?",
                    List.of("HashMap-ə (elementlər HashMap-in açarları kimi saxlanılır)", "ArrayList-ə", "LinkedList-ə", "TreeMap-ə"),
                    0, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "Deque interfeysi nəyi təmsil edir?",
                    List.of("Hər iki ucdan element əlavə/silmə imkanı verən double-ended queue", "Yalnız FIFO növbə",
                            "Yalnız LIFO stack", "Sıralanmış Set"), 0, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "Vector və ArrayList arasındakı fərq nədir?",
                    List.of("Vector sinxronizasiya olunub (thread-safe), ArrayList yox", "Fərq yoxdur",
                            "ArrayList daha köhnədir", "Vector daha sürətlidir"), 0, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "EnumMap nədir?",
                    List.of("Açarları enum tipində olan yüksək performanslı Map implementasiyası", "HashMap-in sinonimi",
                            "Yalnız String açarlar üçün Map", "Immutable Map"), 0, Difficulty.HARD),
            new Question("Kolleksiyalar", "Collections.sort() metodu hansı alqoritmdən istifadə edir (obyektlər üçün)?",
                    List.of("TimSort (merge sort variantı)", "Quick sort", "Bubble sort", "Heap sort"), 0, Difficulty.HARD),
            new Question("Kolleksiyalar", "NavigableMap interfeysi nəyi təmin edir?",
                    List.of("floorKey, ceilingKey kimi naviqasiya metodları ilə sıralanmış Map", "Yalnız açarları sıralanmayan Map",
                            "Thread-safe Map", "Immutable Map"), 0, Difficulty.HARD),
            new Question("Kolleksiyalar", "Kolleksiyada fail-fast iterator nə deməkdir?",
                    List.of("Kolleksiya iterasiya zamanı dəyişdirildikdə dərhal ConcurrentModificationException atır", "Heç vaxt xəta vermir",
                            "Yalnız oxumaq üçündür", "Kolleksiyanı avtomatik düzəldir"), 0, Difficulty.HARD),
            new Question("Kolleksiyalar", "Arrays.asList() metodu ilə yaradılan List-in ölçüsü dəyişdirilə bilərmi?",
                    List.of("Xeyr, sabit ölçülüdür (add/remove UnsupportedOperationException atır)", "Bəli, sərbəst dəyişdirilə bilər",
                            "Yalnız kiçildilə bilər", "Yalnız böyüdülə bilər"), 0, Difficulty.HARD),
            new Question("Kolleksiyalar", "Stack sinifi hansı sinifi extend edir Java-da?",
                    List.of("Vector", "ArrayList", "LinkedList", "AbstractList"), 0, Difficulty.MEDIUM),
            new Question("Kolleksiyalar", "Java-da Map interfeysi Collection interfeysini extend edirmi?",
                    List.of("Xeyr, Map ayrıca hierarxiyadadır (açar-dəyər cütləri üçün)", "Bəli, tam extend edir",
                            "Yalnız SortedMap extend edir", "Heç bir əlaqəsi yoxdur"), 0, Difficulty.MEDIUM),

            new Question("Generics", "Generics-in əsas məqsədi nədir?",
                    List.of("Kodun icra sürətini artırmaq", "Compile-time tip təhlükəsizliyi təmin etmək",
                            "Yaddaşı azaltmaq", "Multithreading dəstəkləmək"), 1, Difficulty.MEDIUM),
            new Question("Generics", "'List<?>' ifadəsi nəyi bildirir?",
                    List.of("İstənilən tipdə element saxlaya bilən wildcard List", "Yalnız Integer List",
                            "Boş List", "Sabit tipli List"), 0, Difficulty.MEDIUM),
            new Question("Generics", "'<T extends Number>' bildirişi nəyi ifadə edir?",
                    List.of("T tipi Number sinifini extend edən tip olmalıdır", "T yalnız String ola bilər",
                            "Heç bir məhdudiyyət yoxdur", "T mütləq abstrakt olmalıdır"), 0, Difficulty.HARD),
            new Question("Generics", "Type erasure nədir?",
                    List.of("Compile zamanı generic tip məlumatının silinməsi (runtime-da olmaması)",
                            "Runtime-da tip yaradılması", "Generic siniflərin silinməsi", "Heç bir əlaqəsi yoxdur"),
                    0, Difficulty.HARD),
            new Question("Generics", "Generic metod necə elan olunur?",
                    List.of("Metod adından əvvəl tip parametri ilə, məs. <T> T method()", "Yalnız sinif səviyyəsində",
                            "Generic metod mümkün deyil", "Return tipindən sonra"), 0, Difficulty.MEDIUM),
            new Question("Generics", "Raw type (məs. List list = new ArrayList()) istifadəsi nə üçün tövsiyə olunmur?",
                    List.of("Compile-time tip yoxlamasını itirir", "Daha sürətli işləyir",
                            "Daha az yaddaş tutur", "Heç bir problem yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Generics", "'? super T' wildcard nəyi ifadə edir?",
                    List.of("T və ya onun hər hansı superclass-ı", "T və ya onun subclass-ları",
                            "Yalnız T", "Heç bir tip"), 0, Difficulty.HARD),
            new Question("Generics", "Generic sinifdə statik sahə niyə generic tip parametrindən istifadə edə bilməz?",
                    List.of("Statik sahələr bütün instansiyalar arasında paylaşılır, amma generic tip hər instansiya üçün fərqli ola bilər",
                            "Statik sahələr generic ola bilər", "Heç bir səbəb yoxdur", "Statik sahələr yalnız private olur"),
                    0, Difficulty.HARD),
            new Question("Generics", "Bounded type parameter nədir?",
                    List.of("Tip parametrinin müəyyən sinif və ya interfeys ilə məhdudlaşdırılması (məs. <T extends Comparable>)",
                            "Sərhədsiz tip", "Yalnız primitiv tiplər", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Generics", "Generic array yaratmaq (məs. new T[10]) Java-da niyə mümkün deyil?",
                    List.of("Type erasure səbəbindən runtime-da tip məlumatı olmur", "Java array dəstəkləmir",
                            "Yaddaş çatışmır", "Heç bir səbəb yoxdur"), 0, Difficulty.HARD),
            new Question("Generics", "PECS principle (Producer Extends, Consumer Super) nəyi izah edir?",
                    List.of("Wildcard-larda 'extends' producer üçün, 'super' consumer üçün istifadə olunmalıdır", "Heç bir mənası yoxdur",
                            "Yalnız consumer üçün extends istifadə olunur", "PECS yalnız array-lərə aiddir"), 0, Difficulty.HARD),
            new Question("Generics", "Generic sinifdə birdən çox tip parametri necə istifadə olunur?",
                    List.of("<K, V> kimi vergüllə ayrılmış tip parametrləri ilə (məs. Map<K,V>)", "Yalnız bir tip parametri istifadə oluna bilər",
                            "Generic siniflər çoxlu tip qəbul edə bilməz", "Heç bir üsulu yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Generics", "Unbounded wildcard (<?>) nə vaxt istifadə olunur?",
                    List.of("Tip parametrinin konkret dəyəri əhəmiyyət kəsb etmədikdə, məs. List ölçüsünü çap etmək üçün", "Heç vaxt",
                            "Yalnız Integer üçün", "Yalnız yazma əməliyyatları üçün"), 0, Difficulty.MEDIUM),
            new Question("Generics", "Generic interfeysin implementasiyasında tip parametri necə konkretləşdirilə bilər?",
                    List.of("implements Comparable<String> kimi konkret tip verməklə", "Mümkün deyil",
                            "Yalnız abstract siniflərdə", "Heç bir üsulu yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Generics", "Java-da generics niyə 'reified' deyil (C#-dan fərqli olaraq)?",
                    List.of("Runtime-da generic tip məlumatı type erasure səbəbindən saxlanmır", "Java generics C#-dan daha güclüdür",
                            "Reified deməkdir generic olmayan", "Heç bir fərq yoxdur"), 0, Difficulty.HARD),
            new Question("Generics", "Generic metodda tip parametrini çağırış zamanı açıq şəkildə necə göstərmək olar?",
                    List.of("ClassName.<Type>methodName() sintaksisi ilə", "Mümkün deyil", "Yalnız reflection ilə", "Yalnız constructor-da"),
                    0, Difficulty.HARD),
            new Question("Generics", "Bridge metod (bridge method) nədir?",
                    List.of("Type erasure zamanı compiler-in generic tip təhlükəsizliyini saxlamaq üçün avtomatik yaratdığı sintetik metod",
                            "Proqramçının əl ilə yazdığı metod", "Yalnız interfeyslərdə olur", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("Generics", "Generics istifadə etməklə hansı runtime xətasının qarşısı compile zamanı alınır?",
                    List.of("ClassCastException", "NullPointerException", "ArithmeticException", "StackOverflowError"), 0, Difficulty.MEDIUM),
            new Question("Generics", "Diamond operator (<>) Java 7+-da nəyə imkan verir?",
                    List.of("Sağ tərəfdə tip parametrini təkrar yazmadan generic obyekt yaratmağa (məs. new ArrayList<>())",
                            "Yeni generic sinif yaratmağa", "Type erasure-u ləğv etməyə", "Heç nəyə"), 0, Difficulty.EASY),
            new Question("Generics", "Generic sinifin instansiyasında tip parametri üçün primitiv tip (məs. int) istifadə oluna bilərmi?",
                    List.of("Xeyr, yalnız wrapper siniflər (Integer və s.) istifadə oluna bilər", "Bəli, sərbəst istifadə oluna bilər",
                            "Yalnız double üçün mümkündür", "Heç bir məhdudiyyət yoxdur"), 0, Difficulty.MEDIUM),

            new Question("Verilənlər Strukturları", "Massiv (array) və List arasındakı əsas fərq nədir?",
                    List.of("Massivin ölçüsü sabitdir, List dinamik böyüyə bilər", "Fərq yoxdur",
                            "List yalnız primitivlər üçündür", "Massiv həmişə daha yavaşdır"), 0, Difficulty.EASY),
            new Question("Verilənlər Strukturları", "Stack (yığın) verilənlər strukturu hansı prinsiplə işləyir?",
                    List.of("LIFO (Last In, First Out)", "FIFO (First In, First Out)", "Təsadüfi çıxış", "Prioritet əsaslı"),
                    0, Difficulty.EASY),
            new Question("Verilənlər Strukturları", "Queue (növbə) verilənlər strukturu hansı prinsiplə işləyir?",
                    List.of("FIFO (First In, First Out)", "LIFO", "Təsadüfi", "Yalnız sıralanmış"), 0, Difficulty.EASY),
            new Question("Verilənlər Strukturları", "Linked List-in Array-dən üstünlüyü nədir?",
                    List.of("Ortada element əlavə/silmə O(1) ola bilər (node dəyişikliyi ilə)", "Həmişə daha az yaddaş tutur",
                            "İndeksə görə çıxış daha sürətlidir", "Heç bir üstünlüyü yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Strukturları", "Binary Tree-də hər node-un maksimum neçə uşağı ola bilər?",
                    List.of("2", "1", "3", "Sonsuz"), 0, Difficulty.EASY),
            new Question("Verilənlər Strukturları", "Hash table-də collision (toqquşma) nə vaxt baş verir?",
                    List.of("İki fərqli açar eyni hash dəyərinə (bucket-ə) düşdükdə", "Cədvəl boş olduqda",
                            "Yalnız açar silindikdə", "Heç vaxt baş vermir"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Strukturları", "Graph (qraf) verilənlər strukturunda 'node' və 'edge' nəyi ifadə edir?",
                    List.of("Node — obyekt/vertex, edge — node-lar arasındakı əlaqə", "Node — əlaqə, edge — obyekt",
                            "Fərq yoxdur", "Yalnız ağaclara aiddir"), 0, Difficulty.EASY),
            new Question("Verilənlər Strukturları", "Trie (prefix tree) verilənlər strukturu ən çox nə üçün istifadə olunur?",
                    List.of("Söz/prefiks axtarışı və avtomatik tamamlama üçün", "Rəqəm sıralaması üçün",
                            "Qraf axtarışı üçün", "Yalnız şifrələmə üçün"), 0, Difficulty.HARD),
            new Question("Verilənlər Strukturları", "Heap verilənlər strukturunun əsas xüsusiyyəti nədir?",
                    List.of("Valideyn node uşaq node-lardan həmişə böyük (max-heap) və ya kiçik (min-heap) olur",
                            "Sıralanmamış massivdir", "LIFO-dur", "Yalnız string saxlayır"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Strukturları", "Dynamic Array (məs. ArrayList) tutumu (capacity) dolduqda nə baş verir?",
                    List.of("Daha böyük yeni massiv yaradılır və elementlər köçürülür", "Xəta atılır",
                            "Əlavə etmə rədd edilir", "Heç nə baş vermir"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Strukturları", "Circular Linked List adi Linked List-dən nə ilə fərqlənir?",
                    List.of("Son node ilk node-a işarə edir, sonsuz dövr yaradır", "Fərq yoxdur",
                            "Yalnız bir node ola bilər", "Heç bir əlaqəsi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Strukturları", "Doubly Linked List-in üstünlüyü Singly Linked List-ə görə nədir?",
                    List.of("Hər node əvvəlki və sonrakı node-a işarə edir, geriyə hərəkət mümkündür", "Daha az yaddaş tutur",
                            "Daha sürətli axtarış edir", "Heç bir üstünlüyü yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Strukturları", "Balanced Binary Search Tree (məs. AVL, Red-Black) niyə vacibdir?",
                    List.of("Ağacın hündürlüyünü minimuma endirərək axtarış/əlavə/silmə əməliyyatlarını O(log n)-də saxlayır",
                            "Yaddaşı azaldır", "Yalnız sıralama üçündür", "Heç bir əhəmiyyəti yoxdur"), 0, Difficulty.HARD),
            new Question("Verilənlər Strukturları", "Set verilənlər strukturunun əsas xüsusiyyəti nədir?",
                    List.of("Dublikat elementlərə icazə vermir", "Sıralanmış olmalıdır", "İndeksli çıxış təmin edir",
                            "Yalnız rəqəmlər saxlayır"), 0, Difficulty.EASY),
            new Question("Verilənlər Strukturları", "Adjacency List qrafın təsviri üçün nə üçün istifadə olunur?",
                    List.of("Hər vertex üçün ona qonşu vertex-lərin siyahısını saxlamaq üçün", "Yalnız çəkiləri saxlamaq üçün",
                            "Ağac balansı üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Strukturları", "Skip List nədir?",
                    List.of("Sıralanmış siyahıda sürətli axtarış üçün əlavə 'sıçrayış' səviyyələri olan verilənlər strukturu",
                            "Sadə array", "Binary tree növü", "Hash table növü"), 0, Difficulty.HARD),
            new Question("Verilənlər Strukturları", "LRU Cache (Least Recently Used) implementasiyası üçün adətən hansı iki struktur birləşdirilir?",
                    List.of("HashMap və Doubly Linked List", "Yalnız Array", "Yalnız Stack", "Yalnız Queue"), 0, Difficulty.HARD),
            new Question("Verilənlər Strukturları", "Priority Queue-nun daxili implementasiyası ən çox hansı struktura əsaslanır?",
                    List.of("Heap (binary heap)", "Sadə array", "Linked List", "Hash table"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Strukturları", "Sparse array nə deməkdir?",
                    List.of("Çoxu default/sıfır dəyərli elementlərdən ibarət olan massiv", "Bütün elementləri dolu massiv",
                            "Sıralanmış massiv", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Strukturları", "Tree-də 'leaf node' nəyi ifadə edir?",
                    List.of("Heç bir uşağı olmayan node", "Kök node", "Ən çox uşağı olan node", "Heç bir mənası yoxdur"),
                    0, Difficulty.EASY),

            new Question("Sıralama Alqoritmləri", "Bubble Sort-un orta hal zaman mürəkkəbliyi nədir?",
                    List.of("O(n²)", "O(n log n)", "O(n)", "O(log n)"), 0, Difficulty.EASY),
            new Question("Sıralama Alqoritmləri", "Quick Sort-un əsas iş prinsipi nədir?",
                    List.of("Pivot seçib massivi kiçik/böyük hissələrə bölərək rekursiv sıralamaq", "Elementləri qonşu-qonşu müqayisə etmək",
                            "Heap qurmaq", "Elementləri birləşdirmək"), 0, Difficulty.MEDIUM),
            new Question("Sıralama Alqoritmləri", "Merge Sort-un zaman mürəkkəbliyi (bütün hallarda) nədir?",
                    List.of("O(n log n)", "O(n²)", "O(n)", "O(1)"), 0, Difficulty.MEDIUM),
            new Question("Sıralama Alqoritmləri", "Hansı sıralama alqoritmi 'stable' (sabit) hesab olunur, yəni bərabər elementlərin nisbi sırasını saxlayır?",
                    List.of("Merge Sort", "Quick Sort (adi implementasiyada)", "Heap Sort", "Heç biri"), 0, Difficulty.MEDIUM),
            new Question("Sıralama Alqoritmləri", "Insertion Sort ən çox nə vaxt effektivdir?",
                    List.of("Kiçik və ya demək olar ki sıralanmış massivlərdə", "Böyük təsadüfi massivlərdə",
                            "Heç vaxt effektiv deyil", "Yalnız string-lər üçün"), 0, Difficulty.MEDIUM),
            new Question("Sıralama Alqoritmləri", "Quick Sort-un ən pis hal zaman mürəkkəbliyi nə vaxt yaranır?",
                    List.of("Pivot həmişə ən kiçik və ya ən böyük element seçildikdə", "Massiv artıq sıralı olduqda həmişə yaxşı olur",
                            "Heç vaxt pis hal yoxdur", "Yalnız kiçik massivlərdə"), 0, Difficulty.HARD),
            new Question("Sıralama Alqoritmləri", "Heap Sort-un zaman mürəkkəbliyi nədir?",
                    List.of("O(n log n)", "O(n²)", "O(n)", "O(log n)"), 0, Difficulty.MEDIUM),
            new Question("Sıralama Alqoritmləri", "Counting Sort hansı şəraitdə effektivdir?",
                    List.of("Dəyər aralığı məhdud və məlum olduqda (tam ədədlər üçün)", "İxtiyari obyektlər üçün",
                            "Yalnız string-lər üçün", "Heç vaxt effektiv deyil"), 0, Difficulty.HARD),
            new Question("Sıralama Alqoritmləri", "In-place sıralama alqoritmi nə deməkdir?",
                    List.of("Əlavə (əhəmiyyətli) yaddaş tələb etmədən orijinal massiv daxilində sıralama aparır", "Yeni massiv yaradır",
                            "Yalnız kiçik massivlər üçündür", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Sıralama Alqoritmləri", "Java-nın Arrays.sort() metodu primitiv massivlər üçün hansı alqoritmi istifadə edir?",
                    List.of("Dual-Pivot Quicksort", "Merge Sort", "Bubble Sort", "Insertion Sort yalnız"), 0, Difficulty.HARD),
            new Question("Sıralama Alqoritmləri", "Selection Sort-un iş prinsipi nədir?",
                    List.of("Hər addımda qalan hissədən ən kiçik elementi tapıb düzgün mövqeyə qoymaq", "Elementləri birləşdirmək",
                            "Pivot seçmək", "Heap qurmaq"), 0, Difficulty.EASY),
            new Question("Sıralama Alqoritmləri", "Sıralama alqoritmlərinin aşağı sərhədi (comparison-based) nədir?",
                    List.of("O(n log n)", "O(n)", "O(n²)", "O(1)"), 0, Difficulty.HARD),
            new Question("Sıralama Alqoritmləri", "Radix Sort necə işləyir?",
                    List.of("Rəqəmləri rəqəm-rəqəm (digit by digit) sıralayaraq", "Müqayisə əsasında", "Pivot seçərək", "Heap qurmaqla"),
                    0, Difficulty.HARD),
            new Question("Sıralama Alqoritmləri", "Hansı sıralama alqoritmi divide-and-conquer (böl və hökm sür) strategiyasına əsaslanır?",
                    List.of("Merge Sort", "Bubble Sort", "Insertion Sort", "Selection Sort"), 0, Difficulty.MEDIUM),
            new Question("Sıralama Alqoritmləri", "Bucket Sort-un əsas ideyası nədir?",
                    List.of("Elementləri diapazonlara (bucket-lərə) bölüb hər birini ayrıca sıralamaq", "Pivot seçmək",
                            "Heap qurmaq", "Yalnız tam ədədlər üçündür"), 0, Difficulty.HARD),
            new Question("Sıralama Alqoritmləri", "Java-nın Collections.sort() və Arrays.sort() (obyektlər üçün) hansı alqoritmi istifadə edir?",
                    List.of("TimSort", "Quick Sort", "Bubble Sort", "Selection Sort"), 0, Difficulty.HARD),
            new Question("Sıralama Alqoritmləri", "Ən pis halda O(n²) mürəkkəbliyə malik olmayan alqoritm hansıdır?",
                    List.of("Merge Sort", "Bubble Sort", "Insertion Sort", "Selection Sort"), 0, Difficulty.MEDIUM),
            new Question("Sıralama Alqoritmləri", "Sıralama alqoritmi seçərkən nəyə diqqət edilməlidir?",
                    List.of("Data ölçüsü, yaddaş məhdudiyyəti, stabillik tələbi", "Yalnız kod uzunluğuna",
                            "Yalnız dilin versiyasına", "Heç nəyə"), 0, Difficulty.MEDIUM),
            new Question("Sıralama Alqoritmləri", "Shell Sort nəyin təkmilləşdirilmiş versiyasıdır?",
                    List.of("Insertion Sort", "Quick Sort", "Merge Sort", "Heap Sort"), 0, Difficulty.HARD),
            new Question("Sıralama Alqoritmləri", "Comparator istifadə edərək Java-da kolleksiyanı azalan qaydada necə sıralamaq olar?",
                    List.of("Collections.sort(list, Comparator.reverseOrder())", "Collections.sort(list) yalnız",
                            "list.reverse()", "Sıralama mümkün deyil"), 0, Difficulty.MEDIUM),

            new Question("Axtarış Alqoritmləri və Ağaclar", "Binary Search hansı şərti tələb edir?",
                    List.of("Massivin əvvəlcədən sıralanmış olmasını", "Massivin sıralanmamasını",
                            "Yalnız tam ədədlər olmasını", "Heç bir şərt yoxdur"), 0, Difficulty.EASY),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Binary Search-ün zaman mürəkkəbliyi nədir?",
                    List.of("O(log n)", "O(n)", "O(n²)", "O(1)"), 0, Difficulty.EASY),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Linear Search-ün zaman mürəkkəbliyi nədir?",
                    List.of("O(n)", "O(log n)", "O(1)", "O(n²)"), 0, Difficulty.EASY),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Binary Search Tree (BST)-də sol alt ağacdakı bütün node-lar nəyə görə kiçikdir?",
                    List.of("Kök node-un dəyərindən", "Sağ alt ağacdan", "Heç nəyə görə", "Ən böyük node-dan"), 0, Difficulty.EASY),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Depth-First Search (DFS) qraf/ağac gəzintisi hansı verilənlər strukturundan istifadə edir (adətən)?",
                    List.of("Stack (və ya rekursiya)", "Queue", "Heap", "Hash table"), 0, Difficulty.MEDIUM),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Breadth-First Search (BFS) qraf/ağac gəzintisi hansı verilənlər strukturundan istifadə edir?",
                    List.of("Queue", "Stack", "Heap", "Hash table"), 0, Difficulty.MEDIUM),
            new Question("Axtarış Alqoritmləri və Ağaclar", "In-order traversal Binary Search Tree-də nə nəticə verir?",
                    List.of("Elementlər artan sırada", "Elementlər azalan sırada", "Təsadüfi sıra", "Yalnız kök node"),
                    0, Difficulty.MEDIUM),
            new Question("Axtarış Alqoritmləri və Ağaclar", "AVL Tree nəyi təmin edir?",
                    List.of("Özünü balanslaşdıran BST, hündürlük fərqi həmişə 1-dən çox olmur", "Balanssız ağacdır",
                            "Yalnız sıralı massivdir", "Heç bir xüsusiyyəti yoxdur"), 0, Difficulty.HARD),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Red-Black Tree hansı məqsədlə istifadə olunur?",
                    List.of("Balanslaşdırılmış BST təmin edərək O(log n) əməliyyatlar zəmanət vermək üçün", "Yalnız rəngli data üçün",
                            "Sadə sıralama üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Axtarış Alqoritmləri və Ağaclar", "B-Tree verilənlər bazası indekslərində niyə geniş istifadə olunur?",
                    List.of("Disk əməliyyatlarını minimuma endirmək üçün çoxsaylı uşaq node-lara malikdir", "Yalnız yaddaşda işləyir",
                            "Binary Tree-dən daha yavaşdır həmişə", "Heç bir üstünlüyü yoxdur"), 0, Difficulty.HARD),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Dijkstra alqoritmi nə üçün istifadə olunur?",
                    List.of("Qrafda ən qısa yolu tapmaq üçün (mənfi çəkisiz)", "Sıralama üçün", "Ağac balanslaşdırmaq üçün",
                            "Hash hesablamaq üçün"), 0, Difficulty.HARD),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Binary Search-ü sort olunmamış massivdə tətbiq etsək nə baş verir?",
                    List.of("Düzgün nəticə zəmanət edilmir", "Həmişə düzgün işləyir", "Xəta atılır", "Daha sürətli işləyir"),
                    0, Difficulty.MEDIUM),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Trie ağacında axtarışın zaman mürəkkəbliyi nəyə bağlıdır?",
                    List.of("Axtarılan sözün uzunluğuna", "Ağacdakı ümumi söz sayına", "Massivin ölçüsünə", "Heç nəyə"),
                    0, Difficulty.HARD),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Heap-də (min-heap) minimum elementə çıxış zaman mürəkkəbliyi nədir?",
                    List.of("O(1)", "O(log n)", "O(n)", "O(n²)"), 0, Difficulty.MEDIUM),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Tree-in 'height' (hündürlük) anlayışı nəyi ifadə edir?",
                    List.of("Kökdən ən uzaq leaf node-a qədər olan kənarların sayı", "Node-ların ümumi sayı", "Ağacın eni",
                            "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Pre-order traversal-da node-lar hansı ardıcıllıqla ziyarət olunur?",
                    List.of("Kök, sol, sağ", "Sol, kök, sağ", "Sol, sağ, kök", "Sağ, kök, sol"), 0, Difficulty.MEDIUM),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Post-order traversal-da node-lar hansı ardıcıllıqla ziyarət olunur?",
                    List.of("Sol, sağ, kök", "Kök, sol, sağ", "Sol, kök, sağ", "Sağ, sol, kök"), 0, Difficulty.MEDIUM),
            new Question("Axtarış Alqoritmləri və Ağaclar", "Java-da HashMap-də axtarışın orta hal zaman mürəkkəbliyi nədir?",
                    List.of("O(1)", "O(log n)", "O(n)", "O(n²)"), 0, Difficulty.MEDIUM),
            new Question("Axtarış Alqoritmləri və Ağaclar", "A* axtarış alqoritmi Dijkstra-dan nə ilə fərqlənir?",
                    List.of("Hədəfə doğru istiqamətlənmək üçün heuristika istifadə edir", "Fərq yoxdur",
                            "Heç vaxt heuristika istifadə etmir", "Yalnız balanslaşdırılmış ağaclarda işləyir"), 0, Difficulty.HARD),
            new Question("Axtarış Alqoritmləri və Ağaclar", "TreeSet/TreeMap-in daxili implementasiyası nəyə əsaslanır?",
                    List.of("Red-Black Tree", "Hash table", "Linked List", "Array"), 0, Difficulty.HARD)
    );

    public static List<Question> get() {
        return QUESTIONS;
    }
}
