package repository.bank;

import model.Difficulty;
import model.Question;

import java.util.List;

public class ConcurrencyJvmQuestions {

    private static final List<Question> QUESTIONS = List.of(
            new Question("Multithreading", "Java-da yeni thread yaratmağın neçə əsas yolu var?",
                    List.of("1", "2 (Thread sinifi və Runnable interfeysi)", "3", "4"), 1, Difficulty.EASY),
            new Question("Multithreading", "'synchronized' açar sözü nə üçün istifadə olunur?",
                    List.of("Kodu sürətləndirmək üçün", "Bir vaxtda yalnız bir thread-in bloka girməsini təmin etmək üçün",
                            "Yeni thread yaratmaq üçün", "Thread-i dayandırmaq üçün"), 1, Difficulty.MEDIUM),
            new Question("Multithreading", "Thread.sleep() metodu nə edir?",
                    List.of("Thread-i həmişəlik dayandırır", "Thread-i müəyyən müddətə pauza edir",
                            "Thread-i öldürür", "Yeni thread yaradır"), 1, Difficulty.EASY),
            new Question("Multithreading", "Deadlock nə deməkdir?",
                    List.of("Thread-lərin bir-birini gözləyərək sonsuz bloklanması", "Thread-in normal bitməsi",
                            "Thread-in sürətlə işləməsi", "Bir thread-in digərini yaratması"), 0, Difficulty.HARD),
            new Question("Multithreading", "wait() və sleep() metodları arasındakı fərq nədir?",
                    List.of("wait() monitoru buraxır, sleep() buraxmır", "Fərq yoxdur",
                            "sleep() monitoru buraxır", "wait() yalnız static metoddur"), 0, Difficulty.HARD),
            new Question("Multithreading", "ExecutorService nə üçün istifadə olunur?",
                    List.of("Thread-lərin pool şəklində idarə edilməsi üçün", "Yaddaşı təmizləmək üçün",
                            "Fayl oxumaq üçün", "Exception tutmaq üçün"), 0, Difficulty.MEDIUM),
            new Question("Multithreading", "Runnable və Callable arasındakı fərq nədir?",
                    List.of("Callable nəticə qaytara bilər və exception ata bilər, Runnable qaytara bilməz", "Fərq yoxdur",
                            "Runnable nəticə qaytarır", "Callable yalnız static-dir"), 0, Difficulty.MEDIUM),
            new Question("Multithreading", "Thread-safe kolleksiyaya nümunə göstərin.",
                    List.of("ArrayList", "HashMap", "ConcurrentHashMap", "LinkedList"), 2, Difficulty.MEDIUM),
            new Question("Multithreading", "volatile açar sözünün təyinatı nədir?",
                    List.of("Dəyişənin dəyərinin bütün thread-lər üçün həmişə yaddaşdan (cache-dən deyil) oxunmasını təmin edir",
                            "Dəyişəni final edir", "Thread yaradır", "Sinxronizasiya əvəz edir"), 0, Difficulty.HARD),
            new Question("Multithreading", "Thread pool-un istifadəsinin əsas üstünlüyü nədir?",
                    List.of("Hər tapşırıq üçün yeni thread yaratmaqdan qaçaraq resursları səmərəli idarə etmək",
                            "Kodu qısaltmaq", "Yaddaşı artırmaq", "Heç bir üstünlüyü yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Multithreading", "Java-da Thread-in start() və run() metodları arasındakı fərq nədir?",
                    List.of("start() yeni thread yaradıb run()-u çağırır, run() isə sadəcə metodu cari thread-də icra edir",
                            "Fərq yoxdur", "run() yeni thread yaradır", "start() yalnız static-dir"), 0, Difficulty.MEDIUM),
            new Question("Multithreading", "Java Memory Model (JMM) nəyi təmin edir?",
                    List.of("Çoxsaylı thread-lər arasında yaddaşa giriş qaydalarını və görünürlüyü müəyyən edir",
                            "Yalnız Heap ölçüsünü müəyyən edir", "Thread yaratmağı qadağan edir", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Multithreading", "Daemon thread nədir?",
                    List.of("Arxa planda işləyən, əsas thread-lər bitdikdə avtomatik dayanan thread", "Əsas thread",
                            "Ölümsüz thread", "Heç bir xüsusiyyəti olmayan thread"), 0, Difficulty.MEDIUM),
            new Question("Multithreading", "synchronized metod ilə synchronized blok arasındakı fərq nədir?",
                    List.of("Blok daha dəqiq (kiçik əhatəli) sinxronizasiyaya imkan verir", "Fərq yoxdur",
                            "Metod daha sürətlidir həmişə", "Blok yalnız static metodlarda işləyir"), 0, Difficulty.MEDIUM),
            new Question("Multithreading", "interrupt() metodu thread-ə nə edir?",
                    List.of("Thread-ə kəsilmə siqnalı göndərir, thread özü buna reaksiya verməlidir", "Thread-i dərhal öldürür",
                            "Thread-i pauza edir", "Heç nə etmir"), 0, Difficulty.MEDIUM),
            new Question("Multithreading", "Livelock nə deməkdir?",
                    List.of("Thread-lərin bir-birinə cavab olaraq daim vəziyyət dəyişdirməsi, amma irəliləməməsi", "Deadlock-un digər adı",
                            "Thread-in normal işləməsi", "Heç bir problem deyil"), 0, Difficulty.HARD),
            new Question("Multithreading", "Starvation (thread aclığı) nə deməkdir?",
                    List.of("Bir thread-in resurslara çıxışı davamlı olaraq başqa thread-lər tərəfindən əngəllənməsi", "Thread-in tamamlanması",
                            "Yaddaşın bitməsi", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("Multithreading", "Thread sinifinin setPriority() metodu nəyə təsir edir?",
                    List.of("Thread-in planlaşdırıcı (scheduler) tərəfindən nisbi icra üstünlüyünə (JVM/OS-dən asılı)", "Thread-in adına",
                            "Thread-in ID-sinə", "Heç nəyə"), 0, Difficulty.MEDIUM),
            new Question("Multithreading", "join() metodu nə edir?",
                    List.of("Cari thread-i çağırılan thread-in bitməsini gözləməyə məcbur edir", "İki thread-i birləşdirir",
                            "Yeni thread yaradır", "Thread-i öldürür"), 0, Difficulty.MEDIUM),
            new Question("Multithreading", "Java-da 'happens-before' münasibəti nəyi təmin edir?",
                    List.of("Bir əməliyyatın nəticələrinin digər thread-lər tərəfindən görünəcəyinə zəmanət verir", "Kodun sürətini artırır",
                            "Thread-i dayandırır", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),

            new Question("Concurrency Alətləri", "AtomicInteger sinifinin məqsədi nədir?",
                    List.of("Sinxronizasiya olmadan thread-safe atomik əməliyyatlar aparmaq", "İnteger-i sabit etmək",
                            "Yalnız oxumaq üçün istifadə olunur", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "CountDownLatch nə üçün istifadə olunur?",
                    List.of("Bir və ya bir neçə thread-in digər thread-lərin tamamlanmasını gözləməsi üçün", "Thread-i öldürmək üçün",
                            "Yaddaşı təmizləmək üçün", "Exception tutmaq üçün"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "Semaphore nə edir?",
                    List.of("Bir resursa eyni anda çıxış edə bilən thread sayını məhdudlaşdırır", "Thread yaradır",
                            "Yaddaşı artırır", "Exception atır"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "Future interfeysi nə üçün istifadə olunur?",
                    List.of("Asinxron hesablamanın nəticəsini gələcəkdə əldə etmək üçün", "Keçmiş nəticələri saxlamaq üçün",
                            "Thread-i dayandırmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "ReentrantLock, synchronized açar sözündən nə ilə fərqlənir?",
                    List.of("Daha çevikdir — tryLock, fairness və interrupt dəstəyi verir", "Fərq yoxdur",
                            "Daha yavaşdır həmişə", "synchronized-dan daha az təhlükəsizdir"), 0, Difficulty.HARD),
            new Question("Concurrency Alətləri", "CyclicBarrier və CountDownLatch arasındakı fərq nədir?",
                    List.of("CyclicBarrier təkrar istifadə oluna bilər, CountDownLatch bir dəfəlikdir", "Fərq yoxdur",
                            "CountDownLatch təkrar istifadə olunur", "CyclicBarrier yalnız bir thread üçündür"), 0, Difficulty.HARD),
            new Question("Concurrency Alətləri", "ThreadLocal nə üçün istifadə olunur?",
                    List.of("Hər thread üçün ayrıca dəyişən nüsxəsi saxlamaq üçün", "Bütün thread-lər arasında ortaq dəyişən üçün",
                            "Thread yaratmaq üçün", "Exception tutmaq üçün"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "Fork/Join Framework nə üçün nəzərdə tutulub?",
                    List.of("Böyük tapşırıqları kiçik hissələrə bölüb paralel icra etmək üçün", "Fayl oxumaq üçün",
                            "Verilənlər bazası üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Concurrency Alətləri", "BlockingQueue nə edir?",
                    List.of("Növbə boş və ya dolu olduqda thread-i bloklayır (producer-consumer modeli üçün)", "Elementləri sıralayır",
                            "Yalnız oxumaq üçündür", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "Race condition nə deməkdir?",
                    List.of("Bir neçə thread paylaşılan data-nı sinxronizasiya olmadan dəyişdirdikdə yaranan gözlənilməz nəticə",
                            "Thread-lərin sürət yarışı", "Proqramın sürətlə işləməsi", "Heç bir problem deyil"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "CompletionService nə üçün istifadə olunur?",
                    List.of("Bir neçə asinxron tapşırığın nəticələrini tamamlanma ardıcıllığı ilə əldə etmək üçün", "Thread yaratmaq üçün",
                            "Yaddaşı təmizləmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Concurrency Alətləri", "StampedLock, ReentrantReadWriteLock-dan nə ilə fərqlənir?",
                    List.of("Optimistic read dəstəkləyərək daha yüksək performans verə bilər", "Fərq yoxdur",
                            "Daha yavaşdır həmişə", "Yalnız yazma üçündür"), 0, Difficulty.HARD),
            new Question("Concurrency Alətləri", "ExecutorService-in shutdown() və shutdownNow() metodları arasındakı fərq nədir?",
                    List.of("shutdown() mövcud tapşırıqların bitməsini gözləyir, shutdownNow() dərhal dayandırmağa çalışır", "Fərq yoxdur",
                            "shutdownNow() yalnız pauza edir", "shutdown() dərhal dayandırır"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "CopyOnWriteArrayList nə vaxt effektivdir?",
                    List.of("Oxumaların yazmalardan çox olduğu, az dəyişən siyahılarda", "Tez-tez yazılan siyahılarda",
                            "Heç vaxt effektiv deyil", "Yalnız tək thread-li mühitdə"), 0, Difficulty.HARD),
            new Question("Concurrency Alətləri", "Executors.newFixedThreadPool() nə yaradır?",
                    List.of("Sabit sayda thread-dən ibarət thread pool", "Sonsuz thread pool", "Yalnız bir thread", "Heç nə yaratmır"),
                    0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "AtomicReference nə üçün istifadə olunur?",
                    List.of("Obyekt referenslarını atomik, thread-safe şəkildə yeniləmək üçün", "Yalnız primitiv tiplər üçün",
                            "Thread yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "compareAndSet() (CAS) əməliyyatı nəyi təmin edir?",
                    List.of("Dəyəri yalnız gözlənilən köhnə dəyərlə uyğun olduqda atomik şəkildə yeniləmək", "Həmişə uğurlu yeniləmə",
                            "Thread-i dayandırmaq", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Concurrency Alətləri", "ScheduledExecutorService nə üçün istifadə olunur?",
                    List.of("Tapşırıqları gecikmə ilə və ya müəyyən intervallarla təkrar icra etmək üçün", "Yalnız bir dəfə icra üçün",
                            "Yaddaşı idarə etmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Concurrency Alətləri", "Phaser sinifi nə üçün istifadə olunur?",
                    List.of("CountDownLatch və CyclicBarrier-in daha çevik, dinamik iştirakçı sayına malik alternativi kimi mərhələli sinxronizasiya üçün",
                            "Thread yaratmaq üçün", "Yaddaşı təmizləmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Concurrency Alətləri", "Immutable obyektlərin concurrency-də üstünlüyü nədir?",
                    List.of("Dəyişməz olduqları üçün əlavə sinxronizasiya tələb etmədən thread-lər arasında təhlükəsiz paylaşıla bilərlər",
                            "Heç bir üstünlüyü yoxdur", "Daha yavaşdırlar", "Yalnız tək thread üçün uyğundurlar"), 0, Difficulty.MEDIUM),

            new Question("JVM və Yaddaş", "Garbage Collector-un vəzifəsi nədir?",
                    List.of("Kodu compile etmək", "İstifadə olunmayan obyektləri yaddaşdan silmək",
                            "Thread-ləri idarə etmək", "Faylları oxumaq"), 1, Difficulty.EASY),
            new Question("JVM və Yaddaş", "Java-da 'Heap' yaddaşı nə üçün istifadə olunur?",
                    List.of("Statik dəyişənlər üçün", "Obyektlərin saxlanması üçün",
                            "Metod çağırışları üçün", "Yalnız primitivlər üçün"), 1, Difficulty.MEDIUM),
            new Question("JVM və Yaddaş", "JVM, JRE və JDK arasındakı fərq nədir?",
                    List.of("Eynidir", "JDK development üçün, JRE işə salma üçün, JVM bytecode icrası üçündür",
                            "JVM yalnız compile edir", "JRE yalnız development üçündür"), 1, Difficulty.MEDIUM),
            new Question("JVM və Yaddaş", "'static' açar sözü ilə elan olunan dəyişən nəyə aiddir?",
                    List.of("Yalnız bir obyektə", "Sinifin özünə, bütün obyektlər üçün ortaqdır",
                            "Yalnız local metoda", "Heç nəyə"), 1, Difficulty.EASY),
            new Question("JVM və Yaddaş", "Stack yaddaşında nə saxlanılır?",
                    List.of("Obyektlər", "Metod çağırışları və lokal dəyişənlər",
                            "Statik dəyişənlər", "Class faylları"), 1, Difficulty.EASY),
            new Question("JVM və Yaddaş", "'final' açar sözü dəyişənə tətbiq edildikdə nə deməkdir?",
                    List.of("Dəyişənin dəyəri bir dəfə təyin edildikdən sonra dəyişdirilə bilməz",
                            "Dəyişən yalnız static olur", "Dəyişən yalnız private olur", "Heç nə demək deyil"),
                    0, Difficulty.EASY),
            new Question("JVM və Yaddaş", "Memory leak Java-da necə baş verə bilər?",
                    List.of("Java-da memory leak mümkün deyil", "İstifadə olunmayan obyektlərə hələ də referans saxlanıldıqda GC onları təmizləyə bilmir",
                            "Yalnız native kodda olur", "Yalnız Stack-də olur"), 1, Difficulty.HARD),
            new Question("JVM və Yaddaş", "Classloader-in vəzifəsi nədir?",
                    List.of(".class fayllarını yaddaşa yükləmək", "Kodu compile etmək",
                            "Thread yaratmaq", "Faylları oxumaq"), 0, Difficulty.MEDIUM),
            new Question("JVM və Yaddaş", "JIT (Just-In-Time) compiler nə edir?",
                    List.of("Bytecode-u runtime-da native maşın koduna çevirərək performansı artırır", "Kodu yalnız compile zamanı yoxlayır",
                            "Yaddaşı təmizləyir", "Thread yaradır"), 0, Difficulty.HARD),
            new Question("JVM və Yaddaş", "Metaspace (Java 8+) nə üçün istifadə olunur?",
                    List.of("Sinif metadata-sının saxlanması üçün (əvvəlki PermGen-in əvəzi)", "Obyektlərin saxlanması üçün",
                            "Lokal dəyişənlər üçün", "Thread stack-i üçün"), 0, Difficulty.HARD),
            new Question("JVM və Yaddaş", "Young Generation və Old Generation Heap-də nəyi təmsil edir?",
                    List.of("Young — yeni yaradılan obyektlər, Old — uzun müddət yaşayan obyektlər", "Fərq yoxdur",
                            "Young — statik dəyişənlər", "Old — yalnız stringlər"), 0, Difficulty.HARD),
            new Question("JVM və Yaddaş", "Minor GC və Major (Full) GC arasındakı fərq nədir?",
                    List.of("Minor GC Young Generation-ı, Major GC bütün Heap-i təmizləyir", "Fərq yoxdur",
                            "Major GC daha sürətlidir", "Minor GC bütün Heap-i təmizləyir"), 0, Difficulty.HARD),
            new Question("JVM və Yaddaş", "-Xmx JVM parametri nəyi təyin edir?",
                    List.of("Maksimum Heap ölçüsünü", "Minimum Heap ölçüsünü", "Thread sayını", "Stack ölçüsünü"), 0, Difficulty.MEDIUM),
            new Question("JVM və Yaddaş", "OutOfMemoryError nə vaxt yaranır?",
                    List.of("JVM-ə lazımi yaddaşı ayıra bilmədikdə (Heap dolduqda)", "Kodda sintaksis xətası olduqda",
                            "Fayl tapılmadıqda", "Heç vaxt"), 0, Difficulty.EASY),
            new Question("JVM və Yaddaş", "Java-da 'escape analysis' nə edir?",
                    List.of("Obyektin yalnız bir metod daxilində istifadə olunduğunu aşkarlayaraq onu Heap əvəzinə Stack-də ayıra bilər (optimallaşdırma)",
                            "Yaddaşı sızdırır", "Thread yaradır", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("JVM və Yaddaş", "String Pool hansı yaddaş sahəsində saxlanılır (Java 7+)?",
                    List.of("Heap (əvvəllər PermGen-də idi)", "Stack", "Metaspace", "Register"), 0, Difficulty.HARD),
            new Question("JVM və Yaddaş", "GC 'stop-the-world' pauzası nə deməkdir?",
                    List.of("Garbage Collection zamanı bütün tətbiq thread-lərinin müvəqqəti dayandırılması", "Proqramın tam dayanması",
                            "JVM-in çökməsi", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JVM və Yaddaş", "G1 Garbage Collector-in əsas məqsədi nədir?",
                    List.of("Böyük Heap-lərdə pauza müddətlərini proqnozlaşdırıla bilən şəkildə minimuma endirmək", "Yalnız kiçik tətbiqlər üçündür",
                            "Heç bir üstünlüyü yoxdur", "Yalnız test mühiti üçündür"), 0, Difficulty.HARD),
            new Question("JVM və Yaddaş", "Java-da soft reference, weak reference və phantom reference-lərin əsas fərqi nədir?",
                    List.of("Onların Garbage Collector tərəfindən nə vaxt təmizlənə biləcəyi qaydası (əlçatanlıq gücü) fərqlidir",
                            "Fərq yoxdur", "Hamısı eyni davranır", "Yalnız adları fərqlidir"), 0, Difficulty.HARD),
            new Question("JVM və Yaddaş", "Java-da 'compact strings' (Java 9+) optimizasiyası nə edir?",
                    List.of("Latin-1 simvollardan ibarət string-ləri UTF-16 əvəzinə byte array kimi saxlayaraq yaddaşa qənaət edir",
                            "String-ləri sıxışdırır (compress)", "String Pool-u silir", "Heç bir təsiri yoxdur"), 0, Difficulty.HARD),

            new Question("JVM Performans Tənzimləmə", "JVM performans tənzimləməsinin əsas məqsədi nədir?",
                    List.of("Tətbiqin cavab müddətini, throughput-u və resurs istifadəsini optimallaşdırmaq", "Kodu daha uzun etmək",
                            "Yalnız Heap-i böyütmək", "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("JVM Performans Tənzimləmə", "-Xms və -Xmx parametrlərini eyni dəyərə təyin etməyin faydası nədir?",
                    List.of("Heap-in dinamik ölçü dəyişməsindən qaynaqlanan overhead-i azaldır", "Heç bir faydası yoxdur",
                            "Yaddaşı azaldır", "JVM-i sürətlə bağlayır"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "JVM profiling alətləri (məs. JProfiler, VisualVM) nə üçün istifadə olunur?",
                    List.of("CPU, yaddaş istifadəsini və performans darboğazlarını analiz etmək üçün", "Kodu compile etmək üçün",
                            "Test yazmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "Thread dump nədir?",
                    List.of("Müəyyən andakı bütün thread-lərin vəziyyətinin görüntüsü, deadlock/performans analizi üçün", "Yaddaş görüntüsü",
                            "Fayl backup-ı", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "Heap dump nə üçün istifadə olunur?",
                    List.of("Memory leak-ləri analiz etmək üçün Heap-in müəyyən andakı vəziyyətini saxlamaq", "CPU istifadəsini ölçmək üçün",
                            "Kodu debug etmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "JVM warm-up nə deməkdir?",
                    List.of("JIT compiler-in tez-tez icra olunan kodu optimallaşdırması üçün lazım olan ilkin icra müddəti", "JVM-in başlanğıc vaxtı",
                            "Yaddaşın doldurulması", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "Hansı JVM parametri GC alqoritmini seçmək üçün istifadə olunur?",
                    List.of("-XX:+UseG1GC kimi parametrlər", "-Xmx", "-classpath", "-version"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "Throughput və latency arasındakı fərq performans tənzimləməsində nədir?",
                    List.of("Throughput ümumi emal həcmi, latency isə tək sorğunun cavab müddətidir", "Fərq yoxdur",
                            "Eyni şeydir", "Latency ümumi həcmdir"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "JMH (Java Microbenchmark Harness) nə üçün istifadə olunur?",
                    List.of("Java kodunun performansını dəqiq və etibarlı şəkildə ölçmək üçün", "UI test etmək üçün",
                            "Kodu compile etmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "JVM-də 'GC pause time' niyə vacibdir izləmək üçün?",
                    List.of("Uzun pauzalar tətbiqin cavab müddətinə mənfi təsir göstərə bilər", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız test mühitində əhəmiyyətlidir", "Pauzalar həmişə faydalıdır"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "Object pooling nə vaxt performans üçün faydalı ola bilər?",
                    List.of("Obyekt yaratmaq/silmək baha olduqda (məs. connection-lar)", "Həmişə", "Heç vaxt", "Yalnız kiçik obyektlər üçün"),
                    0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "CPU profiling ilə memory profiling arasındakı fərq nədir?",
                    List.of("CPU profiling vaxt sərfini, memory profiling yaddaş istifadəsini analiz edir", "Fərq yoxdur",
                            "Eyni məlumatı verir", "Heç bir fərqi yoxdur"), 0, Difficulty.EASY),
            new Question("JVM Performans Tənzimləmə", "String konkatenasiyası dövrədə (loop) niyə performans problemi yarada bilər?",
                    List.of("Hər '+' əməliyyatı yeni String obyekti yaradır (immutable olduğu üçün)", "Heç bir problem yaratmır",
                            "StringBuilder-dən sürətlidir", "Yalnız kiçik dövrələrdə problem yaradır"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "Lazy initialization performans baxımından nə üçün faydalı ola bilər?",
                    List.of("Resurs yalnız faktiki lazım olduqda yaradılır, gərəksiz işi azaldır", "Heç bir faydası yoxdur",
                            "Həmişə yavaşladır", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "Autoboxing/unboxing performans baxımından niyə diqqətlə istifadə edilməlidir?",
                    List.of("Gizli obyekt yaratma və unpacking overhead-i yarada bilər, xüsusən dövrələrdə", "Heç bir təsiri yoxdur",
                            "Həmişə sürətləndirir", "Yalnız String üçün aiddir"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "JVM-də Just-In-Time (JIT) compilation-un tier səviyyələri nəyi ifadə edir?",
                    List.of("Kodun icra tezliyinə görə tədricən daha aqressiv optimallaşdırma mərhələləri", "Yaddaş səviyyələri",
                            "Thread prioritet səviyyələri", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("JVM Performans Tənzimləmə", "Connection pooling performansa necə kömək edir?",
                    List.of("Bahalı bağlantı yaratma əməliyyatını azaldaraq mövcud bağlantıları təkrar istifadə edir", "Heç bir köməyi yoxdur",
                            "Yalnız test mühiti üçündür", "Yaddaşı artırır"), 0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "Hansı vasitə ilə production mühitində canlı JVM-ə qoşulub metrikaları izləmək olar?",
                    List.of("JMX (Java Management Extensions)", "Yalnız log faylları", "Yalnız debugger", "Heç bir vasitə yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("JVM Performans Tənzimləmə", "Excessive logging performansa necə təsir edə bilər?",
                    List.of("I/O əməliyyatları və sinxronizasiya səbəbindən gecikmə yarada bilər", "Heç bir təsiri yoxdur",
                            "Həmişə sürətləndirir", "Yalnız yaddaşı azaldır"), 0, Difficulty.EASY),
            new Question("JVM Performans Tənzimləmə", "Performans tənzimləməsində 'premature optimization' nəyə görə riskli sayılır?",
                    List.of("Real darboğazlar məlum olmadan edilən optimallaşdırma kodun mürəkkəbliyini artıra, faydasız ola bilər",
                            "Həmişə faydalıdır", "Heç bir riski yoxdur", "Yalnız yeni layihələrdə riskli olur"), 0, Difficulty.MEDIUM),

            new Question("Alqoritmlər və Mürəkkəblik", "Big-O notasiyası nəyi ifadə edir?",
                    List.of("Alqoritmin ən pis halda zaman/yer mürəkkəbliyinin yuxarı sərhədini", "Alqoritmin dəqiq icra vaxtını",
                            "Kodun sətir sayını", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Alqoritmlər və Mürəkkəblik", "O(1) mürəkkəblik nə deməkdir?",
                    List.of("Sabit vaxt — giriş ölçüsündən asılı olmayan icra müddəti", "Xətti vaxt", "Loqarifmik vaxt", "Kvadratik vaxt"),
                    0, Difficulty.EASY),
            new Question("Alqoritmlər və Mürəkkəblik", "O(n) mürəkkəblik nəyə uyğundur?",
                    List.of("Xətti axtarış kimi, giriş ölçüsü ilə düz mütənasib icra müddəti", "Sabit vaxt", "Loqarifmik vaxt", "Eksponensial vaxt"),
                    0, Difficulty.EASY),
            new Question("Alqoritmlər və Mürəkkəblik", "O(n²) mürəkkəblik ən çox hansı ssenaridə rast gəlinir?",
                    List.of("İç-içə dövrələrdə (məs. nested loop ilə massiv müqayisəsi)", "Tək dövrədə", "Sabit əməliyyatlarda", "Heç vaxt"),
                    0, Difficulty.EASY),
            new Question("Alqoritmlər və Mürəkkəblik", "Space complexity (yer mürəkkəbliyi) nəyi ölçür?",
                    List.of("Alqoritmin istifadə etdiyi əlavə yaddaş miqdarını", "İcra vaxtını", "Kod sətir sayını", "Heç nəyi"),
                    0, Difficulty.EASY),
            new Question("Alqoritmlər və Mürəkkəblik", "Amortized analysis nə deməkdir?",
                    List.of("Bir sıra əməliyyatların orta xərcinin hesablanması (ən pis tək əməliyyat deyil)", "Yalnız ən pis halın hesablanması",
                            "Yalnız ən yaxşı halın hesablanması", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("Alqoritmlər və Mürəkkəblik", "Recursive alqoritmin zaman mürəkkəbliyini analiz etmək üçün hansı üsul istifadə olunur?",
                    List.of("Recurrence relation (rekursiya münasibəti) və Master Theorem", "Yalnız test etmək",
                            "Heç bir üsul yoxdur", "Yalnız empirik ölçmə"), 0, Difficulty.HARD),
            new Question("Alqoritmlər və Mürəkkəblik", "Dynamic Programming (dinamik proqramlaşdırma) nə üçün istifadə olunur?",
                    List.of("Alt-problemləri yadda saxlayaraq (memoization) təkrar hesablamaların qarşısını almaq üçün", "Yalnız sıralama üçün",
                            "Yalnız qraf üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Alqoritmlər və Mürəkkəblik", "Greedy alqoritm strategiyası nəyə əsaslanır?",
                    List.of("Hər addımda lokal optimal seçim etmək, qlobal optimallığa ümid edərək", "Bütün variantları yoxlamaq",
                            "Təsadüfi seçim etmək", "Heç bir strategiyası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Alqoritmlər və Mürəkkəblik", "Best case, average case və worst case mürəkkəblik nəyi ifadə edir?",
                    List.of("Alqoritmin müxtəlif giriş ssenarilərində göstərdiyi fərqli performansı", "Eyni şeydir",
                            "Yalnız worst case əhəmiyyətlidir həmişə", "Heç bir fərqi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Alqoritmlər və Mürəkkəblik", "O(log n) mürəkkəblik tipik olaraq hansı alqoritmlərdə rast gəlinir?",
                    List.of("Binary Search kimi hər addımda problemi yarıya bölən alqoritmlərdə", "Xətti axtarışda", "Bubble sort-da", "Heç bir yerdə"),
                    0, Difficulty.EASY),
            new Question("Alqoritmlər və Mürəkkəblik", "NP-complete problem nə deməkdir?",
                    List.of("Həlli sürətli yoxlanıla bilən, amma effektiv (polynomial vaxtda) həll alqoritmi məlum olmayan problem sinfi",
                            "Həmişə sürətlə həll oluna bilən problem", "Həll edilə bilməyən problem", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("Alqoritmlər və Mürəkkəblik", "Memoization nə deməkdir?",
                    List.of("Bahalı funksiya çağırışlarının nəticələrini keşləyərək təkrar hesablamanın qarşısını almaq", "Yaddaşı silmək",
                            "Kodu sadələşdirmək", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Alqoritmlər və Mürəkkəblik", "İki alqoritmin O(n) və O(n log n) mürəkkəbliyi arasında böyük n üçün hansı daha sürətlidir?",
                    List.of("O(n)", "O(n log n)", "Fərq yoxdur", "Giriş tipindən asılıdır həmişə"), 0, Difficulty.MEDIUM),
            new Question("Alqoritmlər və Mürəkkəblik", "Divide and Conquer (böl və hökm sür) strategiyasının üç əsas addımı hansılardır?",
                    List.of("Böl, həll et, birləşdir (Divide, Conquer, Combine)", "Yalnız böl", "Yalnız birləşdir", "Heç bir addımı yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("Alqoritmlər və Mürəkkəblik", "Backtracking alqoritmi nə vaxt istifadə olunur?",
                    List.of("Bütün mümkün həlləri sınayıb uyğun olmayanları geri qaytararaq axtarmaq lazım olduqda (məs. N-Queens)",
                            "Yalnız sıralama üçün", "Yalnız axtarış üçün", "Heç vaxt istifadə olunmur"), 0, Difficulty.MEDIUM),
            new Question("Alqoritmlər və Mürəkkəblik", "Two Pointer texnikası hansı problemlərdə tez-tez istifadə olunur?",
                    List.of("Sıralanmış massivdə cüt/aralıq axtarışı kimi problemlərdə", "Yalnız qraf problemlərində",
                            "Yalnız string şifrələməsində", "Heç bir yerdə"), 0, Difficulty.MEDIUM),
            new Question("Alqoritmlər və Mürəkkəblik", "Sliding Window texnikası nəyi optimallaşdırır?",
                    List.of("Ardıcıl alt-massiv/alt-string üzərində hesablamaları O(n)-ə endirir, təkrar hesablamanın qarşısını alaraq",
                            "Yalnız sıralama sürətini", "Yaddaş ölçüsünü həmişə artırır", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Alqoritmlər və Mürəkkəblik", "Big-O, Big-Theta və Big-Omega arasındakı fərq nədir?",
                    List.of("Big-O yuxarı sərhəd, Big-Omega aşağı sərhəd, Big-Theta hər ikisini (sıx sərhəd) ifadə edir", "Hamısı eynidir",
                            "Yalnız worst case üçündür hamısı", "Heç bir fərqi yoxdur"), 0, Difficulty.HARD),
            new Question("Alqoritmlər və Mürəkkəblik", "Alqoritm mürəkkəbliyini qiymətləndirərkən niyə sabitlər (constants) adətən nəzərə alınmır?",
                    List.of("Böyük giriş ölçülərində böyümə tendensiyası sabitlərdən daha vacibdir", "Sabitlər həmişə sıfırdır",
                            "Sabitlər ən vacib amildir", "Heç bir səbəb yoxdur"), 0, Difficulty.MEDIUM)
    );

    public static List<Question> get() {
        return QUESTIONS;
    }
}
