package repository.bank;

import model.Difficulty;
import model.Question;

import java.util.List;

public class CoreOopQuestions {

    private static final List<Question> QUESTIONS = List.of(
            new Question("OOP", "Java-da hansı açar söz bir sinifin başqa sinifdən miras almasını təmin edir?",
                    List.of("implements", "extends", "inherits", "super"), 1, Difficulty.EASY),
            new Question("OOP", "Aşağıdakılardan hansı Java-da çoxvarislik (multiple inheritance) əldə etmək üçün istifadə olunur?",
                    List.of("Abstract class", "Interface", "Final class", "Static class"), 1, Difficulty.MEDIUM),
            new Question("OOP", "Encapsulation (inkapsulyasiya) nəyi ifadə edir?",
                    List.of("Kod təkrarının aradan qaldırılması", "Data və metodların bir sinif daxilində gizlədilməsi",
                            "Sinifin genişləndirilməsi", "Metodun overload edilməsi"), 1, Difficulty.EASY),
            new Question("OOP", "Java-da 'this' açar sözü nə üçün istifadə olunur?",
                    List.of("Statik dəyişənə müraciət üçün", "Cari obyektə istinad üçün",
                            "Valideyn sinifə müraciət üçün", "Yeni obyekt yaratmaq üçün"), 1, Difficulty.EASY),
            new Question("OOP", "Polymorphism (çoxformalılıq) Java-da necə əldə edilir?",
                    List.of("Yalnız inheritance ilə", "Method overloading və overriding ilə",
                            "Yalnız interface ilə", "Statik metodlarla"), 1, Difficulty.MEDIUM),
            new Question("OOP", "Abstract class ilə interface arasındakı əsas fərq nədir (Java 8-ə qədər)?",
                    List.of("Abstract class-da constructor ola bilməz",
                            "Interface-də yalnız abstract metodlar ola bilərdi, abstract class-da isə implementasiya edilmiş metodlar da ola bilər",
                            "Fərq yoxdur", "Interface-dən birbaşa obyekt yaratmaq olar"), 1, Difficulty.MEDIUM),
            new Question("OOP", "Constructor overloading nə deməkdir?",
                    List.of("Eyni sinifdə fərqli parametrlərlə bir neçə constructor olması", "Constructor-un override edilməsi",
                            "Yalnız bir constructor olması", "Constructor-un private olması"), 0, Difficulty.EASY),
            new Question("OOP", "Java-da 'super' açar sözü nə üçün istifadə olunur?",
                    List.of("Cari obyektə istinad üçün", "Valideyn sinifin constructor və ya metodlarına müraciət üçün",
                            "Statik metod çağırmaq üçün", "Yeni obyekt yaratmaq üçün"), 1, Difficulty.EASY),
            new Question("OOP", "Java-da 'instanceof' operatoru nə üçün istifadə olunur?",
                    List.of("Obyektin müəyyən tipdən olub-olmadığını yoxlamaq üçün", "Yeni obyekt yaratmaq üçün",
                            "Metodu overload etmək üçün", "Sinifi final etmək üçün"), 0, Difficulty.EASY),
            new Question("OOP", "Composition (kompozisiya) inheritance-dan nə ilə fərqlənir?",
                    List.of("Composition 'has-a', inheritance 'is-a' münasibətini ifadə edir", "Fərq yoxdur",
                            "Composition yalnız interfeyslərlə işləyir", "Inheritance daha çevikdir"), 0, Difficulty.MEDIUM),
            new Question("OOP", "Method overloading və method overriding arasındakı fərq nədir?",
                    List.of("Overloading eyni sinifdə eyni adlı, fərqli parametrli metodlar, overriding isə alt sinifdə valideyn metodun yenidən tərif edilməsidir",
                            "Fərq yoxdur", "Overriding compile-time-dadır", "Overloading runtime-dadır"), 0, Difficulty.EASY),
            new Question("OOP", "Java-da bütün siniflər hansı sinifdən miras alır?",
                    List.of("Object", "Class", "Main", "System"), 0, Difficulty.EASY),
            new Question("OOP", "Abstract metod nə deməkdir?",
                    List.of("Gövdəsi olmayan, alt sinif tərəfindən implementasiya edilməli olan metod", "Statik metod",
                            "Final metod", "Private metod"), 0, Difficulty.EASY),
            new Question("OOP", "Java-da 'final' sinif nə deməkdir?",
                    List.of("Sinif extend edilə bilməz", "Sinif abstrakt olur",
                            "Sinifdən obyekt yaradıla bilməz", "Sinif interfeys olur"), 0, Difficulty.EASY),
            new Question("OOP", "Interface-də default metod (Java 8+) nəyə imkan verir?",
                    List.of("İnterfeysdə implementasiya edilmiş metod yazmağa, mövcud implementasiyaları pozmadan",
                            "İnterfeysi final etməyə", "İnterfeysdən obyekt yaratmağa", "Heç nəyə"), 0, Difficulty.MEDIUM),
            new Question("OOP", "Aggregation və Composition arasındakı fərq nədir?",
                    List.of("Aggregation-da hissə valideyn obyektdən asılı olmadan mövcud ola bilər, Composition-da yox",
                            "Fərq yoxdur", "Composition daha zəif əlaqədir", "Aggregation yalnız interfeyslə işləyir"), 0, Difficulty.MEDIUM),
            new Question("OOP", "Java-da konstruktor override edilə bilərmi?",
                    List.of("Xeyr, konstruktorlar override edilmir, yalnız overload edilə bilər", "Bəli, həmişə",
                            "Yalnız abstract siniflərdə", "Yalnız static konstruktorlar"), 0, Difficulty.MEDIUM),
            new Question("OOP", "Static metod polymorphism-ə (runtime) tabedirmi?",
                    List.of("Xeyr, static metodlar compile-time-da həll olunur (method hiding)", "Bəli, tam tabedir",
                            "Yalnız private static-lər tabedir", "Heç bir əlaqəsi yoxdur"), 0, Difficulty.HARD),
            new Question("OOP", "Marker interface nədir (məs. Serializable)?",
                    List.of("Heç bir metodu olmayan, sinifə müəyyən davranış əlavə etmək üçün işarələmə xidməti görən interfeys",
                            "Yalnız bir metodu olan interfeys", "Abstract sinif", "Exception növü"), 0, Difficulty.MEDIUM),
            new Question("OOP", "Java-da 'protected' access modifier nəyə icazə verir?",
                    List.of("Yalnız eyni sinif daxilində", "Eyni paket və alt siniflər (fərqli paketdə olsa belə) üçün çıxış",
                            "Heç kimə", "Yalnız eyni fayl daxilində"), 1, Difficulty.MEDIUM),

            new Question("SOLID Prinsipləri", "Single Responsibility Principle (SRP) nəyi ifadə edir?",
                    List.of("Bir sinifin yalnız bir dəyişmə səbəbi olmalıdır", "Sinif çoxlu interfeys implementasiya etməlidir",
                            "Bir sinif yalnız bir metoda malik olmalıdır", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Open/Closed Principle nə deməkdir?",
                    List.of("Siniflər genişlənməyə açıq, dəyişikliyə qapalı olmalıdır", "Bütün siniflər final olmalıdır",
                            "Siniflər həmişə açıq (public) olmalıdır", "Heç bir əlaqəsi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Liskov Substitution Principle nəyi tələb edir?",
                    List.of("Alt sinif öz valideyn sinifinin yerinə istifadə oluna bilməlidir, davranışı pozmadan",
                            "Alt sinif valideyndən fərqli davranmalıdır", "İnterfeyslər əvəz oluna bilməz", "Heç bir mənası yoxdur"),
                    0, Difficulty.HARD),
            new Question("SOLID Prinsipləri", "Interface Segregation Principle nəyi tövsiyə edir?",
                    List.of("Böyük, hər şeyi əhatə edən interfeyslər yaratmaq",
                            "Klientlərin istifadə etmədiyi metodlara asılı olmamaq üçün kiçik, spesifik interfeyslər yaratmaq",
                            "Yalnız bir interfeys istifadə etmək", "İnterfeysləri ümumiyyətlə istifadə etməmək"), 1, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Dependency Inversion Principle nəyi ifadə edir?",
                    List.of("Yüksək səviyyəli modullar aşağı səviyyəli modullardan deyil, abstraksiyalardan asılı olmalıdır",
                            "Bütün siniflər bir-birindən asılı olmalıdır", "Asılılıqlar həmişə konkret siniflər olmalıdır",
                            "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("SOLID Prinsipləri", "SOLID prinsiplərinin əsas məqsədi nədir?",
                    List.of("Kodu daha çətin oxunan etmək", "Daha çevik, davamlı (maintainable) və genişlənə bilən kod yazmaq",
                            "Kodun sətir sayını artırmaq", "Yalnız performansı artırmaq"), 1, Difficulty.EASY),
            new Question("SOLID Prinsipləri", "SOLID-in 'S' hərfi nəyi bildirir?",
                    List.of("Simple", "Single Responsibility", "Static", "Secure"), 1, Difficulty.EASY),
            new Question("SOLID Prinsipləri", "Dependency Injection SOLID-in hansı prinsipi ilə birbaşa bağlıdır?",
                    List.of("Single Responsibility", "Open/Closed", "Dependency Inversion", "Liskov Substitution"),
                    2, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "SOLID-in 'O' hərfi hansı prinsipi bildirir?",
                    List.of("Open/Closed Principle", "Object Principle", "Optional Principle", "Override Principle"),
                    0, Difficulty.EASY),
            new Question("SOLID Prinsipləri", "Liskov Substitution Principle pozulduqda adətən nə baş verir?",
                    List.of("Alt sinif valideynin yerinə istifadə edildikdə gözlənilməz davranış yaranır", "Heç nə dəyişmir",
                            "Proqram sürətlənir", "Yaddaş azalır"), 0, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "SOLID-in 'I' hərfi hansı prinsipi bildirir?",
                    List.of("Interface Segregation Principle", "Inheritance Principle", "Immutability Principle", "Injection Principle"),
                    0, Difficulty.EASY),
            new Question("SOLID Prinsipləri", "SOLID-in 'L' hərfi hansı prinsipi bildirir?",
                    List.of("Liskov Substitution Principle", "Layer Principle", "Lazy Loading Principle", "Logic Principle"),
                    0, Difficulty.EASY),
            new Question("SOLID Prinsipləri", "SOLID-in 'D' hərfi hansı prinsipi bildirir?",
                    List.of("Dependency Inversion Principle", "Data Principle", "Design Principle", "Duplication Principle"),
                    0, Difficulty.EASY),
            new Question("SOLID Prinsipləri", "Open/Closed Principle-i həyata keçirmək üçün adətən hansı texnikadan istifadə olunur?",
                    List.of("Abstraction və polymorphism (interfeys/abstract sinif)", "Bütün metodları static etmək",
                            "Bütün sahələri public etmək", "Heç biri"), 0, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Single Responsibility Principle pozulduqda ən çox hansı problem yaranır?",
                    List.of("Sinif çox böyüyür və dəyişikliklərə həssas olur (God Class)", "Sinif çox kiçik olur",
                            "Performans artır", "Heç bir problem yaranmır"), 0, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Interface Segregation Principle-i pozan koda nümunə hansıdır?",
                    List.of("Klientin istifadə etmədiyi metodları implement etməyə məcbur edən 'fat interface'",
                            "Kiçik, spesifik interfeyslər", "Tək metodlu interfeys", "Heç biri"), 0, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "Dependency Inversion Principle-i tətbiq etmək üçün Spring-də nədən istifadə olunur?",
                    List.of("Dependency Injection (IoC konteyner)", "Static metodlar", "Reflection yalnız", "Heç nədən"),
                    0, Difficulty.MEDIUM),
            new Question("SOLID Prinsipləri", "SOLID prinsipləri hansı proqramlaşdırma paradiqmasına aiddir?",
                    List.of("Obyekt Yönümlü Proqramlaşdırma", "Funksional Proqramlaşdırma", "Procedural Proqramlaşdırma",
                            "Bütün paradiqmalara eyni dərəcədə"), 0, Difficulty.EASY),
            new Question("SOLID Prinsipləri", "Liskov Substitution Principle-i pozan tipik nümunə hansıdır?",
                    List.of("Alt sinifin valideyn metodun gözlənilən davranışını dəyişməsi (məs. gözlənilməz exception atması)",
                            "Alt sinifin əlavə metod əlavə etməsi", "Alt sinifin metodu override etməsi", "Heç biri"), 0, Difficulty.HARD),
            new Question("SOLID Prinsipləri", "SOLID prinsiplərini kim təklif edib?",
                    List.of("Robert C. Martin (Uncle Bob)", "James Gosling", "Martin Fowler", "Kent Beck"), 0, Difficulty.EASY),

            new Question("Dizayn Şablonları", "Singleton dizayn şablonu nəyi təmin edir?",
                    List.of("Bir sinifdən yalnız bir obyekt yaradılmasını", "Çoxlu obyekt yaradılmasını",
                            "Sinifin final olmasını", "İnterfeys yaradılmasını"), 0, Difficulty.EASY),
            new Question("Dizayn Şablonları", "Factory Method şablonunun məqsədi nədir?",
                    List.of("Obyekt yaratma məntiqini alt siniflərə həvalə etmək", "Obyektləri silmək",
                            "Thread yaratmaq", "Exception idarə etmək"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Observer dizayn şablonu nə üçün istifadə olunur?",
                    List.of("Bir obyektin vəziyyəti dəyişdikdə asılı obyektləri xəbərdar etmək üçün", "Obyektləri kopyalamaq üçün",
                            "Yaddaşı idarə etmək üçün", "Thread sinxronizasiyası üçün"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Builder dizayn şablonu hansı problemi həll edir?",
                    List.of("Çoxlu parametrli mürəkkəb obyektlərin addım-addım qurulması", "Obyektlərin silinməsi",
                            "Interfeyslərin birləşdirilməsi", "Thread-lərin idarə edilməsi"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Strategy dizayn şablonu nəyi təmin edir?",
                    List.of("Alqoritmləri runtime-da dəyişdirmək imkanı", "Sinifin tək instansiya olmasını",
                            "Obyektlərin klonlanmasını", "Yaddaşın azaldılmasını"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Decorator dizayn şablonu nə edir?",
                    List.of("Obyektə runtime-da əlavə funksionallıq qoşur, inheritance olmadan", "Obyekti silir",
                            "Yeni sinif yaradır", "Thread yaradır"), 0, Difficulty.HARD),
            new Question("Dizayn Şablonları", "Adapter dizayn şablonu nə üçün istifadə olunur?",
                    List.of("Uyğun olmayan interfeysləri bir-biri ilə işləməyə uyğunlaşdırmaq üçün", "Obyektləri sıralamaq üçün",
                            "Yaddaşı təmizləmək üçün", "Exception tutmaq üçün"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Dependency Injection dizayn şablonunun əsas faydası nədir?",
                    List.of("Siniflər arasında sıx bağlılığı (tight coupling) azaltmaq", "Kodu daha uzun etmək",
                            "Performansı azaltmaq", "Heç bir faydası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Facade dizayn şablonu nə edir?",
                    List.of("Mürəkkəb alt sistemə sadə interfeys təqdim edir", "Obyektləri klonlayır",
                            "Thread yaradır", "Exception tutur"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Command dizayn şablonu nəyi encapsulate edir?",
                    List.of("Bir sorğunu (request) obyekt kimi", "Yalnız data-nı", "Thread-i", "Exception-ı"),
                    0, Difficulty.HARD),
            new Question("Dizayn Şablonları", "Dizayn şablonları hansı üç əsas kateqoriyaya bölünür?",
                    List.of("Creational, Structural, Behavioral", "Static, Dynamic, Hybrid", "Simple, Complex, Advanced",
                            "Local, Global, Shared"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Prototype dizayn şablonu nə edir?",
                    List.of("Mövcud obyekti klonlayaraq yeni obyekt yaradır", "Yeni sinif yaradır", "Obyekti silir", "Thread yaradır"),
                    0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Proxy dizayn şablonu nə üçün istifadə olunur?",
                    List.of("Başqa obyektə giriş/çıxışı idarə etmək üçün ara vasitəçi təqdim etmək", "Obyektləri silmək üçün",
                            "Yeni thread yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Dizayn Şablonları", "Template Method dizayn şablonu nəyi təyin edir?",
                    List.of("Alqoritmin skeletini valideyn sinifdə, detalları isə alt sinifdə", "Yalnız bir metodu",
                            "Sinifin final olmasını", "Heç nəyi"), 0, Difficulty.HARD),
            new Question("Dizayn Şablonları", "Chain of Responsibility dizayn şablonu nə edir?",
                    List.of("Sorğunu bir sıra handler-lər boyunca ötürür, hər biri onu emal edə və ya ötürə bilər",
                            "Obyektləri klonlayır", "Thread yaradır", "Exception atır"), 0, Difficulty.HARD),
            new Question("Dizayn Şablonları", "State dizayn şablonu nə üçün istifadə olunur?",
                    List.of("Obyektin daxili vəziyyətindən asılı olaraq davranışını dəyişdirmək üçün", "Obyekti silmək üçün",
                            "Thread sinxronizasiyası üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Dizayn Şablonları", "Abstract Factory dizayn şablonu Factory Method-dan nə ilə fərqlənir?",
                    List.of("Əlaqəli obyekt ailələri yaradır, tək bir obyekt yaratmaqdan daha genişdir", "Fərq yoxdur",
                            "Yalnız bir obyekt yaradır", "Heç bir əlaqəsi yoxdur"), 0, Difficulty.HARD),
            new Question("Dizayn Şablonları", "Anti-pattern nə deməkdir?",
                    List.of("Ümumi problemə tez-tez rast gəlinən, lakin səmərəsiz və ya zərərli həll yolu", "Yaxşı dizayn nümunəsi",
                            "Test metodu", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Dizayn Şablonları", "Composite dizayn şablonu nə edir?",
                    List.of("Obyektləri ağac strukturunda təşkil edərək tək və mürəkkəb obyektlərlə eyni şəkildə işləməyə imkan verir",
                            "Obyektləri silir", "Thread yaradır", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Dizayn Şablonları", "Dizayn şablonlarından istifadənin əsas faydası nədir?",
                    List.of("Sınanmış, ümumi problemlərə hazır həll yollarını təmin edərək kommunikasiyanı asanlaşdırmaq",
                            "Kodu daha uzun etmək", "Performansı azaltmaq", "Heç bir faydası yoxdur"), 0, Difficulty.EASY),

            new Question("Object Sinifinin Metodları", "Java-da hər sinif hansı sinifin metodlarını irsən alır?",
                    List.of("Object", "Class", "System", "Runtime"), 0, Difficulty.EASY),
            new Question("Object Sinifinin Metodları", "equals() metodunu override edərkən hansı metodu da override etmək tövsiyə olunur?",
                    List.of("hashCode()", "toString()", "clone()", "finalize()"), 0, Difficulty.MEDIUM),
            new Question("Object Sinifinin Metodları", "hashCode() və equals() kontraktına görə, əgər iki obyekt equals() ilə bərabərdirsə, nə olmalıdır?",
                    List.of("Eyni hashCode() qaytarmalıdırlar", "Fərqli hashCode() qaytarmalıdırlar", "Heç bir tələb yoxdur",
                            "hashCode() çağırıla bilməz"), 0, Difficulty.MEDIUM),
            new Question("Object Sinifinin Metodları", "toString() metodunun default implementasiyası nə qaytarır?",
                    List.of("Sinif adı və hash kodunun hex görünüşü", "Boş string", "null", "Obyektin bütün sahələri"),
                    0, Difficulty.EASY),
            new Question("Object Sinifinin Metodları", "clone() metodunu istifadə etmək üçün sinif hansı interfeysi implement etməlidir?",
                    List.of("Cloneable", "Serializable", "Comparable", "Iterable"), 0, Difficulty.MEDIUM),
            new Question("Object Sinifinin Metodları", "getClass() metodu nə qaytarır?",
                    List.of("Obyektin runtime sinifini təmsil edən Class obyekti", "Sinifin adını String kimi",
                            "Obyektin hash kodunu", "Heç nə"), 0, Difficulty.EASY),
            new Question("Object Sinifinin Metodları", "equals() metodu override edilmədikdə default davranış nədir?",
                    List.of("Referensiya bərabərliyini yoxlayır (== kimi)", "Həmişə true qaytarır", "Həmişə false qaytarır",
                            "Exception atır"), 0, Difficulty.EASY),
            new Question("Object Sinifinin Metodları", "Niyə equals() metodunda 'instanceof' və ya getClass() müqayisəsi istifadə olunur?",
                    List.of("Parametrin düzgün tipdə olduğunu təhlükəsiz yoxlamaq üçün", "Performans üçün",
                            "Heç bir səbəb yoxdur", "Yalnız stil məsələsidir"), 0, Difficulty.MEDIUM),
            new Question("Object Sinifinin Metodları", "finalize() metodu nə üçün nəzərdə tutulmuşdu (indi deprecated)?",
                    List.of("Obyekt Garbage Collector tərəfindən silinmədən əvvəl təmizləmə əməliyyatı üçün", "Obyekti yaratmaq üçün",
                            "Obyekti klonlamaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Object Sinifinin Metodları", "Records (Java 14+) equals(), hashCode() və toString() metodlarını necə təmin edir?",
                    List.of("Avtomatik generasiya edir, komponentlərə əsasən", "Heç vaxt təmin etmir",
                            "Yalnız əl ilə yazılmalıdır", "Yalnız toString()-i avtomatik verir"), 0, Difficulty.MEDIUM),
            new Question("Object Sinifinin Metodları", "Object sinifinin wait(), notify(), notifyAll() metodları nə üçündür?",
                    List.of("Thread-lərarası sinxronizasiya və kommunikasiya üçün", "Obyekt yaratmaq üçün", "Exception tutmaq üçün",
                            "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Object Sinifinin Metodları", "İki obyektin '==' ilə bərabər olması nə deməkdir?",
                    List.of("Eyni yaddaş ünvanına (referensiyaya) işarə edirlər", "Eyni məzmuna malikdirlər",
                            "Eyni hashCode-a malikdirlər", "Heç nə demək deyil"), 0, Difficulty.EASY),
            new Question("Object Sinifinin Metodları", "Comparable interfeysindəki compareTo() metodu nəyi qaytarır?",
                    List.of("Mənfi, sıfır və ya müsbət tam ədəd, sıralama nəticəsinə görə", "Boolean", "String", "Heç nə"),
                    0, Difficulty.MEDIUM),
            new Question("Object Sinifinin Metodları", "Immutable sinifdə equals() və hashCode() niyə xüsusilə vacibdir (məs. HashMap açarı kimi istifadə üçün)?",
                    List.of("Obyekt dəyişmədiyi üçün hash dəyəri sabit qalır və kolleksiyalarda etibarlı işləyir", "Heç bir səbəb yoxdur",
                            "Yalnız performans üçün", "Yalnız stil üçün"), 0, Difficulty.MEDIUM),
            new Question("Object Sinifinin Metodları", "Object.equals() metodunun kontraktına aid olmayan xassə hansıdır?",
                    List.of("Reflexive", "Symmetric", "Transitive", "Mutable"), 3, Difficulty.MEDIUM),
            new Question("Object Sinifinin Metodları", "toString() metodunu override etməyin əsas faydası nədir?",
                    List.of("Obyektin oxunaqlı, mənalı string təsvirini vermək (debuq/log üçün)", "Performansı artırmaq",
                            "Yaddaşı azaltmaq", "Heç bir faydası yoxdur"), 0, Difficulty.EASY),
            new Question("Object Sinifinin Metodları", "Bir sinifi HashSet-də düzgün işlətmək üçün nəyi təmin etmək lazımdır?",
                    List.of("equals() və hashCode()-un düzgün və uyğun override edilməsini", "Yalnız toString()-i override etmək",
                            "Sinifi final etmək", "Heç nə etmək lazım deyil"), 0, Difficulty.MEDIUM),
            new Question("Object Sinifinin Metodları", "Records-un komponentləri (fields) default olaraq necədir?",
                    List.of("final (immutable)", "mutable", "static", "transient"), 0, Difficulty.MEDIUM),
            new Question("Object Sinifinin Metodları", "Object sinifinin hashCode() metodunun default implementasiyası nəyə əsaslanır (əksər JVM-lərdə)?",
                    List.of("Obyektin yaddaş ünvanı ilə əlaqəli daxili identifikator", "Obyektin sahələrinin məzmunu",
                            "Sinifin adı", "Həmişə 0 qaytarır"), 0, Difficulty.MEDIUM),
            new Question("Object Sinifinin Metodları", "Niyə mutable obyektləri HashMap açarı kimi istifadə etmək təhlükəlidir?",
                    List.of("Obyekt dəyişdikdə hashCode() dəyişə bilər və açar 'itə' bilər", "Heç bir təhlükə yoxdur",
                            "HashMap mutable açarlara icazə vermir", "Yalnız performans azalır"), 0, Difficulty.HARD),

            new Question("Immutability Dizaynı", "Immutable obyekt nə deməkdir?",
                    List.of("Yaradıldıqdan sonra vəziyyəti dəyişdirilə bilməyən obyekt", "Silinə bilməyən obyekt",
                            "Statik obyekt", "Final sinifdən yaradılan istənilən obyekt"), 0, Difficulty.EASY),
            new Question("Immutability Dizaynı", "Java-da immutable sinif yaratmaq üçün hansı addımlar tələb olunur?",
                    List.of("Sinifi final etmək, sahələri private final etmək, setter yazmamaq, mutable sahələri müdafiə edərək qaytarmaq",
                            "Yalnız sinifi final etmək", "Yalnız getter yazmaq", "Heç bir xüsusi addım lazım deyil"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Immutable obyektlərin thread-safety baxımından üstünlüyü nədir?",
                    List.of("Vəziyyət dəyişmədiyi üçün sinxronizasiyaya ehtiyac yoxdur", "Daha az yaddaş tuturlar",
                            "Daha sürətli yaradılırlar", "Heç bir üstünlüyü yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Defensive copy (müdafiə kopyası) nə üçün istifadə olunur?",
                    List.of("Immutable sinifdə mutable daxili obyektlərə (məs. List, Date) xarici dəyişikliyin qarşısını almaq üçün",
                            "Performansı artırmaq üçün", "Yaddaşı azaltmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Java-da hansı sinif immutable-un klassik nümunəsidir?",
                    List.of("String", "StringBuilder", "ArrayList", "HashMap"), 0, Difficulty.EASY),
            new Question("Immutability Dizaynı", "Immutable obyektlərin dezavantajı nə ola bilər?",
                    List.of("Hər dəyişiklikdə yeni obyekt yaratmaq lazım gəldiyi üçün yaddaş/performans xərci", "Heç bir dezavantajı yoxdur",
                            "Thread-safe deyillər", "Serializasiya oluna bilmirlər"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Java 16+ Record-lar niyə immutability üçün əlverişlidir?",
                    List.of("Komponentləri default olaraq final-dır və setter yaratmır", "Mutable-dirlər",
                            "Heç bir əlaqəsi yoxdur", "Yalnız static ola bilərlər"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Immutable sinifdə final açar sözünün rolu nədir?",
                    List.of("Sinifin extend edilməsinin qarşısını alaraq alt sinifin mutable davranış əlavə etməsini əngəlləmək",
                            "Performansı artırmaq", "Yaddaşı azaltmaq", "Heç bir rolu yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Builder pattern immutable obyektlərin yaradılmasında necə kömək edir?",
                    List.of("Çoxlu parametri addım-addım təyin edib sonda immutable obyekt yaratmağa imkan verir", "Obyekti mutable edir",
                            "Heç bir kömək etmir", "Yalnız sadə obyektlər üçündür"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Immutable kolleksiya yaratmaq üçün Java-da hansı metoddan istifadə olunur (Java 9+)?",
                    List.of("List.of(), Set.of(), Map.of()", "new ArrayList<>()", "Collections.mutableList()", "List.create()"),
                    0, Difficulty.EASY),
            new Question("Immutability Dizaynı", "Immutable obyektlər niyə HashMap açarı kimi ideal hesab olunur?",
                    List.of("hashCode() dəyəri obyektin ömrü boyu sabit qalır", "Daha az yer tuturlar",
                            "Daha sürətli oxunurlar", "Heç bir səbəb yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "'with' metodları (məs. withName()) immutable dizaynda nə üçün istifadə olunur?",
                    List.of("Orijinal obyekti dəyişmədən, dəyişdirilmiş sahə ilə yeni obyekt qaytarmaq üçün", "Obyekti silmək üçün",
                            "Yeni thread yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Immutability funksional proqramlaşdırma ilə necə əlaqəlidir?",
                    List.of("Funksional proqramlaşdırma yan-effektsiz, dəyişməz data ilə işləməyə üstünlük verir", "Heç bir əlaqəsi yoxdur",
                            "Əksinədir, funksional proqramlaşdırma mutable data tələb edir", "Yalnız Java-ya aiddir"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Enum-lar niyə təbii olaraq immutable-dır?",
                    List.of("Sabit, əvvəlcədən müəyyən edilmiş instansiyalar dəsti təmsil edirlər və dəyişdirilə bilməzlər",
                            "Heç bir səbəb yoxdur", "Yalnız final açar sözü ilə", "Mutable-dırlar əslində"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Immutable sinifdə array sahəsi olduqda hansı risk var?",
                    List.of("Array-in özü mutable-dır, referensiya immutable olsa da elementlər dəyişdirilə bilər", "Heç bir risk yoxdur",
                            "Array immutable-dır həmişə", "Yalnız performans riski"), 0, Difficulty.HARD),
            new Question("Immutability Dizaynı", "Immutability caching (keşləmə) üçün niyə faydalıdır?",
                    List.of("Dəyər dəyişmədiyi üçün nəticəni təhlükəsiz şəkildə yenidən istifadə etmək olar", "Heç bir faydası yoxdur",
                            "Keşləməni əngəlləyir", "Yalnız mutable data keşlənə bilər"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Java-da 'final' massiv (array) elan etmək massivin elementlərini immutable edirmi?",
                    List.of("Xeyr, yalnız referensiya dəyişdirilə bilməz, elementlər dəyişdirilə bilər", "Bəli, tam immutable edir",
                            "Massivi silinməz edir", "Heç bir təsiri yoxdur"), 0, Difficulty.HARD),
            new Question("Immutability Dizaynı", "Value Object (dəyər obyekti) konsepsiyası immutability ilə necə bağlıdır?",
                    List.of("Value Object-lər adətən immutable dizayn edilir, çünki kimliyi deyil, dəyəri əhəmiyyətlidir",
                            "Heç bir əlaqəsi yoxdur", "Value Object-lər həmişə mutable olmalıdır", "Yalnız Entity-lərə aiddir"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Immutable obyektlər arasında paylaşılan referanslar (sharing) niyə təhlükəsizdir?",
                    List.of("Heç bir tərəf obyektin vəziyyətini dəyişə bilməz, ona görə yan-effekt riski yoxdur", "Heç bir səbəb yoxdur",
                            "Paylaşma həmişə təhlükəlidir", "Yalnız bir thread istifadə etdikdə təhlükəsizdir"), 0, Difficulty.MEDIUM),
            new Question("Immutability Dizaynı", "Immutable dizaynın SOLID prinsipləri ilə əlaqəsi nədir?",
                    List.of("Sadə, proqnozlaşdırıla bilən davranışla Single Responsibility və etibarlılığı dəstəkləyir", "Heç bir əlaqəsi yoxdur",
                            "SOLID-ə ziddir", "Yalnız Liskov Substitution ilə bağlıdır"), 0, Difficulty.HARD)
    );

    public static List<Question> get() {
        return QUESTIONS;
    }
}
