package repository.bank;

import model.Difficulty;
import model.Question;

import java.util.List;

public class DatabaseQuestions {

    private static final List<Question> QUESTIONS = List.of(
            new Question("JDBC və Verilənlər Bazası", "JDBC nədir?",
                    List.of("Java-dan verilənlər bazasına qoşulmaq üçün standart API", "Java-nın test framework-ü",
                            "Yeni proqramlaşdırma dili", "Web server"), 0, Difficulty.EASY),
            new Question("JDBC və Verilənlər Bazası", "PreparedStatement, Statement-dən nə ilə fərqlənir?",
                    List.of("Parametrləşdirilmiş sorğulara imkan verir və SQL injection-a qarşı daha təhlükəsizdir", "Fərq yoxdur",
                            "Statement daha sürətlidir", "PreparedStatement yalnız SELECT üçündür"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "Connection Pool nə üçün istifadə olunur?",
                    List.of("Verilənlər bazası bağlantılarını təkrar istifadə edərək performansı artırmaq üçün", "Bağlantıları silmək üçün",
                            "Yalnız bir bağlantı yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "ORM (Object-Relational Mapping) nədir?",
                    List.of("Obyektləri verilənlər bazası cədvəlləri ilə uyğunlaşdıran texnika (məs. Hibernate)", "Yalnız SQL yazmaq üsulu",
                            "Test metodu", "Thread idarəetməsi"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "SQL injection həmləsindən qorunmaq üçün ən yaxşı üsul hansıdır?",
                    List.of("PreparedStatement/parametrləşdirilmiş sorğulardan istifadə etmək", "String birləşdirmə (concatenation) ilə sorğu qurmaq",
                            "Heç nə etməmək", "Yalnız Statement istifadə etmək"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "Transaction-un ACID xüsusiyyətləri nələrdir?",
                    List.of("Atomicity, Consistency, Isolation, Durability", "Access, Control, Isolation, Data",
                            "Atomic, Concurrent, Isolated, Distributed", "Heç biri"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "ResultSet nədir?",
                    List.of("SQL sorğusunun nəticəsini təmsil edən obyekt", "Verilənlər bazası bağlantısı",
                            "SQL sorğusunun özü", "Exception növü"), 0, Difficulty.EASY),
            new Question("JDBC və Verilənlər Bazası", "Hibernate-də lazy loading nə deməkdir?",
                    List.of("Əlaqəli data yalnız faktiki istifadə olunduqda yüklənir", "Bütün data əvvəlcədən yüklənir",
                            "Data heç vaxt yüklənmir", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "commit() və rollback() metodları nə üçündür?",
                    List.of("Tranzaksiyanı təsdiqləmək və ya geri qaytarmaq üçün", "Bağlantını bağlamaq üçün",
                            "Cədvəl yaratmaq üçün", "Sorğunu icra etmək üçün"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "N+1 select problemi nədir?",
                    List.of("Hər əlaqəli obyekt üçün ayrıca sorğu göndərilməsi nəticəsində yaranan performans problemi",
                            "Verilənlər bazasının silinməsi", "Tranzaksiya xətası", "Heç bir problem deyil"), 0, Difficulty.HARD),
            new Question("JDBC və Verilənlər Bazası", "DriverManager sinifi JDBC-də nə üçün istifadə olunur?",
                    List.of("Verilənlər bazası sürücülərini idarə edib Connection yaratmaq üçün", "SQL sorğusu yaratmaq üçün",
                            "Nəticəni emal etmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "CallableStatement nə üçün istifadə olunur?",
                    List.of("Verilənlər bazasında saxlanılan prosedurları (stored procedure) çağırmaq üçün", "Sadə SELECT sorğuları üçün",
                            "Bağlantı yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "Batch processing (JDBC-də addBatch/executeBatch) nə üçün istifadə olunur?",
                    List.of("Bir neçə SQL əməliyyatını tək şəbəkə gedişi ilə icra edərək performansı artırmaq üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız SELECT üçündür", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "JDBC-də autoCommit rejimi default olaraq necədir?",
                    List.of("true (hər sorğu ayrıca tranzaksiya kimi commit olunur)", "false", "Heç bir default dəyəri yoxdur",
                            "Yalnız explisit təyin edilməlidir"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "Connection.setAutoCommit(false) nə vaxt istifadə olunur?",
                    List.of("Bir neçə sorğunu bir tranzaksiya kimi idarə etmək lazım olduqda", "Yalnız oxumaq üçün", "Heç vaxt",
                            "Yalnız test mühitində"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "SQL-də JOIN əməliyyatının məqsədi nədir?",
                    List.of("Fərqli cədvəllərdən əlaqəli data-nı birləşdirib bir nəticə dəsti almaq", "Cədvəli silmək",
                            "Cədvəli yaratmaq", "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("JDBC və Verilənlər Bazası", "Optimistic locking və pessimistic locking arasındakı fərq nədir?",
                    List.of("Optimistic konflikti yalnız yazma zamanı yoxlayır, pessimistic əvvəlcədən kilidləyir", "Fərq yoxdur",
                            "Pessimistic heç vaxt kilidləmir", "Optimistic heç vaxt konflikt yoxlamır"), 0, Difficulty.HARD),
            new Question("JDBC və Verilənlər Bazası", "JPA-da @Entity annotasiyası nə edir?",
                    List.of("Sinifin verilənlər bazası cədvəli ilə uyğunlaşdırıldığını (mapped) bildirir", "Sinifi test edir",
                            "Sinifi silir", "Heç bir işi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "Database Connection Pool-un ölçüsünü çox böyük təyin etməyin riski nədir?",
                    List.of("Verilənlər bazası serverinə həddindən artıq yük bindirə, resurs tükənməsinə səbəb ola bilər", "Heç bir riski yoxdur",
                            "Həmişə performansı artırır", "Yalnız test mühitində risklidir"), 0, Difficulty.MEDIUM),
            new Question("JDBC və Verilənlər Bazası", "JDBC URL-i (məs. jdbc:mysql://localhost:3306/mydb) nəyi ehtiva edir?",
                    List.of("Sürücü protokolu, host, port və verilənlər bazası adı", "Yalnız istifadəçi adı", "Yalnız şifrə", "Heç nə"),
                    0, Difficulty.EASY),

            new Question("SQL və Verilənlər Bazası Dizaynı", "Normalization (normallaşdırma) verilənlər bazası dizaynında nəyi hədəfləyir?",
                    List.of("Data təkrarını azaltmaq və data bütövlüyünü artırmaq", "Data-nı təkrarlamaq", "Performansı həmişə azaltmaq",
                            "Heç bir hədəfi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "Primary key nədir?",
                    List.of("Cədvəldəki hər sətri unikal identifikasiya edən sütun(lar)", "Xarici cədvələ istinad edən sütun",
                            "İndeks növü", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("SQL və Verilənlər Bazası Dizaynı", "Foreign key nə üçün istifadə olunur?",
                    List.of("Bir cədvəldəki sütunu başqa cədvəlin primary key-inə bağlayaraq əlaqə yaratmaq üçün", "Cədvəli silmək üçün",
                            "İndeks yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("SQL və Verilənlər Bazası Dizaynı", "INNER JOIN və LEFT JOIN arasındakı fərq nədir?",
                    List.of("INNER JOIN yalnız uyğun sətirləri, LEFT JOIN sol cədvəlin bütün sətirlərini (uyğunluq olmasa belə) qaytarır",
                            "Fərq yoxdur", "LEFT JOIN daha az sətir qaytarır həmişə", "INNER JOIN bütün sətirləri qaytarır"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "GROUP BY sərəncamı nə üçün istifadə olunur?",
                    List.of("Sətirləri müəyyən sütuna görə qruplaşdırıb aqreqat funksiyalar (COUNT, SUM) tətbiq etmək üçün", "Sətirləri silmək üçün",
                            "Cədvəl yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "WHERE və HAVING sərəncamları arasındakı fərq nədir?",
                    List.of("WHERE qruplaşdırmadan əvvəl, HAVING qruplaşdırmadan sonra filtr edir", "Fərq yoxdur",
                            "HAVING həmişə əvvəl işləyir", "WHERE yalnız aqreqat funksiyalar üçündür"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "Third Normal Form (3NF) nəyi tələb edir?",
                    List.of("Bütün qeyri-açar sütunların yalnız primary key-dən asılı olmasını, tranzitiv asılılığın olmamasını",
                            "Heç bir tələbi yoxdur", "Data təkrarını artırmağı", "Yalnız bir sütun olmasını"), 0, Difficulty.HARD),
            new Question("SQL və Verilənlər Bazası Dizaynı", "Denormalization nə vaxt istifadə edilə bilər?",
                    List.of("Oxuma performansını artırmaq üçün, məlum data təkrarı bahasına", "Heç vaxt", "Yalnız kiçik cədvəllərdə",
                            "Yalnız test mühitində"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "SQL-də UNION və UNION ALL arasındakı fərq nədir?",
                    List.of("UNION dublikatları silir, UNION ALL silmir", "Fərq yoxdur", "UNION ALL dublikatları silir",
                            "UNION daha sürətlidir həmişə"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "Composite key (mürəkkəb açar) nə deməkdir?",
                    List.of("Bir neçə sütunun birlikdə unikal identifikator rolunu oynaması", "Yalnız bir sütunlu açar", "İndeks növü",
                            "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "SQL-də subquery (alt-sorğu) nə üçün istifadə olunur?",
                    List.of("Bir sorğunun nəticəsini başqa sorğu daxilində istifadə etmək üçün", "Cədvəl yaratmaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız DELETE üçündür"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "Referential integrity (istinad bütövlüyü) nəyi təmin edir?",
                    List.of("Foreign key-lərin həmişə mövcud primary key-lərə istinad etməsini", "Data-nın sürətli oxunmasını",
                            "Heç bir şeyi təmin etmir", "Yalnız indekslərə aiddir"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "SQL-də DISTINCT açar sözü nə edir?",
                    List.of("Nəticədən dublikat sətirləri çıxarır", "Sətirləri sıralayır", "Sətirləri qruplaşdırır", "Heç bir işi yoxdur"),
                    0, Difficulty.EASY),
            new Question("SQL və Verilənlər Bazası Dizaynı", "View (görünüş) verilənlər bazasında nədir?",
                    List.of("Bir və ya bir neçə cədvələ əsaslanan virtual (saxlanmayan) sorğu nəticəsi", "Fiziki cədvəl", "İndeks növü",
                            "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "Stored Procedure-un üstünlüyü nədir?",
                    List.of("Mürəkkəb məntiqi verilənlər bazası tərəfində icra edərək şəbəkə gedişlərini azaltmaq", "Heç bir üstünlüyü yoxdur",
                            "Yalnız test üçündür", "Performansı həmişə azaldır"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "SQL Injection həmləsi nədir?",
                    List.of("Zərərli SQL kodunun sorğuya inject edilərək icra etdirilməsi", "Verilənlər bazası backup-ı", "Normal SQL sorğusu",
                            "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "ER Diagram (Entity-Relationship Diagram) nə üçün istifadə olunur?",
                    List.of("Verilənlər bazası strukturunu və əlaqələri vizual olaraq təsvir etmək üçün", "Kod yazmaq üçün", "Test etmək üçün",
                            "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("SQL və Verilənlər Bazası Dizaynı", "Trigger (tetikleyici) verilənlər bazasında nə edir?",
                    List.of("Müəyyən hadisə (INSERT, UPDATE, DELETE) baş verdikdə avtomatik icra olunan kod", "Yalnız SELECT-i sürətləndirir",
                            "Cədvəli silir", "Heç bir işi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("SQL və Verilənlər Bazası Dizaynı", "One-to-Many əlaqə nümunəsi hansıdır?",
                    List.of("Bir müəllifin çox kitabı ola bilər", "Bir kitabın çox müəllifi olması", "Heç bir əlaqə", "Yalnız One-to-One"),
                    0, Difficulty.EASY),
            new Question("SQL və Verilənlər Bazası Dizaynı", "SQL-də EXISTS operatoru nə üçün istifadə olunur?",
                    List.of("Alt-sorğunun ən azı bir sətir qaytarıb-qaytarmadığını yoxlamaq üçün", "Cədvəl yaratmaq üçün", "Sətri silmək üçün",
                            "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),

            new Question("NoSQL Verilənlər Bazaları", "NoSQL verilənlər bazaları RDBMS-dən nə ilə fərqlənir?",
                    List.of("Cədvəl-sətir modelindən fərqli struktur (sənəd, açar-dəyər, qraf və s.) istifadə edir və sxema tez-tez çevikdir",
                            "Fərq yoxdur", "NoSQL həmişə SQL istifadə edir", "NoSQL yalnız kiçik data üçündür"), 0, Difficulty.EASY),
            new Question("NoSQL Verilənlər Bazaları", "MongoDB hansı NoSQL kateqoriyasına aiddir?",
                    List.of("Sənəd-əsaslı (document-based)", "Açar-dəyər (key-value)", "Sütun-əsaslı (column-based)",
                            "Qraf-əsaslı (graph-based)"), 0, Difficulty.EASY),
            new Question("NoSQL Verilənlər Bazaları", "Redis əsasən nə üçün istifadə olunur?",
                    List.of("Yaddaşda (in-memory) açar-dəyər saxlanması, keşləmə üçün", "Yalnız fayl saxlanması üçün", "Yalnız test üçün",
                            "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("NoSQL Verilənlər Bazaları", "CAP teoremi nəyi ifadə edir?",
                    List.of("Paylanmış sistemin Consistency, Availability və Partition tolerance-dan yalnız ikisini eyni anda tam təmin edə biləcəyini",
                            "Heç bir mənası yoxdur", "Yalnız SQL sistemlərinə aiddir", "Performans qanunu"), 0, Difficulty.HARD),
            new Question("NoSQL Verilənlər Bazaları", "Cassandra hansı NoSQL kateqoriyasına aiddir?",
                    List.of("Sütun-əsaslı (wide-column)", "Sənəd-əsaslı", "Qraf-əsaslı", "Yalnız açar-dəyər"), 0, Difficulty.MEDIUM),
            new Question("NoSQL Verilənlər Bazaları", "NoSQL verilənlər bazalarının horizontal scaling (üfüqi genişlənmə) baxımından üstünlüyü nədir?",
                    List.of("Adətən şardinq (sharding) vasitəsilə çoxlu serverə asanlıqla paylana bilir", "Heç bir üstünlüyü yoxdur",
                            "Yalnız vertical scaling dəstəkləyir", "Scaling mümkün deyil"), 0, Difficulty.MEDIUM),
            new Question("NoSQL Verilənlər Bazaları", "Eventual consistency (nəhayət uyğunluq) nə deməkdir?",
                    List.of("Sistem müəyyən vaxt sonra bütün node-larda eyni data göstərəcəyinə zəmanət verir, dərhal deyil", "Həmişə dərhal uyğunluq",
                            "Heç bir zəmanət yoxdur", "Yalnız SQL sistemlərinə aiddir"), 0, Difficulty.HARD),
            new Question("NoSQL Verilənlər Bazaları", "Neo4j hansı NoSQL kateqoriyasına aiddir?",
                    List.of("Qraf-əsaslı (graph-based)", "Sənəd-əsaslı", "Sütun-əsaslı", "Açar-dəyər"), 0, Difficulty.MEDIUM),
            new Question("NoSQL Verilənlər Bazaları", "NoSQL-də şəma (schema) çevikliyinin əsas faydası nədir?",
                    List.of("Fərqli strukturlu data-nı asanlıqla saxlaya bilmək, sürətli inkişaf üçün əlverişli", "Heç bir faydası yoxdur",
                            "Data bütövlüyünü artırır həmişə", "Yalnız kiçik layihələr üçündür"), 0, Difficulty.MEDIUM),
            new Question("NoSQL Verilənlər Bazaları", "NoSQL verilənlər bazası nə vaxt RDBMS-dən üstün ola bilər?",
                    List.of("Böyük həcmli, çevik strukturlu data ilə yüksək horizontal scaling tələb olunduqda", "Həmişə", "Heç vaxt",
                            "Yalnız kiçik data üçün"), 0, Difficulty.MEDIUM),
            new Question("NoSQL Verilənlər Bazaları", "Sharding (parçalama) nə deməkdir?",
                    List.of("Data-nı çoxlu server arasında bölərək paylamaq", "Data-nı silmək", "Data-nı şifrələmək", "Heç bir mənası yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("NoSQL Verilənlər Bazaları", "Document database-də 'document' nəyi təmsil edir?",
                    List.of("JSON/BSON kimi formatda saxlanılan, sərbəst strukturlu data vahidini", "Fiziki fayl", "SQL cədvəlini",
                            "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("NoSQL Verilənlər Bazaları", "NoSQL verilənlər bazalarında transaction (tranzaksiya) dəstəyi ənənəvi RDBMS ilə necə müqayisə olunur?",
                    List.of("Bir çox NoSQL sistem ənənəvi olaraq daha məhdud tranzaksiya dəstəyi təklif edir (bəzi müasir sistemlər indi tam ACID dəstəkləyir)",
                            "Həmişə eyni səviyyədədir", "NoSQL heç vaxt tranzaksiya dəstəkləmir", "RDBMS heç vaxt tranzaksiya dəstəkləmir"), 0, Difficulty.HARD),
            new Question("NoSQL Verilənlər Bazaları", "Key-value store-un tipik istifadə nümunəsi hansıdır?",
                    List.of("Sessiya məlumatlarının keşlənməsi", "Mürəkkəb JOIN sorğuları", "Ağır analitik hesabatlar", "Heç bir nümunəsi yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("NoSQL Verilənlər Bazaları", "NoSQL verilənlər bazalarında indekslənmə RDBMS-dəkindən nə ilə fərqlənə bilər?",
                    List.of("Bəzi NoSQL sistemlər fərqli indeks strategiyaları (composite, geospatial və s.) təklif edə bilər, lakin ümumi məqsəd oxşardır",
                            "Heç bir fərqi yoxdur", "NoSQL heç vaxt indeksləmə dəstəkləmir", "Yalnız RDBMS indeksləmə dəstəkləyir"), 0, Difficulty.MEDIUM),
            new Question("NoSQL Verilənlər Bazaları", "Polyglot persistence nə deməkdir?",
                    List.of("Tətbiqdə fərqli data növləri üçün fərqli verilənlər bazası texnologiyalarından istifadə etmək",
                            "Yalnız bir verilənlər bazası istifadə etmək", "Heç bir mənası yoxdur", "Yalnız SQL istifadə etmək"), 0, Difficulty.HARD),
            new Question("NoSQL Verilənlər Bazaları", "MongoDB-də 'collection' anlayışı SQL-də nəyə uyğun gəlir?",
                    List.of("Cədvələ (table)", "Sətrə (row)", "Sütuna (column)", "Verilənlər bazasına"), 0, Difficulty.MEDIUM),
            new Question("NoSQL Verilənlər Bazaları", "Elasticsearch əsasən nə üçün istifadə olunur?",
                    List.of("Tam mətn axtarışı (full-text search) və analitika üçün", "Yalnız açar-dəyər saxlanması üçün",
                            "Yalnız qraf analitikası üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("NoSQL Verilənlər Bazaları", "NoSQL verilənlər bazasında BASE modeli (Basically Available, Soft state, Eventual consistency) ACID-dən nə ilə fərqlənir?",
                    List.of("BASE daha yumşaq uyğunluq zəmanətləri təklif edir, availability-ə üstünlük verir", "Fərq yoxdur",
                            "BASE ACID-dən daha ciddidir", "Heç bir əlaqəsi yoxdur"), 0, Difficulty.HARD),
            new Question("NoSQL Verilənlər Bazaları", "Verilənlər bazası seçimi zamanı NoSQL və RDBMS arasında qərar vermək üçün hansı amillər nəzərə alınmalıdır?",
                    List.of("Data strukturu, scaling tələbləri, consistency ehtiyacları və sorğu nümunələri", "Yalnız qiymət", "Yalnız marka",
                            "Heç bir amil yoxdur"), 0, Difficulty.MEDIUM),

            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Verilənlər bazası indeksi (index) nə üçün istifadə olunur?",
                    List.of("Sorğuların axtarış sürətini artırmaq üçün", "Data-nı silmək üçün", "Cədvəl yaratmaq üçün", "Heç bir məqsədi yoxdur"),
                    0, Difficulty.EASY),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "İndeksin əlavə edilməsinin mənfi tərəfi nədir?",
                    List.of("Yazma (INSERT/UPDATE/DELETE) əməliyyatlarını yavaşlada və əlavə yaddaş tələb edə bilər", "Heç bir mənfi tərəfi yoxdur",
                            "Yalnız oxumağı yavaşladır", "Yalnız kiçik cədvəllərə təsir edir"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Clustered index və non-clustered index arasındakı fərq nədir?",
                    List.of("Clustered index data-nın fiziki sırasını təyin edir, non-clustered ayrıca struktur saxlayır", "Fərq yoxdur",
                            "Non-clustered fiziki sıranı təyin edir", "Hər cədvəldə bir neçə clustered index ola bilər"), 0, Difficulty.HARD),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Composite index (mürəkkəb indeks) nə vaxt faydalıdır?",
                    List.of("Sorğular bir neçə sütuna birlikdə görə filtrasiya apardıqda", "Yalnız tək sütunlu sorğularda", "Heç vaxt",
                            "Yalnız kiçik cədvəllərdə"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "EXPLAIN (və ya EXPLAIN PLAN) sərəncamı nə üçün istifadə olunur?",
                    List.of("SQL sorğusunun icra planını analiz edərək performans darboğazlarını tapmaq üçün", "Sorğunu icra etmək üçün",
                            "Cədvəl yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "N+1 query problemi necə optimallaşdırıla bilər?",
                    List.of("JOIN və ya batch fetching istifadə edərək sorğu sayını azaltmaqla", "Daha çox sorğu əlavə etməklə",
                            "Heç bir həll yolu yoxdur", "Yalnız indeks əlavə etməklə"), 0, Difficulty.HARD),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Query caching (sorğu keşləmə) nə üçün faydalıdır?",
                    List.of("Tez-tez icra olunan eyni sorğuların nəticələrini yenidən hesablamadan qaytarmaq üçün", "Heç bir faydası yoxdur",
                            "Yalnız yazma əməliyyatları üçündür", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Full table scan nə deməkdir?",
                    List.of("Sorğunun bütün cədvəl sətirlərini indeks istifadə etmədən yoxlaması", "Yalnız indeks istifadə edərək axtarış",
                            "Cədvəlin silinməsi", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Verilənlər bazası partitioning (bölünmə) nə üçün istifadə olunur?",
                    List.of("Böyük cədvəlləri idarə oluna bilən hissələrə bölərək performansı yaxşılaşdırmaq üçün", "Data-nı silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız backup üçündür"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "SELECT * əvəzinə lazımi sütunları seçmək niyə performans üçün tövsiyə olunur?",
                    List.of("Şəbəkə/yaddaş yükünü azaldır və lazımsız data ötürülməsinin qarşısını alır", "Heç bir fərqi yoxdur",
                            "Performansı azaldır", "Yalnız stil məsələsidir"), 0, Difficulty.EASY),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Verilənlər bazası query optimizer-i nə edir?",
                    List.of("SQL sorğusunu icra etmək üçün ən effektiv icra planını seçir", "Sorğunu yazır", "Cədvəl yaradır", "Heç bir işi yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Covering index nə deməkdir?",
                    List.of("Sorğunun bütün lazımi sütunlarını cədvələ müraciət etmədən indeksin özündə təmin etməsi",
                            "Bütün sütunları əhatə edən adi indeks", "Heç bir mənası yoxdur", "Yalnız primary key indeksi"), 0, Difficulty.HARD),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Verilənlər bazasında connection pooling niyə performans üçün vacibdir?",
                    List.of("Hər sorğu üçün yeni bağlantı yaratmanın bahalı xərcindən qaçınmağa kömək edir", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız test mühiti üçündür", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Lazy loading verilənlər bazası performansına necə təsir edə bilər?",
                    List.of("Lazımsız data yükünü azaltsa da, düzgün istifadə edilmədikdə N+1 problem yarada bilər", "Heç bir təsiri yoxdur",
                            "Həmişə performansı artırır", "Yalnız yazma əməliyyatlarına təsir edir"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Verilənlər bazası replikasiyası (replication) nə üçün istifadə olunur?",
                    List.of("Yüksək əlçatanlıq və oxuma yükünü paylaşdırmaq üçün data-nın çoxlu server üzərində köçürülməsi", "Data-nı silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız backup üçündür"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Slow query log nə üçün istifadə olunur?",
                    List.of("Yavaş işləyən sorğuları aşkarlayıb optimallaşdırma üçün analiz etmək", "Sorğuları sürətləndirmək üçün avtomatik",
                            "Heç bir məqsədi yoxdur", "Yalnız test mühitində"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "İndeks seçərkən hansı sütunlar üstünlük təşkil etməlidir?",
                    List.of("Tez-tez WHERE, JOIN və ORDER BY-da istifadə olunan sütunlar", "Heç vaxt istifadə olunmayan sütunlar",
                            "Yalnız primary key", "Heç bir prinsipi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Database vacuuming/analyzing (məs. PostgreSQL-də) nə üçün lazımdır?",
                    List.of("Statistikanı yeniləmək və silinmiş sətirlərin yaratdığı boş yeri təmizləmək üçün", "Data-nı silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız backup üçündür"), 0, Difficulty.HARD),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Read replica nə üçün istifadə olunur?",
                    List.of("Oxuma sorğularını əsas verilənlər bazasından ayıraraq yükü azaltmaq üçün", "Yazma sorğuları üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız backup üçün"), 0, Difficulty.MEDIUM),
            new Question("Verilənlər Bazası İndeksləmə və Optimallaşdırma", "Materialized view adi view-dan nə ilə fərqlənir?",
                    List.of("Nəticəni fiziki olaraq saxlayır və vaxtaşırı yenilənir, adi view isə hər sorğuda yenidən hesablanır", "Fərq yoxdur",
                            "Adi view fiziki saxlanır", "Materialized view heç vaxt yenilənmir"), 0, Difficulty.HARD),

            new Question("Keşləmə Strategiyaları", "Keşləmə (caching) nə üçün istifadə olunur?",
                    List.of("Tez-tez sorğulanan data-nı sürətli çıxışlı yaddaşda saxlayaraq performansı artırmaq üçün", "Data-nı silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçündür"), 0, Difficulty.EASY),
            new Question("Keşləmə Strategiyaları", "Cache-Aside (Lazy Loading) strategiyası necə işləyir?",
                    List.of("Tətbiq əvvəlcə keşi yoxlayır, tapılmasa mənbədən oxuyub keşə yazır", "Həmişə mənbədən oxuyur",
                            "Heç vaxt keşi yoxlamır", "Yalnız yazma zamanı işləyir"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "Write-Through keşləmə strategiyası nə edir?",
                    List.of("Data yazılarkən eyni zamanda həm keşə, həm də əsas mənbəyə yazılır", "Yalnız keşə yazılır",
                            "Yalnız mənbəyə yazılır", "Heç bir yerə yazılmır"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "Write-Behind (Write-Back) keşləmə strategiyası nə edir?",
                    List.of("Data əvvəlcə keşə yazılır, əsas mənbəyə yazma isə gecikdirilir (asinxron)", "Data heç vaxt keşlənmir",
                            "Data yalnız mənbəyə yazılır", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("Keşləmə Strategiyaları", "Cache eviction policy (keş çıxarma siyasəti) nə üçün lazımdır?",
                    List.of("Keş dolduqda hansı elementlərin çıxarılacağını müəyyən etmək üçün", "Keşi silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "LRU (Least Recently Used) eviction siyasəti nəyi çıxarır?",
                    List.of("Ən uzun müddət istifadə olunmayan elementi", "Ən çox istifadə olunan elementi", "Təsadüfi elementi",
                            "Ən yeni əlavə olunan elementi"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "Cache invalidation (keş etibarsızlaşdırma) niyə çətin problem hesab olunur?",
                    List.of("Data dəyişdikdə keşdəki köhnə məlumatı vaxtında və düzgün yeniləmək mürəkkəbdir", "Heç bir çətinliyi yoxdur",
                            "Avtomatik həll olunur həmişə", "Yalnız test mühitində problemdir"), 0, Difficulty.HARD),
            new Question("Keşləmə Strategiyaları", "Distributed cache (paylanmış keş, məs. Redis cluster) nə üçün istifadə olunur?",
                    List.of("Bir neçə server/instansiya arasında keş datanı paylaşmaq üçün", "Yalnız bir server üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "Cache stampede (keş basqını) problemi nə vaxt yaranır?",
                    List.of("Populyar keş elementi bitdikdə çoxlu sorğu eyni anda mənbəyə müraciət edir", "Heç vaxt yaranmır",
                            "Yalnız yazma zamanı", "Yalnız kiçik keşlərdə"), 0, Difficulty.HARD),
            new Question("Keşləmə Strategiyaları", "TTL (Time To Live) keşləmədə nəyi ifadə edir?",
                    List.of("Keşlənmiş datanın etibarlı qalacağı müddət", "Server-in işləmə müddəti", "Sorğunun icra vaxtı",
                            "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Keşləmə Strategiyaları", "Application-level caching və HTTP caching arasındakı fərq nədir?",
                    List.of("Application-level tətbiq daxilində (məs. Redis), HTTP caching isə brauzer/proksi səviyyəsində baş verir",
                            "Fərq yoxdur", "HTTP caching yalnız server-də olur", "Application-level yalnız brauzerdə olur"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "CDN (Content Delivery Network) keşləmə baxımından nə edir?",
                    List.of("Statik məzmunu coğrafi baxımdan istifadəçiyə yaxın serverlərdə keşləyir", "Yalnız verilənlər bazasını keşləyir",
                            "Heç bir məqsədi yoxdur", "Yalnız API sorğularını keşləyir"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "Keşləmə strategiyası seçərkən consistency və performans arasında hansı trade-off nəzərə alınmalıdır?",
                    List.of("Daha aqressiv keşləmə performansı artıra bilər, amma köhnəlmiş data riski yaradır", "Heç bir trade-off yoxdur",
                            "Keşləmə həmişə consistency-ni artırır", "Performans həmişə consistency-dən vacibdir"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "Spring-də @Cacheable annotasiyası nə edir?",
                    List.of("Metodun nəticəsini keşləyir, eyni parametrlərlə təkrar çağırışda keşdən qaytarır", "Metodu silir",
                            "Metodu final edir", "Heç bir işi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "Cache warming (keşin qızdırılması) nə deməkdir?",
                    List.of("Tətbiq başlamazdan əvvəl və ya başlanğıcda tez-tez istifadə olunan datanı əvvəlcədən keşə yükləmək", "Keşi silmək",
                            "Heç bir mənası yoxdur", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "Keşləmədə 'hit rate' (uğur nisbəti) nəyi ölçür?",
                    List.of("Sorğuların neçə faizinin keşdən uğurla təmin edildiyini", "Server sürətini", "Yaddaş ölçüsünü", "Heç nəyi"),
                    0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "Session caching nə üçün istifadə olunur?",
                    List.of("İstifadəçi sessiya məlumatlarını sürətli çıxış üçün yaddaşda saxlamaq üçün", "Fayl saxlamaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "Keşdə saxlanılan datanın ölçüsü çox böyük olduqda hansı risk yaranır?",
                    List.of("Yaddaş tükənməsi və ya performans deqradasiyası", "Heç bir risk yoxdur", "Həmişə performansı artırır",
                            "Yalnız test mühitində risklidir"), 0, Difficulty.MEDIUM),
            new Question("Keşləmə Strategiyaları", "Read-through cache nə edir?",
                    List.of("Keş mənbədən oxumanı özü idarə edir, tətbiq yalnız keşlə əlaqə saxlayır", "Tətbiq həmişə birbaşa mənbəyə müraciət edir",
                            "Heç bir mənası yoxdur", "Yalnız yazma üçündür"), 0, Difficulty.HARD),
            new Question("Keşləmə Strategiyaları", "Keşləmə strategiyası seçərkən data-nın nə qədər tez-tez dəyişdiyi niyə vacibdir?",
                    List.of("Tez-tez dəyişən data üçün qısa TTL və ya fərqli invalidation strategiyası lazım ola bilər", "Heç bir əhəmiyyəti yoxdur",
                            "Data dəyişikliyi keşləməyə təsir etmir", "Yalnız statik data keşlənə bilər"), 0, Difficulty.MEDIUM)
    );

    public static List<Question> get() {
        return QUESTIONS;
    }
}
