package repository.bank;

import model.Difficulty;
import model.Question;

import java.util.List;

public class DevOpsInfraQuestions {

    private static final List<Question> QUESTIONS = List.of(
            new Question("Maven və Gradle", "Maven-in əsas məqsədi nədir?",
                    List.of("Layihənin build, asılılıq idarəetməsi və layihə strukturunu standartlaşdırmaq", "Yalnız kodu compile etmək",
                            "Test yazmaq", "UI yaratmaq"), 0, Difficulty.EASY),
            new Question("Maven və Gradle", "pom.xml faylı nəyi təsvir edir?",
                    List.of("Maven layihəsinin konfiqurasiyasını və asılılıqlarını", "Java kodunu",
                            "Test nəticələrini", "Heç nəyi"), 0, Difficulty.EASY),
            new Question("Maven və Gradle", "Maven-də 'dependency' nə deməkdir?",
                    List.of("Layihənin ehtiyac duyduğu xarici kitabxana", "Test sinifi", "Compile xətası", "Heç bir mənası yoxdur"),
                    0, Difficulty.EASY),
            new Question("Maven və Gradle", "Gradle, Maven-dən nə ilə fərqlənir?",
                    List.of("XML əvəzinə Groovy/Kotlin DSL istifadə edir və adətən daha sürətlidir", "Fərq yoxdur",
                            "Gradle yalnız Android üçündür", "Maven daha sürətlidir"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Maven-in 'build lifecycle' mərhələlərindən biri deyil hansıdır?",
                    List.of("compile", "test", "package", "refactor"), 3, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Semantic Versioning-də (MAJOR.MINOR.PATCH) MAJOR versiyasının artması nəyi bildirir?",
                    List.of("Geriyə uyğun olmayan (breaking) dəyişikliklər", "Kiçik bug fix", "Sənədləşmə dəyişikliyi", "Heç nəyi"),
                    0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Maven repository (local, central, remote) nə üçündür?",
                    List.of("Asılılıqların saxlandığı və axtarıldığı yer", "Kodun versiyalaşdırıldığı yer",
                            "Test nəticələrinin saxlandığı yer", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "'mvn clean install' əmri nə edir?",
                    List.of("Əvvəlki build nəticələrini silir, yenidən compile/test edir və artefaktı local repository-ə quraşdırır",
                            "Yalnız kodu silir", "Yalnız test edir", "Heç nə etmir"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Gradle-də build.gradle faylının rolu nədir?",
                    List.of("Layihənin build konfiqurasiyasını təyin etmək (pom.xml-in Gradle qarşılığı)", "Test nəticələrini saxlamaq",
                            "Kodu compile etmək", "Heç bir rolu yoxdur"), 0, Difficulty.EASY),
            new Question("Maven və Gradle", "Transitive dependency nə deməkdir?",
                    List.of("Birbaşa əlavə etdiyiniz asılılığın öz asılılıqlarının da avtomatik daxil edilməsi", "Yalnız birbaşa asılılıqlar",
                            "Test asılılıqları", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Maven-də 'scope' (məs. compile, test, provided) nəyi müəyyən edir?",
                    List.of("Asılılığın hansı build mərhələlərində istifadə olunacağını", "Asılılığın versiyasını", "Asılılığın adını", "Heç nəyi"),
                    0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Maven-in 'plugin' anlayışı nəyi ifadə edir?",
                    List.of("Build prosesinə əlavə funksionallıq (məs. compile, test, package) əlavə edən komponent", "Asılılıq növü",
                            "Test sinifi", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Gradle-də 'task' nədir?",
                    List.of("Build prosesinin bir addımını təmsil edən icra vahidi", "Asılılıq növü", "Test sinifi", "Heç bir mənası yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Maven-in 'parent POM' konsepsiyası nə üçün istifadə olunur?",
                    List.of("Çoxlu modul arasında ortaq konfiqurasiyanı paylaşmaq üçün", "Test yazmaq üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız kiçik layihələr üçündür"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Gradle-in 'incremental build' xüsusiyyəti nə edir?",
                    List.of("Yalnız dəyişən hissələri yenidən compile edərək build vaxtını azaldır", "Hər dəfə hər şeyi yenidən compile edir",
                            "Heç bir təsiri yoxdur", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Maven-də 'SNAPSHOT' versiyası nə deməkdir?",
                    List.of("Hələ inkişaf mərhələsində olan, sabit olmayan versiya", "Final buraxılış", "Test versiyası yalnız",
                            "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Build alətlərində 'reproducible build' (təkrarlana bilən build) nə üçün vacibdir?",
                    List.of("Eyni mənbə koddan həmişə eyni nəticənin alınmasını təmin edir, etibarlılığı artırır", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız test üçündür", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Maven-in 'install' phase-i nə edir?",
                    List.of("Artefaktı local repository-yə quraşdırır ki, digər layihələr istifadə edə bilsin", "Yalnız compile edir",
                            "Yalnız test edir", "Heç nə etmir"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Gradle Wrapper (gradlew) nə üçün istifadə olunur?",
                    List.of("Layihəni Gradle-in müəyyən versiyası ilə, ayrıca quraşdırma tələb etmədən işə salmaq üçün", "Yalnız test üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız Windows üçün"), 0, Difficulty.MEDIUM),
            new Question("Maven və Gradle", "Maven-in effective POM anlayışı nədir?",
                    List.of("Bütün miras alınmış və defolt konfiqurasiyalarla tam həll edilmiş son POM", "Yalnız pom.xml faylının özü",
                            "Heç bir mənası yoxdur", "Yalnız parent POM"), 0, Difficulty.HARD),

            new Question("Docker və Konteynerləşdirmə", "Docker konteyneri nədir?",
                    List.of("Tətbiqi və onun asılılıqlarını izolyasiya edilmiş mühitdə paketləyən yüngül, icra oluna bilən vahid",
                            "Virtual machine", "Fiziki server", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Docker və Konteynerləşdirmə", "Docker image və Docker container arasındakı fərq nədir?",
                    List.of("Image statik şablon, container isə image-in icra olunan instansiyasıdır", "Fərq yoxdur",
                            "Container statikdir", "Image icra olunandır"), 0, Difficulty.EASY),
            new Question("Docker və Konteynerləşdirmə", "Dockerfile nədir?",
                    List.of("Docker image-in necə qurulacağını təsvir edən təlimatlar faylı", "Konfiqurasiya fayl formatı",
                            "Test faylı", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Docker və Konteynerləşdirmə", "Docker konteynerləri virtual machine-lərdən nə ilə fərqlənir?",
                    List.of("Host OS kernel-ini paylaşdıqları üçün daha yüngül və sürətlidirlər", "Fərq yoxdur", "VM-lər daha yüngüldür",
                            "Konteynerlər öz OS-lərini daşıyır"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "docker-compose nə üçün istifadə olunur?",
                    List.of("Bir neçə konteyneri (multi-container tətbiqi) birlikdə təyin edib idarə etmək üçün", "Yalnız bir konteyner üçün",
                            "Image yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Docker-də layer (qat) konsepsiyası nə üçün faydalıdır?",
                    List.of("Image-lər qatlardan ibarətdir, dəyişməyən qatlar keşlənərək build sürətini artırır", "Heç bir faydası yoxdur",
                            "Yalnız fayl ölçüsünü artırır", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Docker Hub nədir?",
                    List.of("Docker image-lərinin saxlanıldığı və paylaşıldığı bulud əsaslı registry", "Yalnız local repository",
                            "Test framework-ü", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Docker və Konteynerləşdirmə", "Multi-stage build Docker-də nə üçün istifadə olunur?",
                    List.of("Build və runtime mərhələlərini ayıraraq son image ölçüsünü kiçiltmək üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün", "Image-i böyütmək üçün"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Docker volume nə üçün istifadə olunur?",
                    List.of("Konteynerdən kənarda, davamlı (persistent) data saxlamaq üçün", "Konteyneri silmək üçün",
                            "Şəbəkə yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Docker-də EXPOSE təlimatı nə edir?",
                    List.of("Konteynerin dinlədiyi portu sənədləşdirir (host-a avtomatik map etmir)", "Portu birbaşa host-a açır",
                            "Konteyneri bağlayır", "Heç bir işi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Docker network rejimləri (bridge, host, none) nəyi idarə edir?",
                    List.of("Konteynerin şəbəkə izolyasiyası və host ilə əlaqə üsulunu", "Yalnız fayl sistemini", "Yalnız CPU limitini",
                            "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Konteynerlərin stateless dizayn edilməsi niyə tövsiyə olunur?",
                    List.of("Asanlıqla yenidən yaradıla, miqyaslana və orkestrasiya edilə bilmələri üçün", "Heç bir səbəb yoxdur",
                            "Stateful daha yaxşıdır həmişə", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Docker-də .dockerignore faylı nə üçündür?",
                    List.of("Build kontekstinə daxil edilməməli faylları müəyyən etmək üçün (.gitignore kimi)", "Konteyneri silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Container orchestration (orkestrasiya) nə deməkdir?",
                    List.of("Çoxlu konteynerin deployment, scaling və idarəsinin avtomatlaşdırılması", "Bir konteynerin yaradılması",
                            "Heç bir mənası yoxdur", "Yalnız şəbəkə konfiqurasiyası"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Docker image-in ölçüsünü kiçiltmək üçün hansı üsul tövsiyə olunur?",
                    List.of("Yüngül baza image (məs. alpine) istifadə etmək və lazımsız qatları azaltmaq", "Böyük baza image istifadə etmək",
                            "Heç bir üsul yoxdur", "Bütün alətləri əlavə etmək"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Docker konteynerinin restart policy-si nə üçün istifadə olunur?",
                    List.of("Konteyner çökdükdə avtomatik yenidən başlama davranışını müəyyən etmək üçün", "Konteyneri silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Docker Swarm nədir?",
                    List.of("Docker-in daxili konteyner orkestrasiya aləti", "Yalnız şəbəkə aləti", "Verilənlər bazası", "Heç bir mənası yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Konteynerləşdirmənin CI/CD pipeline-larında rolü nədir?",
                    List.of("Tətbiqin bütün mühitlərdə (dev, test, prod) eyni şəkildə işləməsini təmin edir", "Heç bir rolu yoxdur",
                            "Yalnız test üçündür", "Yalnız production üçündür"), 0, Difficulty.MEDIUM),
            new Question("Docker və Konteynerləşdirmə", "Docker-də ENTRYPOINT və CMD təlimatları arasındakı fərq nədir?",
                    List.of("ENTRYPOINT konteynerin əsas icra olunan komandasını təyin edir, CMD default arqumentləri verir (üstünə yazıla bilər)",
                            "Fərq yoxdur", "CMD dəyişdirilə bilməz", "ENTRYPOINT dəyişdirilə bilməz"), 0, Difficulty.HARD),
            new Question("Docker və Konteynerləşdirmə", "Docker-in təhlükəsizlik baxımından tövsiyə olunan praktikalarından biri hansıdır?",
                    List.of("Konteynerləri root istifadəçi kimi işə salmamaq", "Həmişə root kimi işə salmaq", "Heç bir tövsiyə yoxdur",
                            "Bütün portları açıq saxlamaq"), 0, Difficulty.MEDIUM),

            new Question("Kubernetes Əsasları", "Kubernetes nədir?",
                    List.of("Konteynerləşdirilmiş tətbiqlərin deployment, scaling və idarəsini avtomatlaşdıran açıq mənbəli platforma",
                            "Verilənlər bazası", "Proqramlaşdırma dili", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Kubernetes Əsasları", "Kubernetes-də Pod nədir?",
                    List.of("Kubernetes-in ən kiçik deployment vahidi, bir və ya bir neçə konteyner ehtiva edə bilər", "Fiziki server",
                            "Verilənlər bazası cədvəli", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Kubernetes Əsasları", "Kubernetes Service nə üçün istifadə olunur?",
                    List.of("Pod-lara sabit şəbəkə ünvanı və yük balanslaşdırması təmin etmək üçün", "Pod-u silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "Kubernetes Deployment obyekti nəyi idarə edir?",
                    List.of("Pod-ların istənilən vəziyyətini (sayı, versiya) elan edərək avtomatik idarə edilməsini", "Yalnız bir Pod-u",
                            "Heç bir mənası yoxdur", "Yalnız verilənlər bazasını"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "Kubernetes-də ReplicaSet nə edir?",
                    List.of("Müəyyən sayda Pod nüsxəsinin daim işlək olmasını təmin edir", "Pod-u silir", "Heç bir işi yoxdur",
                            "Yalnız bir Pod yaradır"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "Horizontal Pod Autoscaler (HPA) nə üçün istifadə olunur?",
                    List.of("Yükə əsasən Pod sayını avtomatik artırıb-azaltmaq üçün", "Pod-u silmək üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız manual scaling üçün"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "Kubernetes-də Namespace nə üçün istifadə olunur?",
                    List.of("Klaster resurslarını məntiqi qruplara bölmək üçün", "Fiziki serveri bölmək üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "Kubernetes ConfigMap nə üçün istifadə olunur?",
                    List.of("Konfiqurasiya məlumatlarını konteyner image-dən ayrı saxlamaq üçün", "Şifrələri saxlamaq üçün (bu Secret-in işidir)",
                            "Pod yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "Kubernetes Secret, ConfigMap-dən nə ilə fərqlənir?",
                    List.of("Secret həssas məlumatlar (şifrələr, tokenlər) üçün nəzərdə tutulub və əlavə qorunma tətbiq edilə bilər",
                            "Fərq yoxdur", "ConfigMap həssas data üçündür", "Heç bir fərqi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "Kubernetes-də liveness probe və readiness probe arasındakı fərq nədir?",
                    List.of("Liveness konteynerin canlı olub-olmadığını, readiness isə trafik qəbul etməyə hazır olub-olmadığını yoxlayır",
                            "Fərq yoxdur", "Readiness konteyneri yenidən başladır", "Liveness trafiki idarə edir"), 0, Difficulty.HARD),
            new Question("Kubernetes Əsasları", "Kubernetes-də Ingress nə üçün istifadə olunur?",
                    List.of("Klasterdən kənar HTTP/HTTPS trafiki Service-lərə marşrutlaşdırmaq üçün", "Pod yaratmaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız daxili trafik üçün"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "Kubernetes-də etcd nə rol oynayır?",
                    List.of("Klasterin bütün konfiqurasiya və vəziyyət məlumatını saxlayan paylanmış açar-dəyər anbarı", "Konteyner runtime-ı",
                            "Yük balanslayıcı", "Heç bir rolu yoxdur"), 0, Difficulty.HARD),
            new Question("Kubernetes Əsasları", "kubectl nədir?",
                    List.of("Kubernetes klasterini idarə etmək üçün əmr sətri aləti", "Konteyner runtime-ı", "Verilənlər bazası",
                            "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Kubernetes Əsasları", "Kubernetes-də rolling update strategiyası nə edir?",
                    List.of("Downtime-sız, tədricən köhnə Pod-ları yenisi ilə əvəz edir", "Bütün Pod-ları eyni anda dayandırır",
                            "Heç bir strategiyası yoxdur", "Yalnız manual update dəstəkləyir"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "StatefulSet, Deployment-dən nə ilə fərqlənir?",
                    List.of("StatefulSet stabil şəbəkə identiklikləri və davamlı saxlama tələb edən tətbiqlər (məs. verilənlər bazası) üçün nəzərdə tutulub",
                            "Fərq yoxdur", "Deployment stateful tətbiqlər üçündür", "Heç bir fərqi yoxdur"), 0, Difficulty.HARD),
            new Question("Kubernetes Əsasları", "Kubernetes-də node nədir?",
                    List.of("Pod-ları işə salan fiziki və ya virtual maşın", "Konteyner image-i", "Şəbəkə protokolu", "Heç bir mənası yoxdur"),
                    0, Difficulty.EASY),
            new Question("Kubernetes Əsasları", "Kubernetes-də Helm nədir?",
                    List.of("Kubernetes tətbiqlərini paketləmək və idarə etmək üçün paket meneceri", "Konteyner runtime-ı",
                            "Verilənlər bazası", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "Kubernetes-də resource limits və requests nə üçün təyin edilir?",
                    List.of("Konteynerlərin CPU/yaddaş istifadəsini idarə edərək resursların ədalətli paylanmasını təmin etmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün", "Pod-u silmək üçün"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "Kubernetes-də self-healing xüsusiyyəti nə deməkdir?",
                    List.of("Uğursuz Pod-ların avtomatik aşkarlanıb yenidən başladılması/əvəz edilməsi", "Heç bir mənası yoxdur",
                            "Yalnız manual müdaxilə tələb edir", "Yalnız test mühitində işləyir"), 0, Difficulty.MEDIUM),
            new Question("Kubernetes Əsasları", "Kubernetes klasterini cloud provider-lərdə idarə edilən xidmət kimi təklif edən nümunələr hansılardır?",
                    List.of("EKS (AWS), GKE (Google), AKS (Azure)", "Yalnız local quraşdırma", "Heç bir belə xidmət yoxdur",
                            "Yalnız Docker Swarm"), 0, Difficulty.MEDIUM),

            new Question("CI/CD və DevOps", "CI (Continuous Integration) nə deməkdir?",
                    List.of("Developerlərin kodu tez-tez mərkəzi repository-ə inteqrasiya edib avtomatik test etməsi", "Yalnız manual test",
                            "Heç bir mənası yoxdur", "Yalnız deployment prosesi"), 0, Difficulty.EASY),
            new Question("CI/CD və DevOps", "CD (Continuous Delivery/Deployment) nə deməkdir?",
                    List.of("Kodun avtomatik olaraq test mühitinə və ya production-a çatdırılması", "Yalnız kodu yazmaq",
                            "Heç bir mənası yoxdur", "Yalnız test yazmaq"), 0, Difficulty.EASY),
            new Question("CI/CD və DevOps", "CI/CD pipeline-ının tipik mərhələləri hansılardır?",
                    List.of("Build, Test, Deploy (bəzən Lint/Analyze əlavə olunur)", "Yalnız Deploy", "Yalnız Test", "Heç bir mərhələsi yoxdur"),
                    0, Difficulty.EASY),
            new Question("CI/CD və DevOps", "DevOps mədəniyyətinin əsas məqsədi nədir?",
                    List.of("Development və Operations komandaları arasında əməkdaşlığı artıraraq daha sürətli, etibarlı çatdırma təmin etmək",
                            "Komandaları ayırmaq", "Heç bir məqsədi yoxdur", "Yalnız alət dəyişikliyi"), 0, Difficulty.EASY),
            new Question("CI/CD və DevOps", "Jenkins nədir?",
                    List.of("Populyar açıq mənbəli CI/CD avtomatlaşdırma aləti", "Verilənlər bazası", "Proqramlaşdırma dili",
                            "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("CI/CD və DevOps", "Infrastructure as Code (IaC) nə deməkdir?",
                    List.of("İnfrastrukturu kod vasitəsilə (məs. Terraform) təsvir edib idarə etmək", "Yalnız manual konfiqurasiya",
                            "Heç bir mənası yoxdur", "Yalnız GUI ilə idarəetmə"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Blue-Green Deployment strategiyası nə edir?",
                    List.of("İki eyni mühit saxlayaraq trafiki yeni versiyaya downtime olmadan keçirir", "Yalnız bir mühit istifadə edir",
                            "Heç bir strategiyası yoxdur", "Həmişə downtime yaradır"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Canary Deployment nə deməkdir?",
                    List.of("Yeni versiyanı əvvəlcə istifadəçilərin kiçik hissəsinə tədricən buraxmaq", "Bütün istifadəçilərə eyni anda buraxmaq",
                            "Heç bir mənası yoxdur", "Yalnız test mühitində istifadə olunur"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Pipeline-da avtomatik testlərin rolü nədir?",
                    List.of("Hər dəyişiklikdən sonra reqressiyaları erkən aşkarlamaq", "Heç bir rolu yoxdur", "Yalnız manual test əvəzinə deyil",
                            "Testlər lazımsızdır"), 0, Difficulty.EASY),
            new Question("CI/CD və DevOps", "GitOps yanaşması nə deməkdir?",
                    List.of("Git repository-ni infrastruktur və deployment vəziyyətinin mənbəyi (source of truth) kimi istifadə etmək",
                            "Yalnız kod saxlamaq üçün Git", "Heç bir mənası yoxdur", "Yalnız local development üçün"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Feature flag (feature toggle) nə üçün istifadə olunur?",
                    List.of("Yeni funksionallığı deploy etsə də, runtime-da aktiv/deaktiv etmək imkanı vermək üçün", "Kodu silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Continuous Monitoring CI/CD pipeline-ında niyə vacibdir?",
                    List.of("Production-da problemlərin tez aşkarlanmasını təmin edir", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız development mühitində lazımdır", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Rollback strategiyası CI/CD-də nə üçün vacibdir?",
                    List.of("Problem yaradan deployment-i tez bir zamanda əvvəlki sabit vəziyyətə qaytarmaq üçün", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız test üçün", "Yalnız manual proseslərdə lazımdır"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Artifact repository (məs. Nexus, Artifactory) CI/CD-də nə rol oynayır?",
                    List.of("Build artefaktlarını (jar, image və s.) saxlayıb versiyalaşdırır", "Kodu yazır", "Heç bir rolu yoxdur",
                            "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Pipeline as Code (məs. Jenkinsfile) nə üçün üstünlük təşkil edir?",
                    List.of("Pipeline konfiqurasiyasını versiyalaşdırılan kod kimi saxlamağa imkan verir", "Heç bir üstünlüyü yoxdur",
                            "Yalnız GUI konfiqurasiyası mümkündür", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Shift-left testing DevOps-da nə deməkdir?",
                    List.of("Testləri inkişaf prosesinin daha erkən mərhələlərinə köçürmək", "Testləri sona köçürmək", "Heç bir mənası yoxdur",
                            "Testləri ləğv etmək"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "SRE (Site Reliability Engineering) nə üçün mövcuddur?",
                    List.of("Proqram mühəndisliyi prinsiplərini əməliyyat (operations) problemlərinə tətbiq etmək üçün", "Yalnız test üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız UI dizaynı üçün"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Deployment pipeline-da 'quality gate' nə edir?",
                    List.of("Müəyyən keyfiyyət meyarları (test coverage, statik analiz) ötülmədən növbəti mərhələyə keçidin qarşısını alır",
                            "Heç bir işi yoxdur", "Yalnız sürəti artırır", "Yalnız sənədləşmə üçündür"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Immutable infrastructure konsepsiyası nə deməkdir?",
                    List.of("Mövcud infrastrukturu dəyişdirmək əvəzinə yeni versiya yaradıb əvəz etmək", "İnfrastrukturu tez-tez dəyişdirmək",
                            "Heç bir mənası yoxdur", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("CI/CD və DevOps", "Mean Time To Recovery (MTTR) metrikası nəyi ölçür?",
                    List.of("Bir problemdən sonra sistemin normal işə qayıtması üçün orta müddəti", "Kod yazma sürətini", "Test sayını",
                            "Heç nəyi"), 0, Difficulty.MEDIUM),

            new Question("Mesaj Növbələri", "Mesaj növbəsi (message queue) nə üçün istifadə olunur?",
                    List.of("Sistemlər/servislər arasında asinxron kommunikasiya təmin etmək üçün", "Yalnız sinxron kommunikasiya üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız fayl saxlamaq üçün"), 0, Difficulty.EASY),
            new Question("Mesaj Növbələri", "Producer və Consumer mesajlaşma sistemlərində nəyi ifadə edir?",
                    List.of("Producer mesaj göndərən, Consumer mesajı qəbul edib emal edən tərəfdir", "Fərq yoxdur", "Consumer mesaj göndərir",
                            "Producer mesaj qəbul edir"), 0, Difficulty.EASY),
            new Question("Mesaj Növbələri", "Apache Kafka nədir?",
                    List.of("Yüksək məhsuldarlıqlı, paylanmış streaming platforması", "Verilənlər bazası", "Proqramlaşdırma dili",
                            "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Mesaj Növbələri", "Kafka-da 'topic' nədir?",
                    List.of("Mesajların kateqoriyalaşdırılıb saxlanıldığı adlı axın (kanal)", "Server", "Verilənlər bazası cədvəli",
                            "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Mesaj Növbələri", "Kafka-da partition (bölmə) nə üçün istifadə olunur?",
                    List.of("Topic-i paralel emal və miqyaslanma üçün bir neçə hissəyə bölmək üçün", "Mesajı silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız backup üçün"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "RabbitMQ hansı mesajlaşma protokolunu əsas götürür?",
                    List.of("AMQP (Advanced Message Queuing Protocol)", "HTTP", "FTP", "Heç birini"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "Point-to-Point (növbə) və Publish-Subscribe mesajlaşma modelləri arasındakı fərq nədir?",
                    List.of("Point-to-Point mesajı bir consumer-ə, Pub-Sub isə çoxlu abunəçiyə çatdırır", "Fərq yoxdur",
                            "Pub-Sub yalnız bir alıcıya çatdırır", "Point-to-Point çoxlu alıcıya çatdırır"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "Kafka-da consumer group nə üçün istifadə olunur?",
                    List.of("Bir neçə consumer-in birlikdə işləyərək topic-in partition-larını paylaşaraq emal etməsi üçün", "Mesajı silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız bir consumer üçündür"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "Message broker-in dead letter queue (DLQ) konsepsiyası nə üçündür?",
                    List.of("Emal edilə bilməyən mesajları ayrıca növbəyə yönləndirərək itkinin qarşısını almaq üçün", "Heç bir məqsədi yoxdur",
                            "Mesajları tamamilə silmək üçün", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "Mesaj növbələrinin əsas üstünlüyü nədir (sistemlər arasında)?",
                    List.of("Sistemləri decouple edərək (asılılığı azaldaraq) çevikliyi və dözümlülüyü artırmaq", "Heç bir üstünlüyü yoxdur",
                            "Sistemləri sıx bağlamaq", "Yalnız performansı azaltmaq"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "Kafka-da 'offset' nəyi ifadə edir?",
                    List.of("Consumer-in partition daxilində hansı mesaja qədər oxuduğunu göstərən indeks", "Mesajın ölçüsünü",
                            "Topic adını", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "At-least-once, at-most-once və exactly-once çatdırılma zəmanətləri nəyi ifadə edir?",
                    List.of("Mesajın neçə dəfə çatdırıla biləcəyinə dair fərqli təminat səviyyələrini", "Hamısı eynidir",
                            "Yalnız exactly-once mövcuddur", "Heç bir fərqi yoxdur"), 0, Difficulty.HARD),
            new Question("Mesaj Növbələri", "Message queue istifadə edərək sistem dizaynında hansı problem azalır?",
                    List.of("Sıx bağlılıq (tight coupling) və sistemlərin birbaşa bir-birindən asılılığı", "Performans", "Heç bir problem azalmır",
                            "Kod sətir sayı"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "Kafka-nın 'replication factor' parametri nəyi təmin edir?",
                    List.of("Data itkisinin qarşısını almaq üçün partition-un neçə nüsxəsinin saxlanacağını", "Mesaj sürətini",
                            "Heç bir mənası yoxdur", "Yalnız topic sayını"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "RabbitMQ-da 'exchange' nə rol oynayır?",
                    List.of("Mesajları müəyyən qaydalara (routing) əsasən müvafiq növbələrə yönləndirir", "Mesajı saxlayır",
                            "Heç bir rolu yoxdur", "Yalnız consumer-dir"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "Event-driven architecture (hadisə əsaslı memarlıq) mesaj növbələri ilə necə bağlıdır?",
                    List.of("Servislər hadisələri mesaj növbələri/broker vasitəsilə asinxron paylaşaraq reaksiya verir", "Heç bir əlaqəsi yoxdur",
                            "Yalnız sinxron çağırışlar istifadə olunur", "Mesaj növbələri yalnız batch emalı üçündür"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "Mesaj sıralamasının (ordering) qorunması Kafka-da necə təmin edilir?",
                    List.of("Eyni partition daxilində mesajlar göndərilmə ardıcıllığı ilə saxlanılır", "Heç vaxt təmin edilmir",
                            "Yalnız bir topic olduqda", "Heç bir mexanizmi yoxdur"), 0, Difficulty.HARD),
            new Question("Mesaj Növbələri", "Message queue-nun batch emalı (batch processing) ilə real-time streaming arasındakı fərqi necə körpüləyə bilər?",
                    List.of("Mesajları buferləşdirərək həm real-vaxta yaxın, həm də toplu emala imkan verir", "Heç bir fərqi yoxdur",
                            "Yalnız batch emalı üçündür", "Yalnız real-time üçündür"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "Mikroservis memarlığında mesaj növbələri hansı ssenaridə xüsusilə faydalıdır?",
                    List.of("Servislər arasında asinxron, dözümlü kommunikasiya lazım olduqda (məs. sifariş emalı)", "Heç bir ssenaridə",
                            "Yalnız sinxron REST çağırışları üçün", "Yalnız UI kommunikasiyası üçün"), 0, Difficulty.MEDIUM),
            new Question("Mesaj Növbələri", "Mesaj brokerinin yüksək əlçatanlığı (high availability) necə təmin edilir?",
                    List.of("Klasterləşmə və replikasiya vasitəsilə", "Yalnız bir server istifadə edərək", "Heç bir üsulla", "Yalnız backup ilə"),
                    0, Difficulty.MEDIUM)
    );

    public static List<Question> get() {
        return QUESTIONS;
    }
}
