package repository.bank;

import model.Difficulty;
import model.Question;

import java.util.List;

public class LanguageFeaturesQuestions {

    private static final List<Question> QUESTIONS = List.of(
            new Question("String", "Java-da String niyə immutable-dır?",
                    List.of("Performans üçün lazım deyil", "Təhlükəsizlik, thread-safety və String Pool-un səmərəli işləməsi üçün",
                            "Compiler tələb edir", "Heç bir səbəb yoxdur"), 1, Difficulty.MEDIUM),
            new Question("String", "String, StringBuilder və StringBuffer arasındakı fərq nədir?",
                    List.of("String mutable, StringBuilder immutable-dır",
                            "StringBuilder thread-safe deyil, StringBuffer thread-safe-dir, String isə immutable-dır",
                            "Fərq yoxdur", "StringBuffer immutable-dır"), 1, Difficulty.MEDIUM),
            new Question("String", "'==' operatoru ilə .equals() metodu String-lər üçün nəyə görə fərqlənir?",
                    List.of("'==' referensiyanı, equals() məzmunu müqayisə edir", "Fərq yoxdur",
                            "equals() referensiyanı müqayisə edir", "'==' həmişə true qaytarır"), 0, Difficulty.EASY),
            new Question("String", "String Pool nədir?",
                    List.of("Bütün obyektlərin saxlandığı yaddaş",
                            "JVM-in string literal-ları təkrar istifadə üçün saxladığı xüsusi yaddaş sahəsi",
                            "Fayl sistemi", "Thread pool-un digər adı"), 1, Difficulty.MEDIUM),
            new Question("String", "intern() metodu nə edir?",
                    List.of("String-i massivə çevirir", "String-i String Pool-a əlavə edir və ya oradan qaytarır",
                            "String-i böyük hərflərə çevirir", "String-i silir"), 1, Difficulty.HARD),
            new Question("String", "String.format() metodunun məqsədi nədir?",
                    List.of("String-i parçalamaq", "Şablon əsasında formatlanmış string yaratmaq",
                            "String-i şifrələmək", "String-i müqayisə etmək"), 1, Difficulty.EASY),
            new Question("String", "StringBuilder-in append() metodu nə edir?",
                    List.of("Yeni String yaradır", "Mövcud StringBuilder-ə məzmun əlavə edir (mutable)",
                            "String-i silir", "String-i tərsinə çevirir"), 1, Difficulty.EASY),
            new Question("String", "String.split() metodu nə qaytarır?",
                    List.of("Tək String", "String massivi", "List<Character>", "Boolean"), 1, Difficulty.EASY),
            new Question("String", "String.valueOf() metodunun məqsədi nədir?",
                    List.of("İstənilən tipi String-ə çevirmək", "String-i silmək",
                            "String-i şifrələmək", "String uzunluğunu ölçmək"), 0, Difficulty.EASY),
            new Question("String", "StringBuilder-in ilkin tutumu (capacity) neçədir (default konstruktorla)?",
                    List.of("0", "16", "100", "Sonsuz"), 1, Difficulty.HARD),
            new Question("String", "String-in immutable olması hash-based kolleksiyalarda (HashMap açarı) niyə üstünlükdür?",
                    List.of("Hash dəyəri sabit qaldığı üçün etibarlı açar rolunu oynayır", "Heç bir üstünlüyü yoxdur",
                            "Yalnız performans üçündür", "Yalnız kiçik string-lər üçün keçərlidir"), 0, Difficulty.MEDIUM),
            new Question("String", "String.equalsIgnoreCase() metodu nə edir?",
                    List.of("Böyük/kiçik hərfə həssas olmadan string-ləri müqayisə edir", "Yalnız uzunluğu müqayisə edir",
                            "String-i böyük hərflərə çevirir", "Heç bir işi yoxdur"), 0, Difficulty.EASY),
            new Question("String", "compareTo() metodu String-lər üçün nəyə əsasən müqayisə aparır?",
                    List.of("Leksikoqrafik (lüğəvi) sıraya", "Uzunluğa", "Hash koduna", "Heç nəyə"), 0, Difficulty.MEDIUM),
            new Question("String", "Text Block (Java 15+) string immutability-ni dəyişirmi?",
                    List.of("Xeyr, text block da String tipindədir və immutable-dır", "Bəli, mutable edir",
                            "Heç bir əlaqəsi yoxdur", "Yalnız StringBuilder ilə işləyir"), 0, Difficulty.MEDIUM),
            new Question("String", "StringBuilder-in reverse() metodu nə edir?",
                    List.of("String-in simvol ardıcıllığını tərsinə çevirir", "String-i silir",
                            "Yeni String qaytarır (immutable)", "Heç nə etmir"), 0, Difficulty.EASY),
            new Question("String", "String-lərin müqayisəsində niyə '==' əvəzinə equals() istifadə edilməlidir?",
                    List.of("'==' referensiyanı müqayisə edir, məzmun bərabərliyini yox", "equals() daha yavaşdır həmişə",
                            "Fərq yoxdur", "'==' həmişə xəta verir"), 0, Difficulty.EASY),
            new Question("String", "CharSequence interfeysi hansı siniflər tərəfindən implement olunur?",
                    List.of("String, StringBuilder, StringBuffer", "Yalnız String", "Yalnız StringBuilder", "Heç biri"),
                    0, Difficulty.MEDIUM),
            new Question("String", "String.trim() və String.strip() (Java 11+) arasındakı fərq nədir?",
                    List.of("strip() Unicode boşluqları da nəzərə alır, trim() yalnız ASCII boşluqları", "Fərq yoxdur",
                            "trim() daha yenidir", "strip() yalnız ASCII üçündür"), 0, Difficulty.MEDIUM),
            new Question("String", "String-in hashCode() metodu niyə keşlənir (cache olunur)?",
                    List.of("String immutable olduğu üçün hash dəyəri bir dəfə hesablanıb saxlanıla bilər", "Performans üçün lazım deyil",
                            "Hər çağırışda yenidən hesablanır", "Heç bir səbəb yoxdur"), 0, Difficulty.HARD),
            new Question("String", "String.chars() metodu (Java 8+) nə qaytarır?",
                    List.of("String-in simvollarının IntStream-ini", "String massivi", "Character List", "Heç nə"), 0, Difficulty.MEDIUM),

            new Question("Java 8+ Xüsusiyyətləri", "'var' açar sözü Java-da nəyi ifadə edir?",
                    List.of("Dinamik tip (JavaScript kimi)", "Compile zamanı tipin avtomatik nəticə çıxarılması (local variable type inference)",
                            "Yeni primitiv tip", "Generic wildcard"), 1, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Record (Java 14+) nədir?",
                    List.of("Dəyişən (mutable) sinif", "Immutable data daşıyan qısa yazılış formalı sinif",
                            "Interfeys növü", "Exception növü"), 1, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Sealed class (Java 17+) nəyi məhdudlaşdırır?",
                    List.of("Hansı siniflərin onu extend edə biləcəyini", "Metodların sayını",
                            "Sahələrin görünürlüyünü", "Constructor sayını"), 0, Difficulty.HARD),
            new Question("Java 8+ Xüsusiyyətləri", "Text block (\"\"\"...\"\"\") Java 15+-da nə üçün istifadə olunur?",
                    List.of("Çoxsətirli string-ləri rahat yazmaq üçün", "Şifrələmə üçün",
                            "Fayl oxumaq üçün", "Regex yazmaq üçün"), 0, Difficulty.EASY),
            new Question("Java 8+ Xüsusiyyətləri", "Switch expression (Java 14+) klassik switch-dən nə ilə fərqlənir?",
                    List.of("Dəyər qaytara bilər və fallthrough-u aradan qaldırır", "Yalnız String üçün işləyir",
                            "Fərq yoxdur", "Yalnız bir case qəbul edir"), 0, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Pattern matching for instanceof (Java 16+) nəyi asanlaşdırır?",
                    List.of("instanceof yoxlamasından sonra əlavə casting-i aradan qaldırır", "Yaddaş idarəetməsini",
                            "Thread yaratmağı", "Exception idarəetməsini"), 0, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Optional.orElseGet() və Optional.orElse() arasındakı fərq nədir?",
                    List.of("orElseGet() dəyər boş olduqda supplier-i lazy şəkildə çağırır, orElse() isə həmişə hesablanır",
                            "Fərq yoxdur", "orElse() lazy-dir", "orElseGet() həmişə null qaytarır"), 0, Difficulty.HARD),
            new Question("Java 8+ Xüsusiyyətləri", "CompletableFuture nə üçün istifadə olunur?",
                    List.of("Asinxron, qeyri-blok edən əməliyyatları idarə etmək üçün", "Statik dəyişən yaratmaq üçün",
                            "Kolleksiyanı sıralamaq üçün", "Fayl oxumaq üçün"), 0, Difficulty.HARD),
            new Question("Java 8+ Xüsusiyyətləri", "Enhanced for-each loop-da 'var' istifadəsi nəyə imkan verir?",
                    List.of("Tipin kompilyator tərəfindən avtomatik müəyyən edilməsinə", "Sonsuz dövrəyə",
                            "Massivin silinməsinə", "Heç nəyə"), 0, Difficulty.EASY),
            new Question("Java 8+ Xüsusiyyətləri", "java.time paketi (Java 8+) nəyi əvəz etmək üçün təqdim olunub?",
                    List.of("Köhnə və problemli java.util.Date/Calendar siniflərini", "String sinifini",
                            "Collections API-ni", "IO paketini"), 0, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Stream.of() metodu nə edir?",
                    List.of("Verilmiş elementlərdən Stream yaradır", "Fayl oxuyur", "Thread yaradır", "Heç bir işi yoxdur"),
                    0, Difficulty.EASY),
            new Question("Java 8+ Xüsusiyyətləri", "Java 8-də Date/Time API-də LocalDate, LocalTime və LocalDateTime arasındakı fərq nədir?",
                    List.of("LocalDate yalnız tarixi, LocalTime yalnız vaxtı, LocalDateTime hər ikisini saxlayır", "Fərq yoxdur",
                            "Hamısı eynidir", "Yalnız LocalDateTime işləyir"), 0, Difficulty.EASY),
            new Question("Java 8+ Xüsusiyyətləri", "Interface-də static metod (Java 8+) nəyə imkan verir?",
                    List.of("İnterfeys daxilində utility metodları saxlamağa, implement edən sinif olmadan çağırıla bilən",
                            "İnterfeysi final etməyə", "İnterfeysdən obyekt yaratmağa", "Heç nəyə"), 0, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "var ilə elan olunan dəyişənin tipi sonradan dəyişdirilə bilərmi?",
                    List.of("Xeyr, tip compile zamanı müəyyən olunur və sabit qalır", "Bəli, istənilən vaxt dəyişdirilə bilər",
                            "var tip anlayışını ləğv edir", "Yalnız primitiv tiplər üçün mümkündür"), 0, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Java 9-da modul sistemi (Project Jigsaw) nə üçün təqdim olunub?",
                    List.of("Tətbiqləri modullara bölərək daha yaxşı encapsulation və asılılıq idarəetməsi üçün", "Yalnız performans üçün",
                            "Yalnız test üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Java 8+ Xüsusiyyətləri", "Java 10-da 'var' yalnız hansı kontekstdə istifadə oluna bilər?",
                    List.of("Lokal dəyişənlərdə (metod daxilində)", "Sinif sahələrində", "Metod parametrlərində", "Bütün kontekstlərdə"),
                    0, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Records-da compact constructor nədir?",
                    List.of("Parametr siyahısı olmadan yalnız validasiya/normallaşdırma üçün yazılan konstruktor", "Adi konstruktor",
                            "Statik metod", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("Java 8+ Xüsusiyyətləri", "Java 17-də sealed interfeys nəyi məhdudlaşdırır?",
                    List.of("Hansı siniflərin onu implement edə biləcəyini", "Metodların sayını", "Sahələrin görünürlüyünü", "Constructor sayını"),
                    0, Difficulty.HARD),
            new Question("Java 8+ Xüsusiyyətləri", "Enhanced switch statement-də ox (->) sintaksisi hansı problemi həll edir?",
                    List.of("Fallthrough (case-lərin bir-birinə 'sızması') problemini", "Performans problemini", "Yaddaş problemini",
                            "Heç bir problemi həll etmir"), 0, Difficulty.MEDIUM),
            new Question("Java 8+ Xüsusiyyətləri", "Helpful NullPointerExceptions (Java 14+) nə edir?",
                    List.of("NPE mesajında dəqiq hansı dəyişənin null olduğunu göstərir", "NPE-ni tamamilə aradan qaldırır",
                            "Heç bir dəyişiklik etmir", "Yalnız test mühitində işləyir"), 0, Difficulty.MEDIUM),

            new Question("Stream və Lambda", "Lambda ifadəsi nədir?",
                    List.of("Anonim funksiyanın qısa yazılış forması", "Yeni sinif tipi",
                            "Statik metod", "Exception növü"), 0, Difficulty.EASY),
            new Question("Stream və Lambda", "Stream API-də 'map()' metodu nə edir?",
                    List.of("Elementləri filtr edir", "Hər elementi başqa formaya çevirir",
                            "Elementləri sıralayır", "Stream-i bağlayır"), 1, Difficulty.EASY),
            new Question("Stream və Lambda", "'filter()' və 'map()' arasındakı fərq nədir?",
                    List.of("filter() şərtə uyğun elementləri seçir, map() elementləri çevirir", "Fərq yoxdur",
                            "map() elementləri seçir", "filter() elementləri çevirir"), 0, Difficulty.EASY),
            new Question("Stream və Lambda", "Stream-lər neçə dəfə istifadə oluna bilər?",
                    List.of("Sonsuz sayda", "Yalnız bir dəfə (terminal əməliyyatdan sonra bağlanır)",
                            "İki dəfə", "Yalnız paralel rejimdə"), 1, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "'reduce()' metodunun məqsədi nədir?",
                    List.of("Stream elementlərini bir nəticəyə birləşdirmək", "Stream-i sıralamaq",
                            "Stream-i filtr etmək", "Yeni stream yaratmaq"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Functional interface nədir?",
                    List.of("Yalnız bir abstract metodu olan interfeys", "Bir neçə metodu olan sinif",
                            "Statik siniflər üçün istifadə olunan interfeys", "Generic interfeys"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Optional sinifinin məqsədi nədir?",
                    List.of("null yoxlamasını daha təhlükəsiz və aydın etmək", "Yeni thread yaratmaq",
                            "Exception atmaq", "Kolleksiyanı sıralamaq"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Stream.collect(Collectors.toList()) nə edir?",
                    List.of("Stream elementlərini List-ə toplayır", "Stream-i bağlayır",
                            "Elementləri silir", "Yeni Stream yaradır"), 0, Difficulty.EASY),
            new Question("Stream və Lambda", "Method reference (məs. String::toUpperCase) nədir?",
                    List.of("Mövcud metodu lambda əvəzinə istinad etmək üçün qısa yazılış", "Yeni metod yaratmaq",
                            "Metodu silmək", "Statik dəyişən"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Parallel stream nə vaxt istifadə edilməlidir?",
                    List.of("Böyük data həcmində, çoxnüvəli emalın faydalı olduğu hallarda", "Həmişə",
                            "Heç vaxt", "Yalnız kiçik data üçün"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Stream.sorted() metodunun default davranışı nədir?",
                    List.of("Elementləri təbii sıralama ilə (natural ordering) sıralayır", "Heç bir sıralama aparmır",
                            "Yalnız azalan sırada sıralayır", "Xəta atır"), 0, Difficulty.EASY),
            new Question("Stream və Lambda", "IntStream, DoubleStream və LongStream niyə mövcuddur?",
                    List.of("Primitiv tiplərlə işləyərkən avtoboxing overhead-indən qaçmaq üçün", "Heç bir səbəb yoxdur",
                            "Yalnız String üçün", "Yalnız kolleksiyalar üçün"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Stream.peek() metodu nə üçün istifadə olunur?",
                    List.of("Elementlərə toxunmadan aralıq addımı müşahidə etmək/debug üçün", "Elementləri silmək üçün",
                            "Yeni stream yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Collectors.groupingBy() nə edir?",
                    List.of("Stream elementlərini müəyyən açara görə qruplaşdırıb Map qaytarır", "Elementləri sıralayır",
                            "Elementləri silir", "Heç bir işi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "flatMap() və map() arasındakı fərq nədir?",
                    List.of("flatMap() iç-içə strukturları (məs. Stream<List<T>>) düzləşdirir, map() yalnız çevirir", "Fərq yoxdur",
                            "map() düzləşdirir", "flatMap() yalnız filtr edir"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Lambda ifadəsi hansı interfeysi implement edə bilər?",
                    List.of("Yalnız Functional Interface (tək abstract metodlu)", "İstənilən interfeysi", "Yalnız abstract sinifi",
                            "Heç birini"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Stream.anyMatch(), allMatch() və noneMatch() metodları nə qaytarır?",
                    List.of("Boolean nəticə, verilmiş şərtə uyğunluğa görə", "Yeni Stream", "Integer", "Heç nə"), 0, Difficulty.EASY),
            new Question("Stream və Lambda", "Stream API-də terminal əməliyyat (terminal operation) nə deməkdir?",
                    List.of("Stream-i bağlayan və nəticə istehsal edən əməliyyat (məs. collect, forEach)", "Yalnız aralıq əməliyyat",
                            "Stream yaradan əməliyyat", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Supplier, Consumer və Function functional interfeysləri arasındakı fərq nədir?",
                    List.of("Supplier heç nə qəbul etməyib dəyər qaytarır, Consumer dəyər qəbul edib heç nə qaytarmır, Function dəyər qəbul edib dəyər qaytarır",
                            "Hamısı eynidir", "Yalnız Function işləyir", "Heç bir fərqi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Stream və Lambda", "Stream.distinct() metodu nə edir?",
                    List.of("Dublikat elementləri stream-dən çıxarır (equals() əsasında)", "Elementləri sıralayır",
                            "Elementləri qruplaşdırır", "Heç bir işi yoxdur"), 0, Difficulty.EASY),

            new Question("Enum-lar", "Java-da enum nədir?",
                    List.of("Sabit dəyərlər çoxluğunu təmsil edən xüsusi sinif növü", "Adi sinif", "İnterfeys", "Exception növü"),
                    0, Difficulty.EASY),
            new Question("Enum-lar", "Enum konstantaları default olaraq necədir?",
                    List.of("public, static, final", "private, mutable", "protected, transient", "Heç bir modifikatoru yoxdur"),
                    0, Difficulty.EASY),
            new Question("Enum-lar", "Enum-da constructor ola bilərmi?",
                    List.of("Bəli, amma yalnız private (və ya paket səviyyəli) ola bilər", "Xeyr, mümkün deyil",
                            "Yalnız public ola bilər", "Constructor tələb olunmur"), 0, Difficulty.MEDIUM),
            new Question("Enum-lar", "Enum-un values() metodu nə qaytarır?",
                    List.of("Bütün enum konstantalarının massivini", "Tək konstantanı", "Boolean", "Heç nə"), 0, Difficulty.EASY),
            new Question("Enum-lar", "Enum-un valueOf() metodu nə edir?",
                    List.of("Verilmiş adla uyğun enum konstantasını qaytarır", "Yeni enum yaradır", "Enum-u silir", "Heç bir işi yoxdur"),
                    0, Difficulty.EASY),
            new Question("Enum-lar", "Enum switch statement-də necə istifadə oluna bilər?",
                    List.of("case-lərdə birbaşa konstant adı ilə (enum adı olmadan)", "İstifadə oluna bilməz", "Yalnız if-else ilə",
                            "Yalnız String kimi"), 0, Difficulty.MEDIUM),
            new Question("Enum-lar", "Enum-lar interfeys implement edə bilərmi?",
                    List.of("Bəli, enum interfeys implement edə bilər", "Xeyr, mümkün deyil", "Yalnız abstract enum edə bilər",
                            "Heç bir halda mümkün deyil"), 0, Difficulty.MEDIUM),
            new Question("Enum-lar", "Enum-un ordinal() metodu nə qaytarır?",
                    List.of("Konstantanın enum-da elan olunma sırasını (0-dan başlayaraq)", "Konstantanın adını", "Konstantanın hash kodunu",
                            "Heç nə"), 0, Difficulty.MEDIUM),
            new Question("Enum-lar", "EnumSet nədir?",
                    List.of("Enum tipləri üçün yüksək performanslı, xüsusi Set implementasiyası", "Adi HashSet", "Immutable List",
                            "Heç bir xüsusiyyəti yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Enum-lar", "Enum-da hər konstant üçün fərqli metod davranışı necə təmin edilə bilər?",
                    List.of("Hər konstanta üçün abstract metodun ayrıca implementasiyasını (constant-specific method body) yazmaqla",
                            "Mümkün deyil", "Yalnız switch ilə", "Yalnız static metodla"), 0, Difficulty.HARD),
            new Question("Enum-lar", "Enum-un name() və toString() metodları fərqlənə bilərmi?",
                    List.of("Bəli, toString() override edildikdə fərqli mətn qaytara bilər, name() isə həmişə deklarasiya adını qaytarır",
                            "Xeyr, həmişə eynidir", "Heç biri override edilə bilməz", "name() həmişə boşdur"), 0, Difficulty.MEDIUM),
            new Question("Enum-lar", "Enum-lar niyə Singleton pattern üçün effektiv üsul hesab olunur?",
                    List.of("JVM tərəfindən thread-safe, serialization-safe tək instansiya zəmanəti verilir", "Heç bir səbəb yoxdur",
                            "Enum-lar mutable-dır", "Yalnız kiçik layihələr üçün uyğundur"), 0, Difficulty.HARD),
            new Question("Enum-lar", "Enum-un compareTo() metodu nəyə əsasən müqayisə aparır?",
                    List.of("ordinal() dəyərinə (elan olunma sırasına)", "Adına əlifba sırası ilə", "hashCode-a", "Heç nəyə"),
                    0, Difficulty.MEDIUM),
            new Question("Enum-lar", "Enum-da abstract metod elan etmək mümkündürmü?",
                    List.of("Bəli, hər konstant öz implementasiyasını verməlidir", "Xeyr, mümkün deyil",
                            "Yalnız static metodlar abstract ola bilər", "Heç bir halda"), 0, Difficulty.MEDIUM),
            new Question("Enum-lar", "Enum-lar Java-da niyə heç vaxt null ola bilməz (default olaraq)?",
                    List.of("Enum dəyişəni yalnız açıq şəkildə null təyin edilməzsə enum konstantalarından biridir", "Enum-lar həmişə null-dur",
                            "Enum-lar primitiv tipdir", "Heç bir səbəb yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Enum-lar", "EnumMap adi HashMap-dən performans baxımından niyə üstündür (enum açarları üçün)?",
                    List.of("Daxili olaraq array əsaslı implementasiya istifadə edir, ordinal() dəyərinə əsaslanaraq", "Heç bir üstünlüyü yoxdur",
                            "Yalnız kiçik data üçün", "HashMap həmişə sürətlidir"), 0, Difficulty.HARD),
            new Question("Enum-lar", "Enum-da sahə (field) və metod əlavə etmək olarmı?",
                    List.of("Bəli, enum adi sinif kimi sahə və metodlara malik ola bilər", "Xeyr, yalnız konstantalar ola bilər",
                            "Yalnız static sahələr ola bilər", "Heç bir halda mümkün deyil"), 0, Difficulty.MEDIUM),
            new Question("Enum-lar", "Java-da enum-lar hansı sinifi implicit olaraq extend edir?",
                    List.of("java.lang.Enum", "Object", "Number", "Comparable"), 0, Difficulty.MEDIUM),
            new Question("Enum-lar", "Enum-un serialization-u niyə etibarlı sayılır?",
                    List.of("Java enum serialization-u xüsusi qaydada idarə edir, yalnız adı serializasiya olunur", "Enum-lar serializasiya oluna bilməz",
                            "Enum-lar həmişə transient-dir", "Heç bir səbəb yoxdur"), 0, Difficulty.HARD),
            new Question("Enum-lar", "Bir enum konstantasına eyni zamanda birdən çox interfeys implement etmək mümkündürmü (enum səviyyəsində)?",
                    List.of("Bəli, enum bir neçə interfeys implement edə bilər", "Xeyr, mümkün deyil", "Yalnız bir interfeys",
                            "Heç bir halda"), 0, Difficulty.MEDIUM),

            new Question("Functional Programming Konsepsiyaları", "Pure function (təmiz funksiya) nə deməkdir?",
                    List.of("Eyni giriş üçün həmişə eyni nəticə verən və yan-effekti olmayan funksiya", "Random nəticə verən funksiya",
                            "Statik funksiya", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Functional Programming Konsepsiyaları", "Side effect (yan-effekt) funksional proqramlaşdırmada nəyi ifadə edir?",
                    List.of("Funksiyanın öz lokal əhatəsindən kənar vəziyyəti dəyişməsi (məs. qlobal dəyişən dəyişdirmək)",
                            "Funksiyanın nəticə qaytarması", "Funksiyanın sürətli işləməsi", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Higher-order function nə deməkdir?",
                    List.of("Funksiyanı parametr kimi qəbul edən və ya funksiya qaytaran funksiya", "Yalnız statik funksiya",
                            "Yalnız private funksiya", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Immutability funksional proqramlaşdırmada niyə vacibdir?",
                    List.of("Yan-effektləri azaldaraq kodun proqnozlaşdırıla bilən və paralel icraya uyğun olmasını təmin edir",
                            "Heç bir əhəmiyyəti yoxdur", "Performansı həmişə azaldır", "Yalnız Java-ya aiddir"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Currying nə deməkdir?",
                    List.of("Çox arqumentli funksiyanı bir arqument qəbul edən funksiyalar zəncirinə çevirmək", "Funksiyanı silmək",
                            "Funksiyanı sürətləndirmək", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("Functional Programming Konsepsiyaları", "Java-da lambda ifadələri funksional proqramlaşdırmanı necə dəstəkləyir?",
                    List.of("Funksiyaları dəyər kimi ötürməyə imkan verərək (functional interface vasitəsilə)", "Heç bir dəstək vermir",
                            "Yalnız OOP dəstəkləyir", "Yalnız statik metodları əvəz edir"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Referential transparency nə deməkdir?",
                    List.of("İfadənin öz nəticəsi ilə əvəz olunmasının proqramın davranışını dəyişməməsi", "Kodun oxunaqlı olması",
                            "Dəyişənin görünürlüyü", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("Functional Programming Konsepsiyaları", "Function composition (funksiya kompozisiyası) nə edir?",
                    List.of("İki və ya daha çox funksiyanı birləşdirərək yeni funksiya yaratmaq (məs. Function.andThen())", "Funksiyaları silmək",
                            "Funksiyaları paralel işə salmaq", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Java-da Function.andThen() və Function.compose() arasındakı fərq nədir?",
                    List.of("andThen() əvvəlcə cari funksiyanı, sonra arqumenti icra edir; compose() əksinə", "Fərq yoxdur",
                            "Yalnız adları fərqlidir", "andThen() yalnız Consumer üçündür"), 0, Difficulty.HARD),
            new Question("Functional Programming Konsepsiyaları", "Recursion (rekursiya) funksional proqramlaşdırmada niyə tez-tez istifadə olunur?",
                    List.of("Dövrə (loop) əvəzinə funksiyanın özünü çağıraraq iterasiyasız həll təqdim edir", "Heç bir səbəb yoxdur",
                            "Yalnız Java-da mövcuddur", "Performans üçün həmişə daha yaxşıdır"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Tail recursion nə deməkdir?",
                    List.of("Rekursiv çağırışın funksiyanın son əməliyyatı olması, bəzi dillərdə optimallaşdırılır", "Adi rekursiya",
                            "Sonsuz rekursiya", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("Functional Programming Konsepsiyaları", "Java-da niyə tail-call optimization avtomatik təmin edilmir (bəzi funksional dillərdən fərqli olaraq)?",
                    List.of("JVM bytecode səviyyəsində bu optimallaşdırmanı dəstəkləmir", "Java tail recursion-u tamamilə qadağan edir",
                            "Heç bir səbəb yoxdur", "Yalnız static metodlarda dəstəklənir"), 0, Difficulty.HARD),
            new Question("Functional Programming Konsepsiyaları", "Monad konsepsiyası (Optional kimi) funksional proqramlaşdırmada nəyə xidmət edir?",
                    List.of("Dəyərləri (\"context\" daxilində) zəncirvari, təhlükəsiz şəkildə emal etməyə", "Yalnız exception tutmağa",
                            "Yalnız string emalına", "Heç bir məqsədə xidmət etmir"), 0, Difficulty.HARD),
            new Question("Functional Programming Konsepsiyaları", "Immutable data strukturları ilə mutable data strukturları arasındakı seçim performansa necə təsir edə bilər?",
                    List.of("Immutable strukturlar hər dəyişiklikdə yeni obyekt yaratdığı üçün əlavə yaddaş xərci ola bilər", "Heç bir fərqi yoxdur",
                            "Mutable həmişə pisdir", "Immutable həmişə sürətlidir"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Declarative (bəyan edici) proqramlaşdırma stili imperativ stildən nə ilə fərqlənir?",
                    List.of("'Nə' istənildiyini təsvir edir, 'necə' ediləcəyini deyil (məs. Stream API)", "Fərq yoxdur",
                            "Yalnız sintaksis fərqlidir", "Declarative yalnız SQL üçündür"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Lazy evaluation (tənbəl hesablama) nə deməkdir?",
                    List.of("İfadənin nəticəsinin yalnız faktiki lazım olduqda hesablanması (məs. Stream aralıq əməliyyatları)",
                            "Həmişə dərhal hesablamaq", "Heç vaxt hesablamamaq", "Yalnız static kontekstdə işləyir"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Java-da BiFunction interfeysi nəyi təmsil edir?",
                    List.of("İki arqument qəbul edib bir nəticə qaytaran funksiyanı", "Bir arqument qəbul edən funksiyanı",
                            "Heç bir arqument qəbul etməyən funksiyanı", "Yalnız boolean qaytaran funksiyanı"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Funksional proqramlaşdırmada 'first-class function' nə deməkdir?",
                    List.of("Funksiyaların dəyişənlərə mənimsədilə, parametr kimi ötürülə və qaytarıla bilməsi", "Yalnız ən vacib funksiya",
                            "Statik funksiya", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Java Stream API-nin funksional proqramlaşdırma prinsiplərinə necə uyğunlaşdığı deyilə bilər?",
                    List.of("Immutable əməliyyatlar zənciri və deklarativ üslubla data emalına imkan verir", "Heç bir uyğunluğu yoxdur",
                            "Yalnız OOP prinsiplərinə əsaslanır", "Yalnız kolleksiyaları dəyişir"), 0, Difficulty.MEDIUM),
            new Question("Functional Programming Konsepsiyaları", "Funksional proqramlaşdırmada 'idempotent' əməliyyat nə deməkdir?",
                    List.of("Əməliyyatı birdən çox dəfə tətbiq etmək nəticəni bir dəfə tətbiq etməklə eyni edir", "Heç vaxt eyni nəticə vermir",
                            "Yalnız bir dəfə icra oluna bilər", "Heç bir mənası yoxdur"), 0, Difficulty.HARD)
    );

    public static List<Question> get() {
        return QUESTIONS;
    }
}
