package repository.bank;

import model.Difficulty;
import model.Question;

import java.util.List;

public class ProcessToolsQuestions {

    private static final List<Question> QUESTIONS = List.of(
            new Question("İstisnalar", "Checked və unchecked exception arasındakı fərq nədir?",
                    List.of("Checked exception-lar compile zamanı yoxlanılır", "Unchecked exception-lar compile zamanı yoxlanılır",
                            "Fərq yoxdur", "Checked exception-lar yalnız runtime-da olur"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "finally bloku nə vaxt icra olunur?",
                    List.of("Yalnız exception atılarsa", "Yalnız exception atılmazsa",
                            "Həmişə, exception olub-olmamasından asılı olmayaraq", "Heç vaxt"), 2, Difficulty.EASY),
            new Question("İstisnalar", "Öz custom exception sinifinizi yaratmaq üçün hansı sinifi extend etməlisiniz?",
                    List.of("Throwable və ya Exception", "Object", "RuntimeError", "Error only"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "try-with-resources nə üçün istifadə olunur?",
                    List.of("Exception-ları tutmaq üçün", "Resursların avtomatik bağlanması üçün",
                            "Yeni thread yaratmaq üçün", "Statik dəyişən elan etmək üçün"), 1, Difficulty.MEDIUM),
            new Question("İstisnalar", "throw və throws açar sözləri arasındakı fərq nədir?",
                    List.of("throw exception atmaq üçün, throws metodun imzasında istisna elan etmək üçün istifadə olunur",
                            "Fərq yoxdur", "throws yalnız runtime exception üçündür", "throw metodun imzasında istifadə olunur"),
                    0, Difficulty.MEDIUM),
            new Question("İstisnalar", "NullPointerException hansı halda yaranır?",
                    List.of("Massiv indeksi hüdüddan kənara çıxdıqda", "null referensiya üzərində metod çağırıldıqda",
                            "Fayl tapılmadıqda", "Rəqəm formatı səhv olduqda"), 1, Difficulty.EASY),
            new Question("İstisnalar", "Multi-catch bloku (catch (IOException | SQLException e)) nə üçün istifadə olunur?",
                    List.of("Bir neçə exception tipini eyni blokda tutmaq üçün", "Yalnız bir exception tipini tutmaq üçün",
                            "Exception-ı yenidən atmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "StackOverflowError nə vaxt yaranır?",
                    List.of("Yaddaş kifayət etmədikdə", "Sonsuz və ya çox dərin rekursiya zamanı",
                            "Fayl tapılmadıqda", "Massiv hüdüddan kənar çıxdıqda"), 1, Difficulty.MEDIUM),
            new Question("İstisnalar", "Exception chaining (səbəb zənciri) nə üçün istifadə olunur?",
                    List.of("Orijinal xətanın səbəbini itirmədən yeni exception atmaq üçün", "Exception-ları silmək üçün",
                            "Performansı artırmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "Error və Exception arasındakı fərq nədir?",
                    List.of("Error adətən proqramın idarə edə bilmədiyi ciddi problemlər (məs. OutOfMemoryError), Exception isə tutula bilən vəziyyətlərdir",
                            "Fərq yoxdur", "Error həmişə checked-dir", "Exception yalnız runtime-dadır"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "Custom exception yaratarkən RuntimeException-dan miras almaq nə deməkdir?",
                    List.of("Unchecked exception yaratmaq, compiler onu tutmağı məcbur etmir", "Checked exception yaratmaq",
                            "Heç bir mənası yoxdur", "Exception yaratmaq mümkün olmur"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "finally blokunda return istifadə etməyin riski nədir?",
                    List.of("try/catch blokundakı return dəyərini gizlədə/əvəz edə bilər, çaşdırıcı davranışa səbəb olur", "Heç bir riski yoxdur",
                            "Performansı artırır", "Yalnız test mühitində problemdir"), 0, Difficulty.HARD),
            new Question("İstisnalar", "Checked exception-ları həddindən artıq istifadə etməyin mənfi tərəfi nədir?",
                    List.of("Kodu 'boilerplate' try-catch bloklarıyla doldurub oxunaqlılığı azalda bilər", "Heç bir mənfi tərəfi yoxdur",
                            "Performansı artırır", "Yalnız test mühitində problem yaradır"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "Exception-ı 'udmaq' (catch edib heç nə etməmək) niyə pis praktika sayılır?",
                    List.of("Problemi gizlədərək debug etməni çətinləşdirir", "Heç bir problem yaratmır", "Performansı artırır",
                            "Yalnız test mühitinə aiddir"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "IllegalArgumentException nə vaxt atılmalıdır?",
                    List.of("Metoda etibarsız və ya uyğunsuz arqument ötürüldükdə", "Fayl tapılmadıqda", "Yaddaş bitdikdə", "Heç vaxt"),
                    0, Difficulty.MEDIUM),
            new Question("İstisnalar", "IllegalStateException nə vaxt atılmalıdır?",
                    List.of("Metod obyektin cari vəziyyəti üçün uyğun olmayan zamanda çağırıldıqda", "Arqument səhv olduqda", "Fayl tapılmadıqda",
                            "Heç vaxt"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "Exception hierarchy-də Throwable-dan hansı iki əsas sinif miras alır?",
                    List.of("Exception və Error", "RuntimeException və IOException", "Yalnız Exception", "Heç biri"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "Custom exception sinifində əlavə constructor-lar (mesaj, cause ilə) yaratmağın faydası nədir?",
                    List.of("Daha çevik və məlumatlı exception yaratma imkanı verir", "Heç bir faydası yoxdur", "Performansı azaldır",
                            "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("İstisnalar", "try bloku daxilində birdən çox resurs (try-with-resources) necə bağlanır?",
                    List.of("Əlavə olunma ardıcıllığının əksinə (son əlavə olunan birinci bağlanır)", "Təsadüfi qaydada", "Heç vaxt bağlanmır",
                            "Yalnız birincisi bağlanır"), 0, Difficulty.HARD),
            new Question("İstisnalar", "Exception mesajlarının aydın və məlumatlı olması niyə vacibdir?",
                    List.of("Problemin tez diaqnoz qoyulmasına və debug edilməsinə kömək edir", "Heç bir əhəmiyyəti yoxdur",
                            "Performansı artırır", "Yalnız test mühitinə aiddir"), 0, Difficulty.EASY),

            new Question("Git və Versiya Nəzarəti", "Git nədir?",
                    List.of("Paylanmış versiya nəzarət sistemi", "Verilənlər bazası", "Proqramlaşdırma dili", "Heç bir mənası yoxdur"),
                    0, Difficulty.EASY),
            new Question("Git və Versiya Nəzarəti", "git commit əmri nə edir?",
                    List.of("Dəyişiklikləri lokal repository-ə saxlayır", "Dəyişiklikləri remote-a göndərir", "Yeni branch yaradır",
                            "Heç nə etmir"), 0, Difficulty.EASY),
            new Question("Git və Versiya Nəzarəti", "git push və git pull arasındakı fərq nədir?",
                    List.of("push lokal dəyişiklikləri remote-a göndərir, pull remote-dan dəyişiklikləri alır", "Fərq yoxdur",
                            "pull göndərir", "push alır"), 0, Difficulty.EASY),
            new Question("Git və Versiya Nəzarəti", "Git branch (budaq) nə üçün istifadə olunur?",
                    List.of("Əsas kod xəttindən ayrı, izolyasiya edilmiş şəkildə inkişaf aparmaq üçün", "Kodu silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.EASY),
            new Question("Git və Versiya Nəzarəti", "Merge conflict (birləşdirmə konflikti) nə vaxt yaranır?",
                    List.of("Eyni fayl hissəsinə fərqli branch-lərdə uyğunsuz dəyişikliklər edildikdə", "Heç vaxt",
                            "Yalnız yeni branch yaradıldıqda", "Yalnız commit edildikdə"), 0, Difficulty.MEDIUM),
            new Question("Git və Versiya Nəzarəti", "git rebase və git merge arasındakı fərq nədir?",
                    List.of("Rebase commit tarixçəsini xətti edir, merge isə birləşdirmə commit-i yaradır", "Fərq yoxdur",
                            "Merge tarixçəni xətti edir", "Rebase heç vaxt istifadə olunmur"), 0, Difficulty.MEDIUM),
            new Question("Git və Versiya Nəzarəti", "Pull Request (Merge Request) nə üçün istifadə olunur?",
                    List.of("Dəyişiklikləri əsas kod xəttinə birləşdirmədən əvvəl kod baxışı və müzakirə üçün", "Kodu silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.EASY),
            new Question("Git və Versiya Nəzarəti", ".gitignore faylı nə üçün istifadə olunur?",
                    List.of("Git-in izləməməli olduğu faylları (məs. build artefaktları) müəyyən etmək üçün", "Faylları silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.EASY),
            new Question("Git və Versiya Nəzarəti", "git stash əmri nə edir?",
                    List.of("Cari dəyişiklikləri müvəqqəti saxlayaraq işçi qovluğu təmiz vəziyyətə qaytarır", "Dəyişiklikləri silir",
                            "Yeni branch yaradır", "Heç nə etmir"), 0, Difficulty.MEDIUM),
            new Question("Git və Versiya Nəzarəti", "Git-də HEAD nəyi göstərir?",
                    List.of("Cari branch-də olan son commit-i (cari mövqeyi)", "Ən köhnə commit-i", "Remote repository-ni",
                            "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Git və Versiya Nəzarəti", "git cherry-pick əmri nə edir?",
                    List.of("Başqa branch-dən müəyyən bir commit-i cari branch-ə tətbiq edir", "Bütün branch-i birləşdirir",
                            "Heç bir işi yoxdur", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Git və Versiya Nəzarəti", "Semantic commit mesajları (məs. Conventional Commits) niyə faydalıdır?",
                    List.of("Dəyişikliklərin növünü (feat, fix, docs) aydın göstərərək tarixçəni oxunaqlı və avtomatlaşdırıla bilən edir",
                            "Heç bir faydası yoxdur", "Yalnız stil məsələsidir", "Performansı artırır"), 0, Difficulty.MEDIUM),
            new Question("Git və Versiya Nəzarəti", "Git-də fast-forward merge nə deməkdir?",
                    List.of("Hədəf branch-in mənbə branch-in birbaşa davamı olduğu üçün əlavə merge commit-i yaratmadan irəli getməsi",
                            "Konfliktli birləşmə", "Heç bir mənası yoxdur", "Yalnız rebase-ə aiddir"), 0, Difficulty.HARD),
            new Question("Git və Versiya Nəzarəti", "Git-də 'detached HEAD' vəziyyəti nə deməkdir?",
                    List.of("HEAD-in bir branch-ə deyil, birbaşa müəyyən commit-ə işarə etməsi", "Repository-nin silinməsi",
                            "Heç bir mənası yoxdur", "Yalnız yeni repository-də olur"), 0, Difficulty.HARD),
            new Question("Git və Versiya Nəzarəti", "Trunk-Based Development strategiyası nə deməkdir?",
                    List.of("Developerlərin qısa müddətli branch-lərlə tez-tez əsas (trunk) branch-ə inteqrasiya etməsi", "Heç vaxt birləşdirməmək",
                            "Yalnız bir developer üçündür", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Git və Versiya Nəzarəti", "Git Flow branching strategiyası nəyi təklif edir?",
                    List.of("develop, feature, release, hotfix kimi müəyyən məqsədli branch-lər strukturu", "Yalnız bir branch istifadə etməyi",
                            "Heç bir strukturu yoxdur", "Yalnız kiçik layihələr üçündür"), 0, Difficulty.MEDIUM),
            new Question("Git və Versiya Nəzarəti", "git blame əmri nə üçün istifadə olunur?",
                    List.of("Faylın hər sətrinin hansı commit/müəllif tərəfindən dəyişdirildiyini göstərmək üçün", "Faylı silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Git və Versiya Nəzarəti", "git reset və git revert arasındakı fərq nədir?",
                    List.of("reset tarixçəni dəyişir (təhlükəli ola bilər), revert yeni commit yaradaraq dəyişikliyi geri qaytarır (təhlükəsiz)",
                            "Fərq yoxdur", "revert tarixçəni silir", "reset yeni commit yaradır"), 0, Difficulty.HARD),
            new Question("Git və Versiya Nəzarəti", "Code review zamanı Pull Request-lərin kiçik saxlanması niyə tövsiyə olunur?",
                    List.of("Baxışı asanlaşdırır və keyfiyyətli, diqqətli review-a imkan verir", "Heç bir əhəmiyyəti yoxdur",
                            "Böyük PR-lar həmişə yaxşıdır", "Performansı artırır"), 0, Difficulty.MEDIUM),
            new Question("Git və Versiya Nəzarəti", "Git-də tag (etiket) nə üçün istifadə olunur?",
                    List.of("Müəyyən commit-i (məs. buraxılış versiyasını) qeyd etmək üçün", "Branch yaratmaq üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün"), 0, Difficulty.EASY),

            new Question("Agile və Scrum", "Agile metodologiyasının əsas prinsipi nədir?",
                    List.of("Dəyişikliyə tez uyğunlaşma və iterativ, inkremental inkişaf", "Tam əvvəlcədən planlaşdırma və dəyişməzlik",
                            "Heç bir prinsipi yoxdur", "Yalnız sənədləşməyə fokuslanmaq"), 0, Difficulty.EASY),
            new Question("Agile və Scrum", "Scrum-da Sprint nədir?",
                    List.of("Müəyyən müddətli (adətən 1-4 həftə) iş dövrü, sonunda işlək məhsul artımı verilir", "Layihənin tam müddəti",
                            "Heç bir mənası yoxdur", "Yalnız planlaşdırma mərhələsi"), 0, Difficulty.EASY),
            new Question("Agile və Scrum", "Scrum-da Product Owner-in rolu nədir?",
                    List.of("Product backlog-u idarə edib prioritetləri müəyyən etmək", "Kod yazmaq", "Testləri işə salmaq", "Heç bir rolu yoxdur"),
                    0, Difficulty.EASY),
            new Question("Agile və Scrum", "Scrum-da Daily Standup (Daily Scrum) toplantısının məqsədi nədir?",
                    List.of("Komandanın qısa sinxronizasiyası — nə edilib, nə ediləcək, əngəllər", "Uzun planlaşdırma", "Heç bir məqsədi yoxdur",
                            "Yalnız menecerlər üçündür"), 0, Difficulty.EASY),
            new Question("Agile və Scrum", "Product Backlog nədir?",
                    List.of("Məhsul üçün lazım olan bütün funksionallıqların prioritetləşdirilmiş siyahısı", "Bitmiş işlərin siyahısı",
                            "Heç bir mənası yoxdur", "Yalnız bug-ların siyahısı"), 0, Difficulty.EASY),
            new Question("Agile və Scrum", "Sprint Retrospective toplantısının məqsədi nədir?",
                    List.of("Keçən sprint-i nəzərdən keçirib komandanın prosesini yaxşılaşdırmaq üçün fikir mübadiləsi", "Kod yazmaq",
                            "Heç bir məqsədi yoxdur", "Yalnız Product Owner üçündür"), 0, Difficulty.MEDIUM),
            new Question("Agile və Scrum", "Scrum Master-in rolu nədir?",
                    List.of("Komandanın Scrum prosesini düzgün tətbiq etməsinə kömək edən, əngəlləri aradan qaldıran fasilitator", "Kod yazmaq",
                            "Prioritetləri təyin etmək", "Heç bir rolu yoxdur"), 0, Difficulty.EASY),
            new Question("Agile və Scrum", "User Story nə üçün istifadə olunur?",
                    List.of("Funksionallığı istifadəçi perspektivindən qısa, sadə formada təsvir etmək üçün", "Kod yazmaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.EASY),
            new Question("Agile və Scrum", "Kanban, Scrum-dan nə ilə fərqlənir?",
                    List.of("Kanban fasiləsiz axın (continuous flow) əsaslıdır, Scrum isə sabit müddətli sprint-lərə əsaslanır", "Fərq yoxdur",
                            "Kanban sprint istifadə edir", "Scrum axın əsaslıdır"), 0, Difficulty.MEDIUM),
            new Question("Agile və Scrum", "Story point-lər nə üçün istifadə olunur?",
                    List.of("İşin nisbi mürəkkəbliyini/həcmini qiymətləndirmək üçün (dəqiq vaxt deyil)", "Dəqiq saat hesablamaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız bug-lar üçün"), 0, Difficulty.MEDIUM),
            new Question("Agile və Scrum", "Definition of Done (DoD) nə üçün vacibdir?",
                    List.of("Bir işin 'tamamlanmış' hesab olunması üçün aydın, ortaq meyarlar təyin etmək", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız Product Owner üçündür", "Performansı artırır"), 0, Difficulty.MEDIUM),
            new Question("Agile və Scrum", "Sprint Planning toplantısında nə baş verir?",
                    List.of("Komanda növbəti sprint üçün hansı backlog elementlərinin götürüləcəyini planlaşdırır", "Kod yazılır",
                            "Heç bir plan qurulmur", "Yalnız retrospektiv aparılır"), 0, Difficulty.EASY),
            new Question("Agile və Scrum", "Velocity Scrum-da nəyi ölçür?",
                    List.of("Komandanın bir sprint-də tamamladığı iş miqdarını (adətən story point-lərlə)", "Kod sətir sayını", "Bug sayını",
                            "Heç nəyi"), 0, Difficulty.MEDIUM),
            new Question("Agile və Scrum", "Agile Manifesto-nun dəyərlərindən biri hansıdır?",
                    List.of("Fəaliyyət göstərən proqram təminatı, hərtərəfli sənədləşmədən üstün tutulur", "Sənədləşmə hər şeydən üstündür",
                            "Plan dəyişikliyə cavab verməkdən üstündür", "Alətlər insanlardan üstündür"), 0, Difficulty.MEDIUM),
            new Question("Agile və Scrum", "Sprint Review toplantısının məqsədi nədir?",
                    List.of("Sprint-də hazırlanan işi maraqlı tərəflərə (stakeholder) nümayiş etdirib feedback almaq",
                            "Komanda daxili prosesi müzakirə etmək", "Heç bir məqsədi yoxdur", "Yalnız Scrum Master üçündür"), 0, Difficulty.EASY),
            new Question("Agile və Scrum", "Backlog grooming (refinement) nə üçün aparılır?",
                    List.of("Backlog elementlərini aydınlaşdırmaq, qiymətləndirmək və prioritetləşdirmək üçün", "Kod yazmaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız sprint sonunda"), 0, Difficulty.MEDIUM),
            new Question("Agile və Scrum", "Cross-functional team (çoxfunksiyalı komanda) Scrum-da nə deməkdir?",
                    List.of("Komandanın işi tamamlamaq üçün lazım olan bütün bacarıqlara sahib olması", "Yalnız bir bacarığa malik komanda",
                            "Heç bir mənası yoxdur", "Yalnız menecerlərdən ibarət komanda"), 0, Difficulty.MEDIUM),
            new Question("Agile və Scrum", "Scrum-da 'əngəl' (impediment) nə deməkdir?",
                    List.of("Komandanın işini yavaşladan və ya dayandıran istənilən maneə", "Yeni funksionallıq", "Heç bir mənası yoxdur",
                            "Yalnız texniki problem"), 0, Difficulty.EASY),
            new Question("Agile və Scrum", "Waterfall metodologiyası Agile-dan nə ilə fərqlənir?",
                    List.of("Waterfall ardıcıl, xətti mərhələlər izləyir, Agile isə iterativ və çevikdir", "Fərq yoxdur", "Agile xəttidir",
                            "Waterfall iterativdir"), 0, Difficulty.MEDIUM),
            new Question("Agile və Scrum", "Continuous feedback (davamlı geri bildirim) Agile-da niyə vacibdir?",
                    List.of("Problemləri erkən aşkarlayıb məhsulu tələblərə uyğun tez tənzimləməyə imkan verir", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız layihə sonunda lazımdır", "Performansı azaldır"), 0, Difficulty.MEDIUM),

            new Question("Logging və Monitorinq", "Logging (loglama) nə üçün istifadə olunur?",
                    List.of("Tətbiqin işləməsi haqqında məlumat qeyd edərək debug/monitorinqi asanlaşdırmaq üçün", "Kodu sürətləndirmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.EASY),
            new Question("Logging və Monitorinq", "Log level-ləri (DEBUG, INFO, WARN, ERROR) nə üçün istifadə olunur?",
                    List.of("Log mesajlarının əhəmiyyət/ciddilik səviyyəsini fərqləndirmək üçün", "Heç bir məqsədi yoxdur", "Yalnız rəng üçün",
                            "Performans üçün"), 0, Difficulty.EASY),
            new Question("Logging və Monitorinq", "SLF4J nədir?",
                    List.of("Java üçün loglama abstraksiya təbəqəsi (facade), müxtəlif loglama kitabxanalarını birləşdirir", "Verilənlər bazası",
                            "Test framework-ü", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Structured logging (strukturlaşdırılmış loglama) nə üçün faydalıdır?",
                    List.of("Logları (məs. JSON formatında) maşın tərəfindən asanlıqla emal/axtarış edilə bilən etmək üçün", "Heç bir faydası yoxdur",
                            "Yalnız insan üçün oxunaqlıdır", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Centralized logging (mərkəzləşdirilmiş loglama, məs. ELK stack) nə üçün istifadə olunur?",
                    List.of("Çoxlu servisin loglarını bir yerdə toplayıb axtarış/analiz etmək üçün", "Logları silmək üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Application Performance Monitoring (APM) alətləri nə edir?",
                    List.of("Tətbiqin performansını (cavab müddəti, xəta nisbəti) real-vaxtda izləyir", "Kodu yazır", "Heç bir işi yoxdur",
                            "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Metrics (metrikalar) və Logs arasındakı fərq nədir?",
                    List.of("Metrics say/ölçü əsaslı aqreqasiya edilmiş data, Logs isə diskret hadisə qeydləridir", "Fərq yoxdur",
                            "Logs həmişə rəqəmdir", "Metrics mətndir"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Alerting (xəbərdarlıq) monitorinq sistemlərində nə üçün istifadə olunur?",
                    List.of("Müəyyən şərtlər (məs. xəta nisbəti artımı) baş verdikdə komandanı avtomatik xəbərdar etmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün", "Logları silmək üçün"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Correlation ID (izləmə ID-si) paylanmış sistemlərdə nə üçün istifadə olunur?",
                    List.of("Bir sorğunun çoxlu servis üzərindən keçdiyi logları birləşdirib izləmək üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız verilənlər bazası üçün", "Şifrələmə üçün"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Log rotation nə üçün lazımdır?",
                    List.of("Log fayllarının nəzarətsiz böyüyüb disk sahəsini tükətməsinin qarşısını almaq üçün", "Logları silmək üçün",
                            "Heç bir məqsədi yoxdur", "Performansı azaltmaq üçün"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Prometheus nədir?",
                    List.of("Açıq mənbəli monitorinq və alerting alət dəsti, əsasən metrics toplama üçün", "Verilənlər bazası",
                            "Proqramlaşdırma dili", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Grafana nə üçün istifadə olunur?",
                    List.of("Metrikaları vizuallaşdırmaq üçün dashboard aləti", "Log toplamaq üçün", "Kod yazmaq üçün", "Heç bir məqsədi yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Logging-də həssas məlumatları (şifrə, kredit kartı) loglamamaq niyə vacibdir?",
                    List.of("Təhlükəsizlik və məxfilik risklərinin qarşısını almaq üçün", "Heç bir əhəmiyyəti yoxdur", "Performans üçün",
                            "Yalnız test mühitinə aiddir"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Distributed tracing (paylanmış izləmə) loglamadan nə ilə fərqlənir?",
                    List.of("Bir sorğunun bütün sistemlər üzərindən keçdiyi tam yolu vizual olaraq izləyir", "Fərq yoxdur",
                            "Yalnız bir servisi izləyir", "Heç bir fərqi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Health check endpoint (məs. /actuator/health) nə üçün istifadə olunur?",
                    List.of("Tətbiqin sağlamlıq vəziyyətini avtomatik yoxlamaq üçün", "Logları silmək üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün"), 0, Difficulty.EASY),
            new Question("Logging və Monitorinq", "MDC (Mapped Diagnostic Context) loglamada nə üçün istifadə olunur?",
                    List.of("Thread-ə xas kontekst məlumatını (məs. istifadəçi ID) log mesajlarına avtomatik əlavə etmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün", "Performansı azaltmaq üçün"), 0, Difficulty.HARD),
            new Question("Logging və Monitorinq", "Log aggregation sistemlərində 'retention policy' nə üçün təyin edilir?",
                    List.of("Logların nə qədər müddət saxlanacağını müəyyən etmək üçün", "Logları dərhal silmək üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Excessive/verbose logging-in mənfi tərəfi nə ola bilər?",
                    List.of("Performansa təsir edə, disk sahəsini tükədə və vacib məlumatı 'boğa' bilər", "Heç bir mənfi tərəfi yoxdur",
                            "Həmişə faydalıdır", "Yalnız test mühitində problem yaradır"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Dashboard-larda 'SLI' (Service Level Indicator) nəyi ölçür?",
                    List.of("Xidmətin performansını əks etdirən konkret metrikanı (məs. cavab müddəti)", "Kod sətir sayını", "Heç nəyi",
                            "Yalnız test nəticələrini"), 0, Difficulty.MEDIUM),
            new Question("Logging və Monitorinq", "Monitoring və observability (müşahidə edilə bilənlik) arasındakı fərq nədir?",
                    List.of("Monitoring məlum problemləri izləyir, observability isə naməlum problemləri sistemin xarici çıxışlarından anlamağa imkan verir",
                            "Fərq yoxdur", "Eyni şeydir həmişə", "Observability yalnız log deməkdir"), 0, Difficulty.HARD),

            new Question("Xəta Loglama və Debugging Texnikaları", "Debugger nə üçün istifadə olunur?",
                    List.of("Kodu addım-addım icra edərək dəyişənləri və axını izləmək üçün", "Kodu compile etmək üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test yazmaq üçün"), 0, Difficulty.EASY),
            new Question("Xəta Loglama və Debugging Texnikaları", "Breakpoint (dayanma nöqtəsi) nə edir?",
                    List.of("Debugger-in icranı müəyyən sətirdə dayandırmasını təmin edir", "Kodu silir", "Heç bir işi yoxdur",
                            "Yalnız test üçündür"), 0, Difficulty.EASY),
            new Question("Xəta Loglama və Debugging Texnikaları", "Stack trace nədir?",
                    List.of("Exception atıldığı andakı metod çağırış zəncirinin ardıcıllığı", "Yaddaş görüntüsü", "Test nəticəsi",
                            "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Xəta Loglama və Debugging Texnikaları", "Root cause analysis (kök səbəb analizi) nə üçün aparılır?",
                    List.of("Problemin əsl, dərin səbəbini tapmaq üçün, sadəcə simptomu deyil", "Simptomu gizlətmək üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "Rubber duck debugging texnikası nə deməkdir?",
                    List.of("Kodu addım-addım kiməsə (və ya obyektə) izah edərək problemi özün aşkarlamaq", "Real debugger istifadə etmək",
                            "Heç bir mənası yoxdur", "Yalnız komanda işi üçündür"), 0, Difficulty.EASY),
            new Question("Xəta Loglama və Debugging Texnikaları", "Reproducing a bug (bug-ı təkrarlamaq) niyə vacib addımdır?",
                    List.of("Problemi etibarlı şəkildə təkrar yaratmaq olmadan onu düzgün diaqnoz qoyub düzəltmək çətindir", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız test mühitində lazımdır", "Performans üçündür"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "Conditional breakpoint nə üçün istifadə olunur?",
                    List.of("Yalnız müəyyən şərt doğru olduqda dayanmaq üçün (dövrədə müəyyən halı tapmaq)", "Həmişə dayanmaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "Remote debugging nə üçün istifadə olunur?",
                    List.of("Uzaq (production/staging) mühitdə işləyən tətbiqi lokal debugger ilə debug etmək üçün", "Yalnız lokal debug üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "Heisenbug termini nəyi ifadə edir?",
                    List.of("Debug etməyə çalışdıqda davranışı dəyişən və ya yox olan bug", "Adi, asan tapılan bug", "Heç bir mənası yoxdur",
                            "Yalnız test bug-ı"), 0, Difficulty.HARD),
            new Question("Xəta Loglama və Debugging Texnikaları", "Binary search debugging texnikası nə deməkdir?",
                    List.of("Problemin harada başladığını tapmaq üçün kod/tarixçəni yarıya bölərək sistematik axtarış aparmaq",
                            "Bütün kodu bir dəfəyə oxumaq", "Heç bir mənası yoxdur", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "git bisect əmri nə üçün istifadə olunur?",
                    List.of("Binary search istifadə edərək hansı commit-in bug-ı təqdim etdiyini tapmaq üçün", "Kodu silmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız merge üçün"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "Print/log-based debugging-in üstünlüyü nədir (debugger-ə qarşı)?",
                    List.of("Production kimi mühitlərdə, debugger qoşmaq mümkün olmadıqda işləyir", "Həmişə debugger-dən yaxşıdır",
                            "Heç bir üstünlüyü yoxdur", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "Memory leak-i aşkarlamaq üçün hansı texnika istifadə olunur?",
                    List.of("Heap dump analizi və profiling alətləri", "Yalnız stack trace oxumaq", "Heç bir texnika yoxdur",
                            "Yalnız test yazmaq"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "Race condition bug-larını debug etmək niyə xüsusilə çətindir?",
                    List.of("Nəticə thread-lərin icra sırasından asılıdır və hər dəfə fərqli ola bilər, təkrarlanması çətindir", "Heç bir çətinliyi yoxdur",
                            "Həmişə asanlıqla təkrarlanır", "Yalnız tək-thread proqramlarda olur"), 0, Difficulty.HARD),
            new Question("Xəta Loglama və Debugging Texnikaları", "Watch expression debugger-də nə üçün istifadə olunur?",
                    List.of("Müəyyən dəyişən/ifadənin dəyərini icra boyu izləmək üçün", "Kodu silmək üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "Bug tracking sistemləri (məs. Jira) nə üçün istifadə olunur?",
                    List.of("Bug-ları qeydə alıb prioritetləşdirərək izləmək üçün", "Kod yazmaq üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız test üçün"), 0, Difficulty.EASY),
            new Question("Xəta Loglama və Debugging Texnikaları", "Post-mortem (hadisədən sonrakı təhlil) analiz nə üçün aparılır?",
                    List.of("Ciddi problemdən sonra səbəbləri anlayıb gələcəkdə təkrarlanmasının qarşısını almaq üçün", "Heç bir məqsədi yoxdur",
                            "Yalnız günahkar tapmaq üçün", "Performans üçün"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "Step Into, Step Over və Step Out debugger əməliyyatları arasındakı fərq nədir?",
                    List.of("Step Into metod daxilinə girir, Step Over metodu keçir, Step Out cari metoddan çıxır", "Hamısı eynidir",
                            "Yalnız Step Into mövcuddur", "Heç bir fərqi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "Logging səviyyəsini production-da DEBUG-a keçirməyin riski nədir?",
                    List.of("Həddindən artıq log həcmi performansa təsir edə və disk sahəsini tükədə bilər", "Heç bir riski yoxdur",
                            "Performansı artırır", "Yalnız test mühitinə aiddir"), 0, Difficulty.MEDIUM),
            new Question("Xəta Loglama və Debugging Texnikaları", "Effective debugging üçün 'minimal reproducible example' yaratmağın faydası nədir?",
                    List.of("Problemi ən sadə formada izolyasiya edərək kök səbəbi tapmağı asanlaşdırır", "Heç bir faydası yoxdur",
                            "Yalnız sənədləşmə üçündür", "Performansı artırır"), 0, Difficulty.MEDIUM)
    );

    public static List<Question> get() {
        return QUESTIONS;
    }
}
