package repository.bank;

import model.Difficulty;
import model.Question;

import java.util.List;

public class SpringWebQuestions {

    private static final List<Question> QUESTIONS = List.of(
            new Question("Spring Framework Əsasları", "Spring Framework-də IoC (Inversion of Control) nəyi ifadə edir?",
                    List.of("Obyektlərin yaradılması və idarəsinin proqramçıdan konteynerə keçməsi", "Kodun sürətləndirilməsi",
                            "Verilənlər bazası idarəetməsi", "Thread idarəetməsi"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "@Autowired annotasiyası nə üçün istifadə olunur?",
                    List.of("Asılılıqların (dependency) avtomatik inject edilməsi üçün", "Sinifi final etmək üçün",
                            "Metodu test etmək üçün", "Exception tutmaq üçün"), 0, Difficulty.EASY),
            new Question("Spring Framework Əsasları", "Spring-də Bean nədir?",
                    List.of("Spring konteyneri tərəfindən idarə olunan obyekt", "Verilənlər bazası cədvəli",
                            "Exception növü", "Test sinifi"), 0, Difficulty.EASY),
            new Question("Spring Framework Əsasları", "@Component, @Service və @Repository annotasiyaları arasındakı fərq nədir?",
                    List.of("Hamısı eyni məqsədi daşıyır, amma qatları (layer) semantik olaraq fərqləndirir", "Tamamilə fərqli işlər görürlər",
                            "Yalnız @Component işləyir", "Heç bir fərq yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring Boot-un əsas üstünlüyü nədir?",
                    List.of("Auto-configuration və embedded server ilə tez başlanğıc təmin etmək", "Yalnız UI yaratmaq",
                            "Yalnız verilənlər bazası ilə işləmək", "Heç bir üstünlüyü yoxdur"), 0, Difficulty.EASY),
            new Question("Spring Framework Əsasları", "Dependency Injection-un növləri hansılardır?",
                    List.of("Constructor, Setter və Field injection", "Yalnız Constructor injection",
                            "Yalnız Field injection", "Heç biri"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "@RestController annotasiyası nə edir?",
                    List.of("Sinifi REST controller kimi işarələyir və metodların qaytardığı obyektləri JSON-a çevirir",
                            "Verilənlər bazası bağlantısı yaradır", "Testi işə salır", "Thread yaradır"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring-də Bean-in default scope-u nədir?",
                    List.of("Prototype", "Singleton", "Request", "Session"), 1, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "@Transactional annotasiyası nəyi təmin edir?",
                    List.of("Metodun tranzaksiya daxilində icra olunmasını", "Metodun sürətlənməsini",
                            "Metodun test olunmasını", "Heç nəyi"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring-də Application Context nədir?",
                    List.of("Bean-lərin yaradılması, konfiqurasiyası və idarəsi üçün IoC konteyneri", "Verilənlər bazası",
                            "Test framework-ü", "Fayl sistemi"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring-də @Qualifier annotasiyası nə üçün istifadə olunur?",
                    List.of("Eyni tipli birdən çox bean olduqda hansının inject ediləcəyini dəqiqləşdirmək üçün", "Bean-i silmək üçün",
                            "Bean-i final etmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring-də @Configuration annotasiyası nə edir?",
                    List.of("Sinifin Bean tərifləri saxlayan konfiqurasiya sinifi olduğunu bildirir", "Sinifi test edir",
                            "Sinifi silir", "Heç bir işi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring-də @Value annotasiyası nə üçün istifadə olunur?",
                    List.of("Xarici konfiqurasiya (properties/yaml) dəyərini sahəyə inject etmək üçün", "Sahəni final etmək üçün",
                            "Sahəni silmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring Data JPA nə üçün istifadə olunur?",
                    List.of("Verilənlər bazası əməliyyatlarını repository interfeysləri vasitəsilə sadələşdirmək üçün", "Yalnız UI üçün",
                            "Test üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring-də @ExceptionHandler annotasiyası nə edir?",
                    List.of("Controller-də baş verən müəyyən exception-ları mərkəzləşdirilmiş şəkildə idarə edir", "Exception-ları silir",
                            "Exception-ları gizlədir", "Heç bir işi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring-də profile (@Profile) konsepsiyası nə üçündür?",
                    List.of("Fərqli mühitlər (dev, test, prod) üçün fərqli konfiqurasiya aktivləşdirmək üçün", "İstifadəçi profili yaratmaq üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring-in Aspect-Oriented Programming (AOP) dəstəyi nə üçün istifadə olunur?",
                    List.of("Logging, təhlükəsizlik kimi köndələn (cross-cutting) məsələləri əsas biznes məntiqindən ayırmaq üçün", "Yalnız test üçün",
                            "Verilənlər bazası üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Spring Framework Əsasları", "@PostConstruct annotasiyası nə vaxt icra olunur?",
                    List.of("Bean-in bütün asılılıqları inject edildikdən sonra, istifadəyə hazır olmazdan əvvəl", "Bean yaradılmazdan əvvəl",
                            "Bean silinərkən", "Heç vaxt"), 0, Difficulty.MEDIUM),
            new Question("Spring Framework Əsasları", "Spring-də circular dependency (dövri asılılıq) problemi nə vaxt yaranır?",
                    List.of("İki və ya daha çox bean bir-birindən qarşılıqlı asılı olduqda", "Heç vaxt yaranmır",
                            "Yalnız test mühitində", "Yalnız static bean-lərdə"), 0, Difficulty.HARD),
            new Question("Spring Framework Əsasları", "Spring Boot Actuator nə üçün istifadə olunur?",
                    List.of("Tətbiqin sağlamlıq, metrika və monitorinq məlumatlarını təqdim etmək üçün", "Yalnız UI yaratmaq üçün",
                            "Test yazmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),

            new Question("REST API və Veb Servislər", "REST nə deməkdir?",
                    List.of("Representational State Transfer — resurs əsaslı memarlıq stili", "Bir proqramlaşdırma dili",
                            "Verilənlər bazası növü", "Test framework-ü"), 0, Difficulty.EASY),
            new Question("REST API və Veb Servislər", "HTTP metodlarından GET və POST arasındakı əsas fərq nədir?",
                    List.of("GET məlumat almaq, POST yeni resurs yaratmaq/göndərmək üçündür", "Fərq yoxdur",
                            "GET həmişə data dəyişir", "POST yalnız oxumaq üçündür"), 0, Difficulty.EASY),
            new Question("REST API və Veb Servislər", "HTTP status kodu 404 nəyi bildirir?",
                    List.of("Resurs tapılmadı", "Server xətası", "Uğurlu əməliyyat", "İcazə yoxdur"), 0, Difficulty.EASY),
            new Question("REST API və Veb Servislər", "PUT və PATCH HTTP metodları arasındakı fərq nədir?",
                    List.of("PUT bütün resursu əvəz edir, PATCH qismən yeniləyir", "Fərq yoxdur",
                            "PATCH resursu silir", "PUT yalnız oxumaq üçündür"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "Idempotent HTTP metodu nə deməkdir?",
                    List.of("Eyni sorğu neçə dəfə göndərilsə də nəticə eyni olur", "Sorğu heç vaxt icra olunmur",
                            "Sorğu yalnız bir dəfə göndərilə bilər", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "JSON verilənlər formatının əsas üstünlüyü nədir?",
                    List.of("Yüngül, oxunaqlı və dillərarası dəstəklənən struktur", "Yalnız Java-da işləyir",
                            "Binary formatdır", "Heç bir üstünlüyü yoxdur"), 0, Difficulty.EASY),
            new Question("REST API və Veb Servislər", "@RequestBody annotasiyası (Spring) nə edir?",
                    List.of("HTTP sorğu gövdəsini Java obyektinə çevirir", "HTTP başlığını oxuyur",
                            "URL parametrini oxuyur", "Cavab kodu təyin edir"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "API versiyalaşdırması nə üçün vacibdir?",
                    List.of("Köhnə klientləri pozmadan API-ni inkişaf etdirmək üçün", "API-ni yavaşlatmaq üçün",
                            "Heç bir səbəbi yoxdur", "Yalnız sənədləşmə üçün"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "Statelessness REST memarlığında nəyi ifadə edir?",
                    List.of("Hər sorğunun serverdə əvvəlki sorğulardan asılı olmadan, özündə bütün lazımi məlumatla icra olunması",
                            "Server-in vəziyyəti heç vaxt dəyişməməsi", "Client-in vəziyyəti saxlamaması", "Heç bir mənası yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "CORS (Cross-Origin Resource Sharing) nə üçündür?",
                    List.of("Fərqli domenlərdən gələn sorğulara icazə vermək/idarə etmək üçün brauzer təhlükəsizlik mexanizmi",
                            "Verilənlər bazası əlaqəsi üçün", "Thread idarəetməsi üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "SOAP və REST arasındakı əsas fərq nədir?",
                    List.of("SOAP protokol-əsaslı və ciddi standartlıdır, REST isə memarlıq stilidir və daha çevikdir", "Fərq yoxdur",
                            "REST daha köhnədir", "SOAP yalnız JSON istifadə edir"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "HATEOAS REST memarlığında nəyi ifadə edir?",
                    List.of("API cavablarında növbəti mümkün əməliyyatlara keçidlərin (link) daxil edilməsi", "Yalnız autentifikasiya",
                            "Yalnız şifrələmə", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("REST API və Veb Servislər", "HTTP 500 status kodu nəyi bildirir?",
                    List.of("Server daxili xətası", "Uğurlu əməliyyat", "Resurs tapılmadı", "İcazə yoxdur"), 0, Difficulty.EASY),
            new Question("REST API və Veb Servislər", "HTTP 201 status kodu adətən hansı əməliyyatdan sonra qaytarılır?",
                    List.of("Yeni resursun uğurla yaradılması (POST)", "Resursun silinməsi", "Resursun oxunması", "Xəta"), 0, Difficulty.EASY),
            new Question("REST API və Veb Servislər", "Pagination (səhifələmə) REST API-lərdə nə üçün vacibdir?",
                    List.of("Böyük data dəstlərini kiçik, idarə oluna bilən hissələrlə qaytararaq performansı yaxşılaşdırmaq üçün",
                            "Heç bir əhəmiyyəti yoxdur", "Yalnız UI üçündür", "Data itkisinə səbəb olur"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "REST API-də DELETE metodu idempotent hesab olunurmu?",
                    List.of("Bəli, eyni resursu bir neçə dəfə silmək eyni nəticə (resurs yoxdur) ilə nəticələnir", "Xeyr",
                            "Yalnız POST idempotentdir", "Heç bir metod idempotent deyil"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "API Gateway nə üçün istifadə olunur?",
                    List.of("Mikroservislərə gələn sorğuları mərkəzləşdirilmiş şəkildə idarə etmək (routing, auth, rate limiting) üçün",
                            "Yalnız verilənlər bazası üçün", "Yalnız UI üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "Rate limiting API-lərdə nə üçün tətbiq olunur?",
                    List.of("Klientin müəyyən müddətdə edə biləcəyi sorğu sayını məhdudlaşdıraraq sistemi qorumaq üçün", "Heç bir səbəb yoxdur",
                            "API-ni sürətləndirmək üçün", "Yalnız test üçün"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "GraphQL REST-dən nə ilə fərqlənir?",
                    List.of("Klient dəqiq hansı sahələrin qaytarılacağını sorğuda özü müəyyən edə bilir (over/under-fetching problemi azalır)",
                            "Fərq yoxdur", "GraphQL yalnız mutasiya üçündür", "REST daha çevikdir həmişə"), 0, Difficulty.MEDIUM),
            new Question("REST API və Veb Servislər", "Webhook nədir?",
                    List.of("Müəyyən hadisə baş verdikdə serverin klient tərəfindən qeydiyyatdan keçirilmiş URL-ə avtomatik HTTP sorğusu göndərməsi",
                            "Yalnız GET sorğusu", "Verilənlər bazası", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),

            new Question("WebSocket və Real-vaxt Kommunikasiya", "WebSocket protokolu HTTP-dən nə ilə fərqlənir?",
                    List.of("Tam-dupleks (full-duplex), davamlı bağlantı təmin edir, HTTP isə sorğu-cavab modelidir", "Fərq yoxdur",
                            "WebSocket yalnız GET dəstəkləyir", "HTTP daha sürətlidir həmişə"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "WebSocket bağlantısı necə başlayır (handshake)?",
                    List.of("HTTP Upgrade sorğusu ilə, sonra protokol WebSocket-ə keçir", "Birbaşa TCP ilə, HTTP olmadan",
                            "FTP protokolu ilə", "Heç bir handshake tələb olunmur"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "WebSocket-in tipik istifadə sahələrinə hansı aiddir?",
                    List.of("Chat tətbiqləri, canlı bildirişlər, real-vaxt oyunlar", "Statik veb səhifələr", "Fayl arxivləşdirmə",
                            "Batch emalı"), 0, Difficulty.EASY),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "Server-Sent Events (SSE) WebSocket-dən nə ilə fərqlənir?",
                    List.of("SSE yalnız server-dən klientə birtərəfli axın təmin edir, WebSocket ikitərəflidir", "Fərq yoxdur",
                            "SSE ikitərəflidir", "WebSocket yalnız birtərəflidir"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "Spring-də WebSocket dəstəyi üçün hansı annotasiya istifadə olunur?",
                    List.of("@EnableWebSocket və ya STOMP üçün @EnableWebSocketMessageBroker", "@RestController yalnız", "@Repository",
                            "Heç biri"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "STOMP protokolu nə üçün WebSocket üzərində istifadə olunur?",
                    List.of("Mesajlaşma üçün strukturlaşdırılmış, sub-protokol səviyyəsi əlavə edir (topic/queue modeli)", "Yalnız şifrələmə üçün",
                            "Yalnız autentifikasiya üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "WebSocket bağlantısının uzun müddət açıq qalması hansı resurs riskini yaradır?",
                    List.of("Server tərəfində çoxlu açıq bağlantı yaddaş/resurs istehlakını artıra bilər", "Heç bir risk yoxdur",
                            "Yalnız klient tərəfində risk var", "Risk yalnız test mühitindədir"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "Long polling nədir?",
                    List.of("Klientin sorğunu göndərib server yeni data olana qədər cavabı gecikdirdiyi real-vaxt simulyasiya texnikası",
                            "WebSocket-in digər adı", "Yalnız POST sorğusu", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "WebSocket-də mesaj broker (message broker) rolu nədir?",
                    List.of("Mesajları abunəçilər arasında marşrutlaşdırmaq (məs. topic əsaslı yayım)", "Bağlantını bağlamaq",
                            "Yalnız şifrələmə", "Heç bir rolu yoxdur"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "WebSocket bağlantısında təhlükəsizlik (autentifikasiya) necə təmin edilə bilər?",
                    List.of("Handshake zamanı token yoxlaması və ya sessiya əsaslı autentifikasiya ilə", "Heç bir üsulla təmin edilə bilməz",
                            "WebSocket avtomatik təhlükəsizdir", "Yalnız HTTPS kifayətdir"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "Socket.IO nədir?",
                    List.of("WebSocket üzərində əlavə funksionallıq (fallback, otaqlar) təqdim edən kitabxana", "Java-nın daxili sinifi",
                            "Verilənlər bazası", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "WebSocket vasitəsilə göndərilən mesajlar hansı formatda ola bilər?",
                    List.of("Mətn (text) və ya binary", "Yalnız JSON", "Yalnız XML", "Yalnız binary"), 0, Difficulty.EASY),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "Real-vaxt tətbiqlərdə 'heartbeat' mesajları nə üçün istifadə olunur?",
                    List.of("Bağlantının canlı olduğunu təsdiqləmək və qırılmaları erkən aşkarlamaq üçün", "Data ötürmək üçün",
                            "Şifrələmə üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "Fərqli server instansiyaları arasında WebSocket mesajlarını necə paylaşmaq olar (horizontal scaling)?",
                    List.of("Xarici mesaj broker (məs. Redis Pub/Sub, RabbitMQ) istifadə edərək", "Mümkün deyil",
                            "Yalnız bir server instansiyası ola bilər", "Heç bir üsul yoxdur"), 0, Difficulty.HARD),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "WebSocket-in CORS ilə əlaqəsi nədir?",
                    List.of("Cross-origin WebSocket bağlantıları da brauzer tərəfindən nəzarət oluna bilər (Origin header yoxlaması)",
                            "Heç bir əlaqəsi yoxdur", "WebSocket CORS-a tabe deyil həmişə", "Yalnız HTTP-yə aiddir"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "Reconnection strategiyası WebSocket klientlərində niyə vacibdir?",
                    List.of("Şəbəkə kəsintisi zamanı avtomatik yenidən qoşulma təmin edərək istifadəçi təcrübəsini yaxşılaşdırır",
                            "Heç bir əhəmiyyəti yoxdur", "Yalnız server tərəfində lazımdır", "Heç vaxt lazım deyil"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "WebSocket protokolunun URL sxemi nədir?",
                    List.of("ws:// (və təhlükəsiz üçün wss://)", "http://", "ftp://", "tcp://"), 0, Difficulty.EASY),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "Real-vaxt bildirişlər üçün push notification WebSocket-dən nə ilə fərqlənir?",
                    List.of("Push notification tətbiq açıq olmasa belə OS səviyyəsində çatdırılır, WebSocket isə aktiv bağlantı tələb edir",
                            "Fərq yoxdur", "WebSocket tətbiq bağlı olanda da işləyir", "Heç bir fərqi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "Backpressure (əks təzyiq) real-vaxt streaming sistemlərində nəyi ifadə edir?",
                    List.of("İstehlakçının emal edə biləcəyindən çox sürətli data axını olduqda yaranan idarəetmə problemi", "Şəbəkə sürəti",
                            "Server yükü", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("WebSocket və Real-vaxt Kommunikasiya", "WebSocket bağlantısı bağlandıqda (close event) hansı məlumat ötürülür?",
                    List.of("Bağlanma kodu (close code) və izahedici mesaj", "Heç bir məlumat", "Yalnız boolean", "Yalnız timestamp"),
                    0, Difficulty.MEDIUM),

            new Question("API Dizaynı və Sənədləşmə", "OpenAPI (Swagger) specification nə üçün istifadə olunur?",
                    List.of("REST API-lərin strukturunu standart, maşın tərəfindən oxuna bilən formatda təsvir etmək üçün", "Yalnız test üçün",
                            "Verilənlər bazası üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("API Dizaynı və Sənədləşmə", "API dizaynında 'resource naming' üçün REST konvensiyası nə tövsiyə edir?",
                    List.of("Cəm isimlərdən istifadə (məs. /users, /orders)", "Fellərdən istifadə (məs. /getUsers)", "Heç bir konvensiya yoxdur",
                            "Yalnız böyük hərflərlə"), 0, Difficulty.EASY),
            new Question("API Dizaynı və Sənədləşmə", "API versiyalaşdırmasının ümumi üsullarından biri hansıdır?",
                    List.of("URL-də versiya nömrəsi (məs. /api/v1/users)", "Yalnız cavab kodunda", "Yalnız fayl adında", "Heç bir üsul yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("API Dizaynı və Sənədləşmə", "Swagger UI nə təqdim edir?",
                    List.of("API sənədləşməsini interaktiv, brauzerdə sınaq imkanı ilə göstərir", "Yalnız statik sənəd", "Test yazmaq",
                            "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("API Dizaynı və Sənədləşmə", "API dizaynında 'contract-first' yanaşması nə deməkdir?",
                    List.of("Əvvəlcə API kontraktını (spesifikasiyasını) təyin edib sonra implementasiya etmək", "Əvvəlcə kod yazıb sonra sənədləşdirmək",
                            "Heç bir mənası yoxdur", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("API Dizaynı və Sənədləşmə", "API-lərdə error response formatının standartlaşdırılması (məs. RFC 7807 Problem Details) nə üçün faydalıdır?",
                    List.of("Klientlərin xətaları ardıcıl, proqnozlaşdırıla bilən şəkildə emal etməsini təmin edir", "Heç bir faydası yoxdur",
                            "Yalnız görünüş üçündür", "Performansı azaldır"), 0, Difficulty.MEDIUM),
            new Question("API Dizaynı və Sənədləşmə", "API dokumentasiyasında 'request/response examples' niyə vacibdir?",
                    List.of("Developerlərin API-ni necə istifadə edəcəyini praktik nümunələrlə tez anlamasına kömək edir", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız marketinq üçündür", "Performansı artırır"), 0, Difficulty.EASY),
            new Question("API Dizaynı və Sənədləşmə", "API-də backward compatibility (geriyə uyğunluq) nəyi ifadə edir?",
                    List.of("Yeni versiyanın köhnə klientləri pozmaması", "Köhnə klientlərin dəstəklənməməsi", "Heç bir mənası yoxdur",
                            "Yalnız yeni klientlərə aiddir"), 0, Difficulty.MEDIUM),
            new Question("API Dizaynı və Sənədləşmə", "API Design-First vs Code-First yanaşmalarının fərqi nədir?",
                    List.of("Design-First əvvəlcə spesifikasiya yazır, Code-First əvvəlcə kod yazıb sonra spesifikasiya generasiya edir",
                            "Fərq yoxdur", "Code-First həmişə daha yaxşıdır", "Design-First yalnız kiçik layihələr üçündür"), 0, Difficulty.MEDIUM),
            new Question("API Dizaynı və Sənədləşmə", "REST API-də HTTP status kodlarının düzgün istifadəsi niyə vacibdir?",
                    List.of("Klientlərin nəticəni proqram vasitəsilə düzgün emal etməsinə imkan verir (standart semantika)", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız sənədləşmə üçündür", "Performansı artırır"), 0, Difficulty.MEDIUM),
            new Question("API Dizaynı və Sənədləşmə", "API-lərdə HATEOAS-ın praktikada az istifadə olunmasının səbəbi nə ola bilər?",
                    List.of("Əlavə mürəkkəblik gətirir və çoxu real dünya API-si üçün faydası aydın deyil", "Həmişə istifadə olunur",
                            "Heç bir səbəb yoxdur", "Yalnız köhnə API-lərdə istifadə olunur"), 0, Difficulty.HARD),
            new Question("API Dizaynı və Sənədləşmə", "API sənədləşməsində 'deprecated' işarəsi nə bildirir?",
                    List.of("Endpoint-in gələcəkdə silinəcəyini və istifadəsinin tövsiyə edilmədiyini", "Endpoint-in yeni olduğunu",
                            "Endpoint-in ən sürətli olduğunu", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("API Dizaynı və Sənədləşmə", "API Rate Limit haqqında məlumat adətən hansı yolla klientə bildirilir?",
                    List.of("HTTP response header-ləri ilə (məs. X-RateLimit-Remaining)", "Yalnız sənədləşmədə", "Heç vaxt bildirilmir",
                            "Yalnız email ilə"), 0, Difficulty.MEDIUM),
            new Question("API Dizaynı və Sənədləşmə", "API dizaynında idempotency key konsepsiyası nə üçün istifadə olunur?",
                    List.of("Eyni sorğunun təsadüfən təkrar göndərilməsi zamanı əməliyyatın yalnız bir dəfə tətbiq olunmasını təmin etmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız GET üçündür", "Performansı artırmaq üçün"), 0, Difficulty.HARD),
            new Question("API Dizaynı və Sənədləşmə", "OpenAPI spesifikasiyasından avtomatik client SDK generasiya etmək mümkündürmü?",
                    List.of("Bəli, bir çox alət (məs. OpenAPI Generator) bunu dəstəkləyir", "Xeyr, mümkün deyil",
                            "Yalnız Java üçün mümkündür", "Heç bir alət yoxdur"), 0, Difficulty.MEDIUM),
            new Question("API Dizaynı və Sənədləşmə", "API-lərdə 'breaking change' nəyi ifadə edir?",
                    List.of("Mövcud klientlərin işini pozacaq dəyişiklik (məs. sahə silmək, tip dəyişmək)", "Kiçik bug fix",
                            "Yeni endpoint əlavə etmək", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("API Dizaynı və Sənədləşmə", "API dizaynında konsistent (ardıcıl) adlandırma niyə vacibdir?",
                    List.of("Developerlərin API-ni proqnozlaşdırıla bilən şəkildə öyrənməsini asanlaşdırır", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız stil məsələsidir", "Performansı artırır"), 0, Difficulty.EASY),
            new Question("API Dizaynı və Sənədləşmə", "API-lərdə sorğu parametrlərinin (query parameters) filtrasiya üçün istifadəsinə nümunə hansıdır?",
                    List.of("GET /users?status=active", "POST /users/filter/active", "DELETE /users?active", "Heç biri"), 0, Difficulty.EASY),
            new Question("API Dizaynı və Sənədləşmə", "Postman kolleksiyaları API test və sənədləşməsində nə üçün istifadə olunur?",
                    List.of("Sorğuları təşkil edib paylaşaraq API-ni test etmək və nümunə göstərmək üçün", "Yalnız verilənlər bazası üçün",
                            "Kodu compile etmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("API Dizaynı və Sənədləşmə", "API dizaynında 'sparse fieldsets' konsepsiyası nə edir?",
                    List.of("Klientin cavabda yalnız lazım olan sahələri sorğulamasına imkan verir (over-fetching-i azaldır)",
                            "Bütün sahələri həmişə qaytarır", "Heç bir mənası yoxdur", "Yalnız POST üçündür"), 0, Difficulty.MEDIUM),

            new Question("Autentifikasiya və Avtorizasiya", "Autentifikasiya (authentication) və avtorizasiya (authorization) arasındakı fərq nədir?",
                    List.of("Autentifikasiya kimliyi təsdiqləyir, avtorizasiya isə nəyə icazəli olduğunu müəyyən edir", "Fərq yoxdur",
                            "Avtorizasiya kimliyi təsdiqləyir", "Eyni şeydir həmişə"), 0, Difficulty.EASY),
            new Question("Autentifikasiya və Avtorizasiya", "JWT (JSON Web Token) nədən ibarətdir?",
                    List.of("Header, Payload və Signature hissələrindən", "Yalnız Payload-dan", "Yalnız şifrələnmiş mətndən",
                            "Heç bir strukturu yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "JWT-nin stateless (vəziyyətsiz) olması nə üstünlük verir?",
                    List.of("Server sessiya məlumatını saxlamağa ehtiyac duymur, horizontal scaling asanlaşır", "Heç bir üstünlüyü yoxdur",
                            "Token həmişə server-də saxlanmalıdır", "Yalnız kiçik tətbiqlər üçün uyğundur"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "OAuth2 protokolunun əsas məqsədi nədir?",
                    List.of("İstifadəçinin parolunu paylaşmadan üçüncü tərəf tətbiqlərə məhdud giriş icazəsi vermək", "Şifrələmə alqoritmi",
                            "Verilənlər bazası protokolu", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "OAuth2-də 'access token' və 'refresh token' arasındakı fərq nədir?",
                    List.of("Access token qısa müddətli giriş üçün, refresh token yeni access token almaq üçün istifadə olunur", "Fərq yoxdur",
                            "Refresh token daha qısa ömürlüdür", "Access token heç vaxt bitmir"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "Spring Security-də autentifikasiya prosesini idarə edən əsas interfeys hansıdır?",
                    List.of("AuthenticationManager", "RestController", "Repository", "Service"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "Role-Based Access Control (RBAC) nə deməkdir?",
                    List.of("İstifadəçilərə rol təyin edilib, icazələrin rollar əsasında idarə edilməsi", "Hər istifadəçiyə ayrıca icazə vermək",
                            "Heç bir icazə sistemi olmaması", "Yalnız admin girişi"), 0, Difficulty.EASY),
            new Question("Autentifikasiya və Avtorizasiya", "Şifrələrin verilənlər bazasında saxlanması üçün niyə hashing (məs. bcrypt) istifadə olunur?",
                    List.of("Şifrələrin açıq mətn kimi saxlanmasının qarşısını alaraq təhlükəsizliyi artırmaq üçün", "Performans üçün",
                            "Yaddaşı azaltmaq üçün", "Heç bir səbəb yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "CSRF (Cross-Site Request Forgery) həmləsi nədir?",
                    List.of("İstifadəçinin bilmədən icazəsiz sorğu göndərməyə məcbur edilməsi", "SQL injection növü",
                            "Şəbəkə kəsintisi", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "Session-based autentifikasiya JWT-based autentifikasiyadan nə ilə fərqlənir?",
                    List.of("Session server tərəfində vəziyyət saxlayır, JWT isə stateless-dir", "Fərq yoxdur",
                            "JWT server tərəfində saxlanır", "Session heç vaxt bitmir"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "OAuth2-də 'Authorization Code' grant type nə üçün istifadə olunur?",
                    List.of("Server tərəfli tətbiqlərdə təhlükəsiz şəkildə access token əldə etmək üçün", "Yalnız mobil tətbiqlər üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız test üçün"), 0, Difficulty.HARD),
            new Question("Autentifikasiya və Avtorizasiya", "Two-Factor Authentication (2FA) nəyi təmin edir?",
                    List.of("Şifrədən əlavə ikinci təsdiq faktoru (məs. SMS kod) tələb edərək təhlükəsizliyi artırır", "Heç bir əlavə təhlükəsizlik vermir",
                            "Şifrəni əvəz edir", "Yalnız korporativ tətbiqlər üçündür"), 0, Difficulty.EASY),
            new Question("Autentifikasiya və Avtorizasiya", "Spring Security-də @PreAuthorize annotasiyası nə edir?",
                    List.of("Metod çağırılmazdan əvvəl icazə şərtini yoxlayır", "Metodu final edir", "Metodu silir", "Heç bir işi yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "Single Sign-On (SSO) nə üçün istifadə olunur?",
                    List.of("İstifadəçinin bir dəfə giriş edərək bir neçə əlaqəli tətbiqə çıxış əldə etməsi üçün", "Hər tətbiq üçün ayrı giriş tələb etmək üçün",
                            "Heç bir məqsədi yoxdur", "Yalnız mobil tətbiqlər üçün"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "OpenID Connect OAuth2-dən nə ilə fərqlənir?",
                    List.of("OAuth2 üzərində qurulmuş autentifikasiya qatıdır (kimliyi təsdiqləyir), OAuth2 isə əsasən avtorizasiya üçündür",
                            "Fərq yoxdur", "OpenID Connect avtorizasiya üçündür", "Heç bir əlaqəsi yoxdur"), 0, Difficulty.HARD),
            new Question("Autentifikasiya və Avtorizasiya", "API açarları (API keys) autentifikasiyanın hansı formasıdır?",
                    List.of("Sadə, statik token əsaslı identifikasiya üsulu", "Ən təhlükəsiz üsul həmişə", "Yalnız OAuth2-yə aiddir",
                            "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "Principle of Least Privilege (ən az imtiyaz prinsipi) nə deməkdir?",
                    List.of("İstifadəçi/sistemə yalnız işini görmək üçün minimum lazım olan icazələri vermək", "Bütün icazələri vermək",
                            "Heç bir icazə verməmək", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "JWT token-in etibarlılıq müddəti (expiration) niyə vacibdir?",
                    List.of("Oğurlanmış token-in uzun müddət istifadə oluna bilməsinin qarşısını alır", "Heç bir əhəmiyyəti yoxdur",
                            "Performansı artırır", "Yalnız test üçündür"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "Basic Authentication-un təhlükəsizlik baxımından zəif tərəfi nədir?",
                    List.of("İstifadəçi adı/şifrə hər sorğuda base64 (asanlıqla deşifrə oluna bilən) formatda göndərilir", "Heç bir zəif tərəfi yoxdur",
                            "Ən təhlükəsiz üsuldur", "Şifrələnmiş göndərilir həmişə"), 0, Difficulty.MEDIUM),
            new Question("Autentifikasiya və Avtorizasiya", "Avtorizasiya yoxlaması yalnız frontend-də (klient tərəfində) aparılması niyə təhlükəlidir?",
                    List.of("Klient tərəfli yoxlama asanlıqla keçilə bilər, backend-də də mütləq yoxlama olmalıdır", "Heç bir təhlükə yoxdur",
                            "Frontend yoxlaması kifayətdir həmişə", "Backend yoxlaması lazımsızdır"), 0, Difficulty.MEDIUM)
    );

    public static List<Question> get() {
        return QUESTIONS;
    }
}
