package repository.bank;

import model.Difficulty;
import model.Question;

import java.util.List;

public class TestingQualityQuestions {

    private static final List<Question> QUESTIONS = List.of(
            new Question("Testing", "JUnit-də @Test annotasiyası nə üçün istifadə olunur?",
                    List.of("Metodun test metodu olduğunu bildirmək üçün", "Sinifi abstrakt etmək üçün",
                            "Metodu private etmək üçün", "Exception atmaq üçün"), 0, Difficulty.EASY),
            new Question("Testing", "@BeforeEach annotasiyası nə vaxt icra olunur?",
                    List.of("Bütün testlərdən əvvəl bir dəfə", "Hər testdən əvvəl",
                            "Bütün testlərdən sonra", "Heç vaxt"), 1, Difficulty.EASY),
            new Question("Testing", "Mock obyekt nə üçün istifadə olunur?",
                    List.of("Real asılılıqları simulyasiya edərək təcrid olunmuş test yazmaq üçün", "Verilənlər bazasına qoşulmaq üçün",
                            "Performansı artırmaq üçün", "Kodu compile etmək üçün"), 0, Difficulty.MEDIUM),
            new Question("Testing", "assertEquals() metodu nə edir?",
                    List.of("İki dəyərin bərabər olub-olmadığını yoxlayır", "İki dəyəri toplayır",
                            "Exception atır", "Testi dayandırır"), 0, Difficulty.EASY),
            new Question("Testing", "Unit test və Integration test arasındakı fərq nədir?",
                    List.of("Unit test bir komponenti təcrid şəkildə, integration test isə komponentlərin birgə işini test edir",
                            "Fərq yoxdur", "Integration test daha sürətlidir", "Unit test verilənlər bazasını yoxlayır"),
                    0, Difficulty.MEDIUM),
            new Question("Testing", "assertThrows() nə üçün istifadə olunur?",
                    List.of("Metodun müəyyən exception atdığını yoxlamaq üçün", "Metodun sürətini ölçmək üçün",
                            "Metodu dayandırmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Testing", "Test coverage (kod əhatəsi) nəyi göstərir?",
                    List.of("Kodun neçə faizinin testlərlə əhatə olunduğunu", "Testlərin sürətini",
                            "Bug sayını", "Sinif sayını"), 0, Difficulty.EASY),
            new Question("Testing", "TDD (Test-Driven Development) yanaşmasının əsas prinsipi nədir?",
                    List.of("Əvvəlcə testi yazmaq, sonra onu keçən kodu yazmaq", "Əvvəlcə kodu yazmaq, sonra test yazmaq",
                            "Test yazmamaq", "Yalnız manual test etmək"), 0, Difficulty.MEDIUM),
            new Question("Testing", "@Mock və @InjectMocks annotasiyaları (Mockito) nə üçün istifadə olunur?",
                    List.of("Mock obyektlər yaratmaq və onları test olunan sinifə inject etmək üçün", "Verilənlər bazası qoşulması üçün",
                            "Performans testi üçün", "UI testi üçün"), 0, Difficulty.MEDIUM),
            new Question("Testing", "Parametrized test nə üçün istifadə olunur?",
                    List.of("Eyni test metodunu fərqli giriş dəyərləri ilə dəfələrlə işlətmək üçün", "Testi yavaşlatmaq üçün",
                            "Yalnız bir dəyərlə test etmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Testing", "@AfterEach annotasiyası nə vaxt icra olunur?",
                    List.of("Hər testdən sonra", "Bütün testlərdən sonra bir dəfə", "Hər testdən əvvəl", "Heç vaxt"), 0, Difficulty.EASY),
            new Question("Testing", "@BeforeAll və @AfterAll annotasiyaları (JUnit 5) nə vaxt icra olunur və hansı şərtlə?",
                    List.of("Bütün testlərdən əvvəl/sonra bir dəfə, adətən static metod olmalıdır", "Hər testdən əvvəl/sonra",
                            "Heç vaxt", "Yalnız instance metodları ola bilər"), 0, Difficulty.MEDIUM),
            new Question("Testing", "Test Pyramid konsepsiyası nəyi tövsiyə edir?",
                    List.of("Çox sayda sürətli unit test, az sayda integration/UI test", "Yalnız UI testlər",
                            "Yalnız manual testlər", "Heç bir tövsiyəsi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Testing", "Stub və Mock arasındakı fərq nədir?",
                    List.of("Stub sadə, əvvəlcədən təyin olunmuş cavab verir; Mock çağırışların gözləntilərini yoxlayır", "Fərq yoxdur",
                            "Mock heç vaxt istifadə olunmur", "Stub yalnız verilənlər bazası üçündür"), 0, Difficulty.HARD),
            new Question("Testing", "@Disabled (JUnit 5) annotasiyası nə edir?",
                    List.of("Testi müvəqqəti deaktiv edir", "Testi silir", "Testi sürətləndirir", "Heç bir işi yoxdur"), 0, Difficulty.EASY),
            new Question("Testing", "Code coverage 100% olması nəyi zəmanət etmir?",
                    List.of("Kodun bütün mümkün ssenarilər üçün düzgün işlədiyini (yalnız sətirlərin icra olunduğunu göstərir)", "Heç nə",
                            "Bütün testlərin keçdiyini", "Kompilyasiyanın uğurlu olduğunu"), 0, Difficulty.MEDIUM),
            new Question("Testing", "Test Doubles kateqoriyasına hansı daxildir?",
                    List.of("Dummy, Fake, Stub, Spy, Mock", "Yalnız Mock", "Yalnız Stub", "Heç biri"), 0, Difficulty.HARD),
            new Question("Testing", "Integration test nə vaxt yazılmalıdır?",
                    List.of("Fərqli komponentlərin (məs. verilənlər bazası, API) birgə düzgün işlədiyini yoxlamaq üçün", "Yalnız bir metodu test etmək üçün",
                            "Heç vaxt lazım deyil", "Yalnız UI üçün"), 0, Difficulty.MEDIUM),
            new Question("Testing", "assertAll() metodu (JUnit 5) nə üçün istifadə olunur?",
                    List.of("Bir neçə assertion-u qruplaşdıraraq hamısını icra edib bütün uğursuzluqları birlikdə göstərmək üçün",
                            "Yalnız bir assertion üçün", "Testi dayandırmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Testing", "Test Isolation (test təcridi) nə üçün vacibdir?",
                    List.of("Testlərin bir-birindən asılı olmadan, istənilən ardıcıllıqla düzgün işləməsini təmin etmək üçün", "Testləri yavaşlatmaq üçün",
                            "Heç bir əhəmiyyəti yoxdur", "Yalnız performans üçün"), 0, Difficulty.MEDIUM),

            new Question("Kod Keyfiyyəti və Clean Code", "Code smell nə deməkdir?",
                    List.of("Kodda potensial problemi göstərən əlamət (mütləq bug olmasa da)", "Kompilyasiya xətası",
                            "Runtime exception", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "DRY prinsipi nəyi ifadə edir?",
                    List.of("Don't Repeat Yourself — kod təkrarından qaçmaq", "Kodu qısa yazmaq",
                            "Yalnız şərhlərdən istifadə etmək", "Heç bir mənası yoxdur"), 0, Difficulty.EASY),
            new Question("Kod Keyfiyyəti və Clean Code", "Code review-un əsas məqsədi nədir?",
                    List.of("Kodun keyfiyyətini, düzgünlüyünü yoxlamaq və bilik paylaşımını təmin etmək", "Yalnız bugları tapmaq",
                            "Yalnız performansı ölçmək", "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("Kod Keyfiyyəti və Clean Code", "Refactoring nə deməkdir?",
                    List.of("Xarici davranışı dəyişmədən kodun daxili strukturunu yaxşılaşdırmaq", "Yeni funksionallıq əlavə etmək",
                            "Bugları düzəltmək", "Testləri silmək"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Cyclomatic complexity nəyi ölçür?",
                    List.of("Kodun məntiqi mürəkkəbliyini (şərti budaqların sayı əsasında)", "Kodun sətir sayını",
                            "Fayl sayını", "Test sayını"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "YAGNI prinsipi nə deməkdir?",
                    List.of("You Aren't Gonna Need It — indi lazım olmayan funksionallığı əlavə etməmək",
                            "Həmişə hər şeyi qabaqcadan planlaşdırmaq", "Kod təkrarı", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Static code analysis alətləri (məs. SonarQube) nə üçün istifadə olunur?",
                    List.of("Kodu icra etmədən potensial problemləri (bug, code smell, təhlükəsizlik) aşkar etmək üçün",
                            "Yalnız kodu compile etmək üçün", "Testləri işə salmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Magic number nə deməkdir?",
                    List.of("Kodda izahsız, sabit dəyər kimi yazılmış rəqəm", "Random ədəd", "Böyük ədəd", "Heç bir mənası yoxdur"),
                    0, Difficulty.EASY),
            new Question("Kod Keyfiyyəti və Clean Code", "Technical debt nəyi ifadə edir?",
                    List.of("Sürətli həll üçün edilən güzəştlərin gələcəkdə əlavə iş tələb etməsi", "Maliyyə borcu",
                            "Layihənin büdcəsi", "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Pair programming-in üstünlüyü nədir?",
                    List.of("Bilik paylaşımı və real-time kod review vasitəsilə keyfiyyətin artması", "Yalnız sürəti artırmaq",
                            "Heç bir üstünlüyü yoxdur", "Yalnız yeni işçilər üçündür"), 0, Difficulty.EASY),
            new Question("Kod Keyfiyyəti və Clean Code", "KISS prinsipi nəyi ifadə edir?",
                    List.of("Keep It Simple, Stupid — kodu lazımsız mürəkkəblikdən qaçındırmaq", "Kompleks kod yazmaq",
                            "Heç bir mənası yoxdur", "Yalnız test üçündür"), 0, Difficulty.EASY),
            new Question("Kod Keyfiyyəti və Clean Code", "Code duplication (kod təkrarı) niyə problemdir?",
                    List.of("Dəyişiklik lazım olduqda hər yerdə ayrıca yenilənməli olur, səhv riski artır", "Heç bir problem deyil",
                            "Performansı artırır", "Yalnız stil məsələsidir"), 0, Difficulty.EASY),
            new Question("Kod Keyfiyyəti və Clean Code", "Naming convention-ların (adlandırma qaydaları) kod keyfiyyətinə təsiri nədir?",
                    List.of("Kodun oxunaqlılığını və başa düşülməsini əhəmiyyətli dərəcədə artırır", "Heç bir təsiri yoxdur",
                            "Yalnız compilerə təsir edir", "Performansı azaldır"), 0, Difficulty.EASY),
            new Question("Kod Keyfiyyəti və Clean Code", "God Class (God Object) anti-pattern-i nədir?",
                    List.of("Çox məsuliyyət daşıyan, aşırı böyük sinif", "Kiçik, fokuslu sinif", "İnterfeys növü", "Heç bir mənası yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Boy Scout Rule (izçi qaydası) proqramlaşdırmada nəyi tövsiyə edir?",
                    List.of("Kodu tapdığından bir az daha təmiz qoymaq", "Kodu heç toxunmamaq", "Hər şeyi yenidən yazmaq",
                            "Heç bir tövsiyəsi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Linting alətləri (məs. Checkstyle) nə üçün istifadə olunur?",
                    List.of("Kod stilini və potensial problemləri avtomatik yoxlamaq üçün", "Kodu compile etmək üçün",
                            "Testləri işə salmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Comments (şərhlər) haqqında Clean Code prinsipi nə deyir?",
                    List.of("Yaxşı adlandırılmış kod özü-özünü izah etməlidir, şərhlər minimuma endirilməlidir", "Hər sətirə şərh yazılmalıdır",
                            "Şərhlər lazımsızdır həmişə", "Heç bir tövsiyəsi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Feature Envy code smell-i nəyi ifadə edir?",
                    List.of("Bir metodun başqa sinifin data/metodları ilə həddindən artıq maraqlanması (öz sinifindən çox)",
                            "Yeni funksionallıq əlavə etmək", "Performans problemi", "Heç bir mənası yoxdur"), 0, Difficulty.HARD),
            new Question("Kod Keyfiyyəti və Clean Code", "Continuous Integration (CI) kod keyfiyyətinə necə kömək edir?",
                    List.of("Hər dəyişiklikdə avtomatik build/test işə salaraq problemləri erkən aşkarlayır", "Heç bir köməyi yoxdur",
                            "Yalnız deployment üçündür", "Kod yazmağı əvəz edir"), 0, Difficulty.MEDIUM),
            new Question("Kod Keyfiyyəti və Clean Code", "Kod baxışında (code review) 'nitpicking' nə deməkdir?",
                    List.of("Əhəmiyyətsiz, kiçik stil məsələlərinə həddindən artıq fokuslanmaq", "Ciddi bugları tapmaq", "Testləri yazmaq",
                            "Heç bir mənası yoxdur"), 0, Difficulty.MEDIUM),

            new Question("Annotations və Reflection", "Java-da annotation nədir?",
                    List.of("Koda əlavə metadata təqdim edən element", "Yeni sinif növü", "Exception növü", "Thread növü"),
                    0, Difficulty.EASY),
            new Question("Annotations və Reflection", "@Override annotasiyası nə üçün istifadə olunur?",
                    List.of("Metodun valideyn sinifdəki metodu override etdiyini compiler-ə bildirmək üçün", "Metodu gizlətmək üçün",
                            "Metodu final etmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("Annotations və Reflection", "Reflection API nə üçün istifadə olunur?",
                    List.of("Runtime-da siniflərin, metodların və sahələrin strukturunu araşdırmaq və manipulyasiya etmək üçün",
                            "Kodu sürətləndirmək üçün", "Yaddaşı azaltmaq üçün", "Thread yaratmaq üçün"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "@FunctionalInterface annotasiyası nə edir?",
                    List.of("İnterfeysin yalnız bir abstract metoda malik olmasını compile zamanı təsdiqləyir", "İnterfeysi sinifə çevirir",
                            "Metodu final edir", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "Class.forName() metodu nə edir?",
                    List.of("Verilmiş adla sinifi runtime-da yükləyir", "Yeni sinif yaradır", "Sinifi silir", "Obyekti klonlayır"),
                    0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "Custom annotation necə yaradılır?",
                    List.of("@interface açar sözü ilə", "class açar sözü ilə", "interface açar sözü ilə", "enum açar sözü ilə"),
                    0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "Retention Policy (@Retention) annotasiyanın nəyini müəyyən edir?",
                    List.of("Annotasiyanın nə qədər müddət saxlanılacağını (SOURCE, CLASS, RUNTIME)", "Annotasiyanın rəngini",
                            "Annotasiyanın adını", "Heç nəyi"), 0, Difficulty.HARD),
            new Question("Annotations və Reflection", "Reflection-un mənfi tərəfi nədir?",
                    List.of("Performans itkisi və compile-time tip təhlükəsizliyinin olmaması", "Heç bir mənfi tərəfi yoxdur",
                            "Yalnız test üçün yararsızdır", "Yaddaşı artırır"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "getDeclaredFields() metodu nə qaytarır?",
                    List.of("Sinifin bütün elan olunmuş sahələrini (private daxil olmaqla)", "Yalnız public sahələri",
                            "Yalnız metodları", "Heç nə"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "Annotation processor nə üçün istifadə olunur?",
                    List.of("Compile zamanı annotasiyalara əsasən kod generasiya etmək və ya yoxlama aparmaq üçün",
                            "Runtime-da annotasiyanı silmək üçün", "Annotasiyanı şifrələmək üçün", "Heç bir məqsədi yoxdur"),
                    0, Difficulty.HARD),
            new Question("Annotations və Reflection", "@Deprecated annotasiyası nə edir?",
                    List.of("Elementin köhnəldiyini və istifadəsinin tövsiyə edilmədiyini bildirir", "Elementi silir",
                            "Elementi final edir", "Heç bir işi yoxdur"), 0, Difficulty.EASY),
            new Question("Annotations və Reflection", "@SuppressWarnings annotasiyası nə üçün istifadə olunur?",
                    List.of("Compiler xəbərdarlıqlarını müəyyən kontekstdə söndürmək üçün", "Xətaları silmək üçün",
                            "Kodu sürətləndirmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "@Target annotasiyası nəyi müəyyən edir?",
                    List.of("Custom annotasiyanın hansı kod elementlərinə (sinif, metod, sahə və s.) tətbiq oluna biləcəyini",
                            "Annotasiyanın rəngini", "Annotasiyanın adını", "Heç nəyi"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "Method.invoke() metodu Reflection API-də nə edir?",
                    List.of("Reflection vasitəsilə metodu dinamik şəkildə çağırır", "Yeni metod yaradır", "Metodu silir", "Heç bir işi yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "setAccessible(true) Reflection-da nə edir?",
                    List.of("Private/protected üzvlərə giriş məhdudiyyətini keçici olaraq aradan qaldırır", "Elementi public edir həmişəlik",
                            "Elementi silir", "Heç bir işi yoxdur"), 0, Difficulty.HARD),
            new Question("Annotations və Reflection", "Spring Framework-də annotation-lar (məs. @Autowired) daxildə necə emal olunur?",
                    List.of("Reflection vasitəsilə runtime-da oxunub müvafiq davranış tətbiq edilir", "Compile zamanı silinir",
                            "Heç vaxt emal olunmur", "Yalnız sənədləşmə üçündür"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "Annotasiyada default dəyər necə təyin edilir?",
                    List.of("'default' açar sözü ilə (məs. String value() default \"\";)", "'=' işarəsi ilə", "Mümkün deyil",
                            "Yalnız konstruktorda"), 0, Difficulty.MEDIUM),
            new Question("Annotations və Reflection", "@Inherited annotasiyası nə edir?",
                    List.of("Custom annotasiyanın alt siniflər tərəfindən irsən alınmasını təmin edir", "Annotasiyanı silir",
                            "Annotasiyanı final edir", "Heç bir işi yoxdur"), 0, Difficulty.HARD),
            new Question("Annotations və Reflection", "Reflection istifadə edərək private sahəyə dəyər təyin etmək mümkündürmü?",
                    List.of("Bəli, setAccessible(true) ilə, amma modul sistemi (Java 9+) məhdudiyyət qoya bilər", "Heç vaxt mümkün deyil",
                            "Yalnız public sahələr üçün", "Heç bir məhdudiyyət yoxdur"), 0, Difficulty.HARD),
            new Question("Annotations və Reflection", "Annotation-lar generic tip parametri qəbul edə bilərmi?",
                    List.of("Xeyr, annotasiyalar generic ola bilməz", "Bəli, sərbəst şəkildə", "Yalnız runtime-da", "Heç bir məhdudiyyət yoxdur"),
                    0, Difficulty.HARD),

            new Question("I/O və Serialization", "Serialization nədir?",
                    List.of("Obyekti bayt ardıcıllığına çevirmək (saxlamaq və ya ötürmək üçün)", "Obyekti silmək",
                            "Obyekti klonlamaq", "Obyekti sıralamaq"), 0, Difficulty.EASY),
            new Question("I/O və Serialization", "Serializable interfeysi nə üçün implement edilir?",
                    List.of("Sinifin obyektlərinin serializasiya oluna bilməsini təmin etmək üçün", "Sinifi final etmək üçün",
                            "Metodları gizlətmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.EASY),
            new Question("I/O və Serialization", "transient açar sözü nə edir?",
                    List.of("Sahənin serializasiya zamanı nəzərə alınmamasını təmin edir", "Sahəni final edir",
                            "Sahəni statik edir", "Heç nə etmir"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "BufferedReader niyə adi FileReader-dən daha sürətlidir?",
                    List.of("Daxili buferləşdirmə ilə oxuma əməliyyatlarının sayını azaldır", "Fərq yoxdur",
                            "Daha az yaddaş istifadə edir", "Yalnız binary fayllar üçündür"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "try-with-resources I/O əməliyyatlarında niyə vacibdir?",
                    List.of("Stream/resource-ların avtomatik və düzgün bağlanmasını təmin edir", "Faylı sürətli oxuyur",
                            "Yaddaşı artırır", "Heç bir əhəmiyyəti yoxdur"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "InputStream və Reader arasındakı fərq nədir?",
                    List.of("InputStream bayt, Reader isə simvol (character) əsaslı oxuma aparır", "Fərq yoxdur",
                            "Reader yalnız fayl üçündür", "InputStream yalnız şəbəkə üçündür"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "serialVersionUID nə üçün istifadə olunur?",
                    List.of("Serializasiya olunmuş sinifin versiyasını idarə etmək üçün, deserialization zamanı uyğunluğu yoxlamaq üçün",
                            "Obyektin ID-si üçün", "Thread ID-si üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("I/O və Serialization", "java.nio.file.Files sinifi nə üçün istifadə olunur?",
                    List.of("Fayl əməliyyatlarını (oxuma, yazma, kopyalama) müasir və rahat şəkildə aparmaq üçün", "Şəbəkə əməliyyatları üçün",
                            "Thread yaratmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "Deserialization zamanı təhlükəsizlik riski nə ola bilər?",
                    List.of("Zərərli serialized data icra olunan koda çevrilə bilər (insecure deserialization)", "Heç bir risk yoxdur",
                            "Yalnız performans azalır", "Fayl böyüyür"), 0, Difficulty.HARD),
            new Question("I/O və Serialization", "System.out.println() daxili olaraq hansı axını istifadə edir?",
                    List.of("Standart çıxış axınını (stdout, PrintStream)", "Standart giriş axınını",
                            "Şəbəkə axınını", "Fayl axınını"), 0, Difficulty.EASY),
            new Question("I/O və Serialization", "Files.readAllLines() metodu nə qaytarır?",
                    List.of("Faylın hər sətrini ehtiva edən List<String>", "Tək String", "byte massivi", "Heç nə"), 0, Difficulty.EASY),
            new Question("I/O və Serialization", "PrintWriter və BufferedWriter arasındakı fərq nədir?",
                    List.of("PrintWriter formatlanmış çıxış (print/println) təqdim edir, BufferedWriter sadəcə buferləşdirilmiş yazı aparır",
                            "Fərq yoxdur", "BufferedWriter formatlaşdırma edir", "PrintWriter yalnız fayl üçündür"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "Java-da fayl oxumaq üçün 'try-with-resources' istifadə edilmədikdə hansı risk yaranır?",
                    List.of("Resurs sızması (resource leak) — fayl handle-ı bağlanmaya bilər", "Heç bir risk yoxdur",
                            "Fayl avtomatik silinir", "Performans artır"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "OutputStream və Writer arasındakı fərq nədir?",
                    List.of("OutputStream bayt, Writer simvol (character) əsaslı yazı aparır", "Fərq yoxdur",
                            "Writer yalnız fayl üçündür", "OutputStream yalnız şəbəkə üçündür"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "Java-da RandomAccessFile nə üçün istifadə olunur?",
                    List.of("Fayla istənilən mövqedən oxumaq/yazmaq üçün (ardıcıl olmayan giriş)", "Yalnız ardıcıl oxumaq üçün",
                            "Yalnız yazmaq üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("I/O və Serialization", "Externalizable interfeysi Serializable-dan nə ilə fərqlənir?",
                    List.of("Serializasiya prosesini tam əl ilə (readExternal/writeExternal) idarə etməyə imkan verir", "Fərq yoxdur",
                            "Daha az nəzarət verir", "Heç bir əlaqəsi yoxdur"), 0, Difficulty.HARD),
            new Question("I/O və Serialization", "Java-da fayl yolu (path) əməliyyatları üçün hansı müasir API tövsiyə olunur?",
                    List.of("java.nio.file.Path və Files sinifləri", "Yalnız java.io.File", "Yalnız String əməliyyatları", "Heç bir tövsiyə yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "Buffered stream-lərin əsas faydası nədir?",
                    List.of("I/O əməliyyatlarının sayını azaldaraq performansı artırmaq", "Heç bir faydası yoxdur",
                            "Yaddaşı azaltmaq", "Yalnız binary fayllar üçündür"), 0, Difficulty.MEDIUM),
            new Question("I/O və Serialization", "Java-da standart giriş (System.in) necə oxunur?",
                    List.of("Scanner və ya BufferedReader vasitəsilə", "Birbaşa String kimi", "Yalnız fayl kimi", "Oxuna bilməz"),
                    0, Difficulty.EASY),
            new Question("I/O və Serialization", "Object Serialization-da 'readObject()' və 'writeObject()' metodlarını əl ilə override etməyin məqsədi nədir?",
                    List.of("Serializasiya prosesinə xüsusi məntiq (məs. şifrələmə, validasiya) əlavə etmək", "Heç bir məqsədi yoxdur",
                            "Prosesi qadağan etmək", "Yalnız performans üçün"), 0, Difficulty.HARD),

            new Question("Serialization Formatları", "JSON formatının əsas üstünlüyü nədir?",
                    List.of("Yüngül, insan tərəfindən oxunaqlı və geniş dil dəstəyinə malikdir", "Yalnız Java-da işləyir",
                            "Binary formatdır", "Heç bir üstünlüyü yoxdur"), 0, Difficulty.EASY),
            new Question("Serialization Formatları", "XML və JSON arasındakı əsas fərq nədir?",
                    List.of("XML tag-əsaslı və daha ətraflıdır, JSON isə daha yığcam və sadədir", "Fərq yoxdur",
                            "JSON yalnız Java-ya aiddir", "XML yalnız verilənlər bazası üçündür"), 0, Difficulty.EASY),
            new Question("Serialization Formatları", "Jackson kitabxanası Java-da nə üçün istifadə olunur?",
                    List.of("Java obyektlərini JSON-a çevirmək və əksinə (serialization/deserialization)", "Yalnız test üçün",
                            "Verilənlər bazası üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Serialization Formatları", "@JsonProperty annotasiyası (Jackson) nə üçün istifadə olunur?",
                    List.of("Java sahəsinin JSON-da hansı adla göstəriləcəyini təyin etmək üçün", "Sahəni gizlətmək üçün",
                            "Sahəni silmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Serialization Formatları", "Protobuf (Protocol Buffers) JSON-dan nə ilə fərqlənir?",
                    List.of("Binary format olduğu üçün daha kompakt və sürətlidir, amma insan tərəfindən birbaşa oxunmur", "Fərq yoxdur",
                            "Protobuf JSON-dan yavaşdır həmişə", "Protobuf yalnız Google məhsullarında işləyir"), 0, Difficulty.MEDIUM),
            new Question("Serialization Formatları", "YAML formatı nə üçün tez-tez konfiqurasiya fayllarında istifadə olunur?",
                    List.of("Oxunaqlı, indentasiya-əsaslı sintaksisə malikdir", "Yalnız binary formatdır", "Yalnız Java üçündür",
                            "Heç bir üstünlüyü yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Serialization Formatları", "JSON-da massiv (array) hansı simvollarla göstərilir?",
                    List.of("Kvadrat mötərizələr [ ]", "Fiqurlu mötərizələr { }", "Adi mötərizələr ( )", "Heç biri"), 0, Difficulty.EASY),
            new Question("Serialization Formatları", "@JsonIgnore annotasiyası (Jackson) nə edir?",
                    List.of("Sahəni serializasiya/deserializasiya zamanı nəzərə almır", "Sahəni silir", "Sahəni final edir", "Heç bir işi yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("Serialization Formatları", "Serialization formatı seçərkən hansı amillər nəzərə alınmalıdır?",
                    List.of("Performans, oxunaqlılıq, ölçü, dillərarası uyğunluq", "Yalnız fayl adı", "Yalnız rəng", "Heç bir amil yoxdur"),
                    0, Difficulty.MEDIUM),
            new Question("Serialization Formatları", "Gson kitabxanası nədir?",
                    List.of("Google-un Java obyektlərini JSON-a çevirmək üçün yaratdığı kitabxana", "Verilənlər bazası", "Test framework-ü",
                            "Web server"), 0, Difficulty.MEDIUM),
            new Question("Serialization Formatları", "XML-in Schema (XSD) ilə validasiyası nəyə imkan verir?",
                    List.of("XML sənədinin strukturunun əvvəlcədən müəyyən edilmiş qaydalara uyğunluğunu yoxlamağa", "XML-i JSON-a çevirməyə",
                            "XML-i şifrələməyə", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Serialization Formatları", "Avro serialization formatının əsas xüsusiyyəti nədir?",
                    List.of("Schema-əsaslıdır və Kafka kimi sistemlərdə geniş istifadə olunur", "Yalnız XML-ə əsaslanır",
                            "Schema tələb etmir", "Yalnız test üçündür"), 0, Difficulty.HARD),
            new Question("Serialization Formatları", "JSON-un null dəyəri necə göstərilir?",
                    List.of("null açar sözü ilə", "\"null\" string kimi", "0 kimi", "Boş sahə kimi"), 0, Difficulty.EASY),
            new Question("Serialization Formatları", "Binary serialization formatlarının (Protobuf, Avro) mətn əsaslı formatlara (JSON, XML) üstünlüyü nədir?",
                    List.of("Daha kiçik ölçü və daha sürətli emal", "Həmişə daha oxunaqlıdır", "Heç bir üstünlüyü yoxdur",
                            "Yalnız test üçün uyğundur"), 0, Difficulty.MEDIUM),
            new Question("Serialization Formatları", "@JsonCreator annotasiyası (Jackson) nə üçün istifadə olunur?",
                    List.of("JSON-dan obyekt yaratmaq üçün istifadə olunacaq konstruktor/factory metodu göstərmək üçün", "Sahəni gizlətmək üçün",
                            "Sahəni silmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.HARD),
            new Question("Serialization Formatları", "JSON Schema nə üçün istifadə olunur?",
                    List.of("JSON sənədinin strukturunu və məhdudiyyətlərini təsvir/validasiya etmək üçün", "JSON-u XML-ə çevirmək üçün",
                            "JSON-u şifrələmək üçün", "Heç bir məqsədi yoxdur"), 0, Difficulty.MEDIUM),
            new Question("Serialization Formatları", "Serializasiya zamanı circular reference (dövri referans) problemi necə həll edilə bilər?",
                    List.of("@JsonManagedReference/@JsonBackReference kimi annotasiyalarla və ya DTO istifadə edərək", "Heç bir həll yolu yoxdur",
                            "Proqram avtomatik həll edir həmişə", "Yalnız binary formatlar bu problemi həll edir"), 0, Difficulty.HARD),
            new Question("Serialization Formatları", "MessagePack nədir?",
                    List.of("JSON-a bənzər, lakin daha kompakt binary serialization formatı", "Mətn əsaslı format", "Yalnız Java üçündür",
                            "Verilənlər bazasıdır"), 0, Difficulty.HARD),
            new Question("Serialization Formatları", "API-lərdə content negotiation zamanı Accept header-i nəyi bildirir?",
                    List.of("Klientin hansı format(lar)da cavab qəbul etmək istədiyini (məs. application/json)",
                            "Server-in cavab formatını məcburi təyin edir", "Heç bir mənası yoxdur", "Yalnız POST sorğularına aiddir"),
                    0, Difficulty.MEDIUM),
            new Question("Serialization Formatları", "Serialization formatının versiyalaşdırılması (schema evolution) niyə vacibdir?",
                    List.of("Köhnə və yeni sistemlər arasında uyğunluğu qorumaq üçün, sahələr əlavə/silindikdə", "Heç bir əhəmiyyəti yoxdur",
                            "Yalnız binary formatlar üçün lazımdır", "Yalnız test mühitində əhəmiyyətlidir"), 0, Difficulty.MEDIUM)
    );

    public static List<Question> get() {
        return QUESTIONS;
    }
}
